In [ ]:
import pandas as pd
import requests
import re
import json
import time

In [ ]:
API_URL = "https://api.perplexity.ai/chat/completions"  # Ajustar según documentación actual
API_KEY = "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"  # Reemplazar con tu clave de API real


def query_perplexity(prompt):
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": "sonar-pro",
        "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
        "max_tokens": 1000,
        "temperature": 0.7
    }
    response = requests.post(API_URL, json=payload, headers=headers)
    if response.status_code == 200:
        data = response.json()
        return data["choices"][0]["message"]["content"]
    else:
        raise Exception(f"Error {response.status_code}: {response.text}")


def augment_dataframe(df):
    # Problem Description	Python Code	Source	Description Error	Error Label
    df_subset = df.copy()

    problem_description=[]
    python_code=[]
    source=[]
    description_error=[]
    error_label=[]

    problems_aug = []
    descriptions_aug = []
    k=1
    for _, row in df_subset.iterrows():
        print("row ",k)
        k+=1
        problem_text = row[0]
        succefull=False
        while not succefull:
          try:
            prompt_problem = f"Give me 5 paraphrases of '{problem_text}' in comma-separated format. like this paraphrase1,paraphrase2,paraphrase3, paraphrase4,paraphrase5"
            print("Execute "+prompt_problem)
            result_problem = query_perplexity(prompt_problem)
            results_problem=re.split(r',\s*\n*',result_problem)
            print("result problem\n\n",results_problem,"\ntam:",len(results_problem))
            if(len(results_problem)==5):
              succefull=True
              print("Succefully")
          except:
            print("Error")
            time.sleep(2)

        time.sleep(2)

        succefull=False
        while not succefull:
          try:
            code_text= row[1]
            prompt_code=f"Remove the comments from '{code_text}' then give me 5 paraphrases changing to equivalent arithmetic or logical operators and moving the positions of the variables without altering the logic of the loop. Give me the answer in JSON format (just json, nothing else) with each paraphrase in a sequential dictionary like this: 'codes': [{{'ex1':, 'ex2':, 'ex3':, 'ex4':,'ex5':}}']"
            print("Execute "+prompt_code)
            result_code = query_perplexity(prompt_code)
            print("result code\n\n",result_code)
            result_json=json.loads(result_code)
            print("Succefully")
            succefull=True
          except:
            print("Error")
            time.sleep(2)

        for rp in results_problem:
          for i,rc in enumerate( result_json["codes"]):
            problem_description.append(row[0])
            python_code.append(row[1])
            source.append(row[2])
            description_error.append(row[3])
            error_label.append(row[4])

            print("Problem: ",rp)
            print("Code: ",rc[f'ex{i+1}'])

            problems_aug.append(rp)
            descriptions_aug.append(rc[f'ex{i+1}'])



        print("Please wait")
        time.sleep(3)

    df_result=pd.DataFrame()
    df_result['Problem Description']=problem_description
    df_result['Python Code']=python_code
    df_result['Source']=source
    df_result['Description Error']=description_error
    df_result['Error Label']=error_label
    df_result['Problem Augmented']=problems_aug
    df_result['Description Augmented']=descriptions_aug




    return df_result

# Load Dataset

In [1]:
archivo_3 = '/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/Tuning/BestModels/ExternData.csv'
train_full = pd.read_csv(archivo_3)

NameError: name 'pd' is not defined

In [ ]:
train_full

,Problem Description,Python Code,Source,Description Error,Error Label
0,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2
1,Sum numbers from 1 to n,def sum_to_n_buggy(n):\n total = 0\n i =...,Based on typical mistakes in Codeforces common...,i is incorrectly incremented,2
2,Prompt user for numbers until 0 is entered,def input_until_zero_buggy():\n num = int(i...,Common error from GeeksforGeeks Python while l...,number is never updated in the loop,2
3,Find first multiple of 7 greater than n,def first_multiple_7_buggy(n):\n i = n + 1\...,Typical error in CodeNet beginner loop problems,i not incremented,2
4,Calculate factorial of n,def factorial_buggy(n):\n result = 1\n w...,Inspired by classic factorial exercises,"decrement by 2, not 1",2
5,Count digits in a positive integer n,def count_digits_buggy(n):\n count = 0\n ...,Inspired by digit counting problems in Codefor...,n not updated inside the loop,2
6,Sum all even numbers up to n,def sum_evens_buggy(n):\n total = 0\n i ...,"CodeChef/Codeforces summing problems, conditio...",loop condition incorrect,1
7,Find a prime number using break,def find_prime_buggy():\n num = 2\n whil...,Inspired by break/continue loop errors from Py...,break outside the if block,2
8,Print cubes of numbers from 1 to n,def print_cubes_buggy(n):\n while i <= n:\n...,"Common initialization error, based on CodeNet ...",i not initialized,0
9,Prompt for password until correct,def prompt_password_buggy():\n password = i...,Typical validation loop error from Python begi...,password requested only once,2
10,"Print numbers from 1 to n, but condition exclu...",def print_numbers_buggy(n):\n i = 1\n wh...,Common inclusive/exclusive error in loops (Cod...,condition excludes n,1
11,Divide a number by 2 repeatedly until it's les...,def divide_repeatedly_buggy(n):\n while n >...,Inspired by CodeNet loop problems involving di...,integer division and missing update,2
12,Sum all digits of n,def sum_digits_buggy(n):\n total = 0\n w...,"Classic digit-processing error, Python/Codeforces",missing update of n,2
13,Count how many times 5 can be subtracted from n,def count_subtract_5_buggy(n):\n count = 0\...,Common mistake in decrement loops (CodeNet/Cod...,n is not updated,2
14,Calculate power using while loop,"def power_buggy(base, exp):\n result = 1\n ...",Power calculation errors in Codeforces/Python ...,missing increment of i,2
15,Check if number is perfect,def is_perfect_buggy(n):\n sum_div = 0\n ...,"Perfect number mistakes, classic math loops",sum calculation and missing increment,2
16,Convert decimal to binary,def decimal_to_binary_buggy(n):\n res = ''\...,"Typical binary conversion loop, Codeforces/Cod...",n not updated inside the loop,2
17,Print items in list until negative is found,def print_until_negative_buggy(lst):\n i = ...,Inspired by control-flow misplacement from Pyt...,break outside the if block,2
18,Count multiples of 3 up to n,def count_mult_3_buggy(n):\n i = 1\n cou...,"Loops with missed accumulation, typical in beg...",count never updated,2
19,Print odd numbers up to n,def print_odds_buggy(n):\n i = 1\n while...,"Increment logic error, Codeforces/CodeChef",i is incremented incorrectly,2
20,Sum the first n natural numbers,def sum_n_buggy(n):\n i = 1\n total = 0\...,"Classic off-by-one loop error, inspired by bas...",loop condition excludes n,1
21,Sum odd numbers up to n,def sum_odds_buggy(n):\n total = 0\n i =...,"Odd number sum, increment bug, beginner mistakes",i increment incorrect,2
22,Count primes up to n,def count_primes_buggy(n):\n count = 0\n ...,Classic loop and condition error in prime coun...,loop condition excludes n,1
23,Read and sum numbers until a negative is entered,def sum_until_negative_buggy():\n total = 0...,"Missing input update bug, shown in tutorials (...",does not read new number inside loop,2
24,Find LCM of two numbers,"def lcm_buggy(a, b):\n num = max(a, b)\n ...","LCM calculation, common loop bug (CodeNet/Code...",missing increment of candidate,2
25,Print Fibonacci sequence up to n terms,"def fibonacci_buggy(n):\n a, b = 0, 1\n ...","Sequence and assignment bug, inspired by class...",assignments out of order,2
26,Count multiples of 5 up to n,def count_mult_5_buggy(n):\n i = 1\n cou...,"Missing i update, common beginner error, CodeC...",i not updated,2
27,Find GCD of two numbers using Euclid algorithm,"def gcd_buggy(a, b):\n while a != b:\n ...","Euclid's algorithm off-by-one/condition bug, C...",condition may cause infinite loop,1
28,Prompt user for positive numbers until 5 are e...,def count_positives_buggy():\n count = 0\n ...,"Input accumulation/counting error, basic progr...",counter never incremented,2
29,Sum multiples of 4 between 1 and n,def sum_mult_4_buggy(n):\n i = 1\n while...,"Sum variable scope bug, inspired by sum/accumu...",sum variable is reset inside the loop,2
30,"Print the factorial of n, but n is not initial...",def buggy_factorial():\n while n > 0:\n ...,Initialization errors are a classic mistake (C...,n is not initialized before the while loop,0
31,Reverse a list but forget to initialize the in...,def buggy_reverse(lst):\n # missing i = len...,"Initialization and condition errors, common in...",missing initialization and undefined variable ...,3
32,"Print numbers from a to b, missing both variab...",def buggy_print_range(b):\n # missing a = 1...,Initialization and update errors frequently se...,missing initialization and wrong update in loo...,4
33,"Sum even numbers in a list, with an off-by-one...",def buggy_sum_evens(lst):\n i = 0\n sum_...,"Condition and update errors, drawn from typica...",wrong condition and no accumulation in loop body,5
34,"Count numbers divisible by 3, fails to initial...",def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6

# Test problem

In [ ]:
text="Check if number is perfect"
prompt = f"Give me 5 paraphrases of '{text}' in comma-separated format"

In [ ]:
prompt

"Give me 5 paraphrases of 'Check if number is perfect' in comma-separated format"

In [ ]:
result = query_perplexity(prompt)

In [ ]:
result

'Determine whether a number is perfect, Test if a number qualifies as perfect, Verify if a number fits the criteria for perfect numbers, Assess if a number is a perfect number, Evaluate whether a number is perfect'

In [ ]:
import re

re.split(r',\s+\n',result)

['Determine whether a number is perfect, Test if a number qualifies as perfect, Verify if a number fits the criteria for perfect numbers, Assess if a number is a perfect number, Evaluate whether a number is perfect']

# Test code

In [ ]:
code=train_full['Python Code'][0]
prompt = f"Remove the comments from '{code}' then give me 5 paraphrases changing to equivalent arithmetic or logical operators and moving the positions of the variables without altering the logic of the cycle. Give me the answer only JSON format with each paraphrase in a sequential dictionary like this: 'codes': [{{'ex1':, 'ex2':, 'ex3':, 'ex4':,'ex5':}}']"

In [ ]:
prompt

"Remove the comments from 'def count_evens_buggy(n):\\n    i = 0\\n    count = 0\\n    while i <= n:\\n        if i % 2 == 0:\\n            count += 1\\n        # missing i += 1\\n    return count' then give me 5 paraphrases changing to equivalent arithmetic or logical operators and moving the positions of the variables without altering the logic of the cycle. Give me the answer only JSON format with each paraphrase in a sequential dictionary like this: 'codes': [{'ex1':, 'ex2':, 'ex3':, 'ex4':,'ex5':}']"

In [ ]:
result = query_perplexity(prompt)

In [ ]:
result

'{\n  "codes": [\n    {\n      "ex1": "def count_evens_buggy(n):\\n    i = 0\\n    count = 0\\n    while not (i > n):\\n        if not (i & 1):\\n            count += 1\\n        # i += 1 is missing\\n    return count"\n    },\n    {\n      "ex2": "def count_evens_buggy(n):\\n    count = 0\\n    i = 0\\n    while i <= n:\\n        if (i % 2 == 0):\\n            count = count + 1\\n        # missing i = i + 1\\n    return count"\n    },\n    {\n      "ex3": "def count_evens_buggy(n):\\n    count = 0\\n    idx = 0\\n    while idx <= n:\\n        if (idx % 2) == 0:\\n            count += 1\\n        # idx += 1 missing\\n    return count"\n    },\n    {\n      "ex4": "def count_evens_buggy(n):\\n    i = 0\\n    total = 0\\n    while i <= n:\\n        if (i & 1) == 0:\\n            total += 1\\n        # i += 1 not present\\n    return total"\n    },\n    {\n      "ex5": "def count_evens_buggy(n):\\n    counter = 0\\n    i = 0\\n    while i <= n:\\n        if (not i % 2):\\n            counter = counter + 1\\n        # i += 1 omitted\\n    return counter"\n    }\n  ]\n}'

In [ ]:
import json
result_json=json.loads(result)

In [ ]:
result_json

{'codes': [{'ex1': 'def count_evens_buggy(n):\n    i = 0\n    count = 0\n    while not (i > n):\n        if not (i & 1):\n            count += 1\n        # i += 1 is missing\n    return count'},
  {'ex2': 'def count_evens_buggy(n):\n    count = 0\n    i = 0\n    while i <= n:\n        if (i % 2 == 0):\n            count = count + 1\n        # missing i = i + 1\n    return count'},
  {'ex3': 'def count_evens_buggy(n):\n    count = 0\n    idx = 0\n    while idx <= n:\n        if (idx % 2) == 0:\n            count += 1\n        # idx += 1 missing\n    return count'},
  {'ex4': 'def count_evens_buggy(n):\n    i = 0\n    total = 0\n    while i <= n:\n        if (i & 1) == 0:\n            total += 1\n        # i += 1 not present\n    return total'},
  {'ex5': 'def count_evens_buggy(n):\n    counter = 0\n    i = 0\n    while i <= n:\n        if (not i % 2):\n            counter = counter + 1\n        # i += 1 omitted\n    return counter'}]}

In [ ]:
print(result_json['codes'][0]['ex1'])

def count_evens_buggy(n):
    i = 0
    count = 0
    while not (i > n):
        if not (i & 1):
            count += 1
        # i += 1 is missing
    return count

# Test everything

In [ ]:
train_full

,Problem Description,Python Code,Source,Description Error,Error Label
0,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2
1,Sum numbers from 1 to n,def sum_to_n_buggy(n):\n total = 0\n i =...,Based on typical mistakes in Codeforces common...,i is incorrectly incremented,2
2,Prompt user for numbers until 0 is entered,def input_until_zero_buggy():\n num = int(i...,Common error from GeeksforGeeks Python while l...,number is never updated in the loop,2
3,Find first multiple of 7 greater than n,def first_multiple_7_buggy(n):\n i = n + 1\...,Typical error in CodeNet beginner loop problems,i not incremented,2
4,Calculate factorial of n,def factorial_buggy(n):\n result = 1\n w...,Inspired by classic factorial exercises,"decrement by 2, not 1",2
5,Count digits in a positive integer n,def count_digits_buggy(n):\n count = 0\n ...,Inspired by digit counting problems in Codefor...,n not updated inside the loop,2
6,Sum all even numbers up to n,def sum_evens_buggy(n):\n total = 0\n i ...,"CodeChef/Codeforces summing problems, conditio...",loop condition incorrect,1
7,Find a prime number using break,def find_prime_buggy():\n num = 2\n whil...,Inspired by break/continue loop errors from Py...,break outside the if block,2
8,Print cubes of numbers from 1 to n,def print_cubes_buggy(n):\n while i <= n:\n...,"Common initialization error, based on CodeNet ...",i not initialized,0
9,Prompt for password until correct,def prompt_password_buggy():\n password = i...,Typical validation loop error from Python begi...,password requested only once,2
10,"Print numbers from 1 to n, but condition exclu...",def print_numbers_buggy(n):\n i = 1\n wh...,Common inclusive/exclusive error in loops (Cod...,condition excludes n,1
11,Divide a number by 2 repeatedly until it's les...,def divide_repeatedly_buggy(n):\n while n >...,Inspired by CodeNet loop problems involving di...,integer division and missing update,2
12,Sum all digits of n,def sum_digits_buggy(n):\n total = 0\n w...,"Classic digit-processing error, Python/Codeforces",missing update of n,2
13,Count how many times 5 can be subtracted from n,def count_subtract_5_buggy(n):\n count = 0\...,Common mistake in decrement loops (CodeNet/Cod...,n is not updated,2
14,Calculate power using while loop,"def power_buggy(base, exp):\n result = 1\n ...",Power calculation errors in Codeforces/Python ...,missing increment of i,2
15,Check if number is perfect,def is_perfect_buggy(n):\n sum_div = 0\n ...,"Perfect number mistakes, classic math loops",sum calculation and missing increment,2
16,Convert decimal to binary,def decimal_to_binary_buggy(n):\n res = ''\...,"Typical binary conversion loop, Codeforces/Cod...",n not updated inside the loop,2
17,Print items in list until negative is found,def print_until_negative_buggy(lst):\n i = ...,Inspired by control-flow misplacement from Pyt...,break outside the if block,2
18,Count multiples of 3 up to n,def count_mult_3_buggy(n):\n i = 1\n cou...,"Loops with missed accumulation, typical in beg...",count never updated,2
19,Print odd numbers up to n,def print_odds_buggy(n):\n i = 1\n while...,"Increment logic error, Codeforces/CodeChef",i is incremented incorrectly,2
20,Sum the first n natural numbers,def sum_n_buggy(n):\n i = 1\n total = 0\...,"Classic off-by-one loop error, inspired by bas...",loop condition excludes n,1
21,Sum odd numbers up to n,def sum_odds_buggy(n):\n total = 0\n i =...,"Odd number sum, increment bug, beginner mistakes",i increment incorrect,2
22,Count primes up to n,def count_primes_buggy(n):\n count = 0\n ...,Classic loop and condition error in prime coun...,loop condition excludes n,1
23,Read and sum numbers until a negative is entered,def sum_until_negative_buggy():\n total = 0...,"Missing input update bug, shown in tutorials (...",does not read new number inside loop,2
24,Find LCM of two numbers,"def lcm_buggy(a, b):\n num = max(a, b)\n ...","LCM calculation, common loop bug (CodeNet/Code...",missing increment of candidate,2
25,Print Fibonacci sequence up to n terms,"def fibonacci_buggy(n):\n a, b = 0, 1\n ...","Sequence and assignment bug, inspired by class...",assignments out of order,2
26,Count multiples of 5 up to n,def count_mult_5_buggy(n):\n i = 1\n cou...,"Missing i update, common beginner error, CodeC...",i not updated,2
27,Find GCD of two numbers using Euclid algorithm,"def gcd_buggy(a, b):\n while a != b:\n ...","Euclid's algorithm off-by-one/condition bug, C...",condition may cause infinite loop,1
28,Prompt user for positive numbers until 5 are e...,def count_positives_buggy():\n count = 0\n ...,"Input accumulation/counting error, basic progr...",counter never incremented,2
29,Sum multiples of 4 between 1 and n,def sum_mult_4_buggy(n):\n i = 1\n while...,"Sum variable scope bug, inspired by sum/accumu...",sum variable is reset inside the loop,2
30,"Print the factorial of n, but n is not initial...",def buggy_factorial():\n while n > 0:\n ...,Initialization errors are a classic mistake (C...,n is not initialized before the while loop,0
31,Reverse a list but forget to initialize the in...,def buggy_reverse(lst):\n # missing i = len...,"Initialization and condition errors, common in...",missing initialization and undefined variable ...,3
32,"Print numbers from a to b, missing both variab...",def buggy_print_range(b):\n # missing a = 1...,Initialization and update errors frequently se...,missing initialization and wrong update in loo...,4
33,"Sum even numbers in a list, with an off-by-one...",def buggy_sum_evens(lst):\n i = 0\n sum_...,"Condition and update errors, drawn from typica...",wrong condition and no accumulation in loop body,5
34,"Count numbers divisible by 3, fails to initial...",def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6

In [ ]:
for i, row in train_full.iterrows():
  print(i,row[0])

0 Count how many even numbers are up to n
1 Sum numbers from 1 to n
2 Prompt user for numbers until 0 is entered
3 Find first multiple of 7 greater than n
4 Calculate factorial of n
5 Count digits in a positive integer n
6 Sum all even numbers up to n
7 Find a prime number using break
8 Print cubes of numbers from 1 to n
9 Prompt for password until correct
10 Print numbers from 1 to n, but condition excludes n
11 Divide a number by 2 repeatedly until it's less than 1
12 Sum all digits of n
13 Count how many times 5 can be subtracted from n
14 Calculate power using while loop
15 Check if number is perfect
16 Convert decimal to binary
17 Print items in list until negative is found
18 Count multiples of 3 up to n
19 Print odd numbers up to n
20 Sum the first n natural numbers
21 Sum odd numbers up to n
22 Count primes up to n
23 Read and sum numbers until a negative is entered
24 Find LCM of two numbers
25 Print Fibonacci sequence up to n terms
26 Count multiples of 5 up to n
27 Find GCD of two numbers using Euclid algorithm
28 Prompt user for positive numbers until 5 are entered
29 Sum multiples of 4 between 1 and n
30 Print the factorial of n, but n is not initialized before entering the while loop
31 Reverse a list but forget to initialize the index, and use an undefined variable in the condition
32 Print numbers from a to b, missing both variable initialization and incorrect update inside the loop
33 Sum even numbers in a list, with an off-by-one loop condition and never incrementing the result in the loop body
34 Count numbers divisible by 3, fails to initialize counter, uses incorrect condition, and does not update counter in the loop

/tmp/ipython-input-1784881177.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(i,row[0])

In [ ]:
train_full.iloc[30:35,0]

30    Print the factorial of n, but n is not initial...
31    Reverse a list but forget to initialize the in...
32    Print numbers from a to b, missing both variab...
33    Sum even numbers in a list, with an off-by-one...
34    Count numbers divisible by 3, fails to initial...
Name: Problem Description, dtype: object

In [ ]:
train_full.iloc[30,0]='Print the factorial of n'
train_full.iloc[31,0]='Reverse a list'
train_full.iloc[32,0]='Print numbers from a to b'
train_full.iloc[33,0]='Sum even numbers in a list'
train_full.iloc[34,0]='Count numbers divisible by 3'

In [ ]:
train_full.to_csv('/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/Tuning/BestModels/ExAuCorrection.csv',
                  index=False)

In [ ]:
train_full=pd.read_csv('/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/Tuning/BestModels/ExAuCorrection.csv')

In [ ]:
train_full

,Problem Description,Python Code,Source,Description Error,Error Label
0,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2
1,Sum numbers from 1 to n,def sum_to_n_buggy(n):\n total = 0\n i =...,Based on typical mistakes in Codeforces common...,i is incorrectly incremented,2
2,Prompt user for numbers until 0 is entered,def input_until_zero_buggy():\n num = int(i...,Common error from GeeksforGeeks Python while l...,number is never updated in the loop,2
3,Find first multiple of 7 greater than n,def first_multiple_7_buggy(n):\n i = n + 1\...,Typical error in CodeNet beginner loop problems,i not incremented,2
4,Calculate factorial of n,def factorial_buggy(n):\n result = 1\n w...,Inspired by classic factorial exercises,"decrement by 2, not 1",2
5,Count digits in a positive integer n,def count_digits_buggy(n):\n count = 0\n ...,Inspired by digit counting problems in Codefor...,n not updated inside the loop,2
6,Sum all even numbers up to n,def sum_evens_buggy(n):\n total = 0\n i ...,"CodeChef/Codeforces summing problems, conditio...",loop condition incorrect,1
7,Find a prime number using break,def find_prime_buggy():\n num = 2\n whil...,Inspired by break/continue loop errors from Py...,break outside the if block,2
8,Print cubes of numbers from 1 to n,def print_cubes_buggy(n):\n while i <= n:\n...,"Common initialization error, based on CodeNet ...",i not initialized,0
9,Prompt for password until correct,def prompt_password_buggy():\n password = i...,Typical validation loop error from Python begi...,password requested only once,2
10,"Print numbers from 1 to n, but condition exclu...",def print_numbers_buggy(n):\n i = 1\n wh...,Common inclusive/exclusive error in loops (Cod...,condition excludes n,1
11,Divide a number by 2 repeatedly until it's les...,def divide_repeatedly_buggy(n):\n while n >...,Inspired by CodeNet loop problems involving di...,integer division and missing update,2
12,Sum all digits of n,def sum_digits_buggy(n):\n total = 0\n w...,"Classic digit-processing error, Python/Codeforces",missing update of n,2
13,Count how many times 5 can be subtracted from n,def count_subtract_5_buggy(n):\n count = 0\...,Common mistake in decrement loops (CodeNet/Cod...,n is not updated,2
14,Calculate power using while loop,"def power_buggy(base, exp):\n result = 1\n ...",Power calculation errors in Codeforces/Python ...,missing increment of i,2
15,Check if number is perfect,def is_perfect_buggy(n):\n sum_div = 0\n ...,"Perfect number mistakes, classic math loops",sum calculation and missing increment,2
16,Convert decimal to binary,def decimal_to_binary_buggy(n):\n res = ''\...,"Typical binary conversion loop, Codeforces/Cod...",n not updated inside the loop,2
17,Print items in list until negative is found,def print_until_negative_buggy(lst):\n i = ...,Inspired by control-flow misplacement from Pyt...,break outside the if block,2
18,Count multiples of 3 up to n,def count_mult_3_buggy(n):\n i = 1\n cou...,"Loops with missed accumulation, typical in beg...",count never updated,2
19,Print odd numbers up to n,def print_odds_buggy(n):\n i = 1\n while...,"Increment logic error, Codeforces/CodeChef",i is incremented incorrectly,2
20,Sum the first n natural numbers,def sum_n_buggy(n):\n i = 1\n total = 0\...,"Classic off-by-one loop error, inspired by bas...",loop condition excludes n,1
21,Sum odd numbers up to n,def sum_odds_buggy(n):\n total = 0\n i =...,"Odd number sum, increment bug, beginner mistakes",i increment incorrect,2
22,Count primes up to n,def count_primes_buggy(n):\n count = 0\n ...,Classic loop and condition error in prime coun...,loop condition excludes n,1
23,Read and sum numbers until a negative is entered,def sum_until_negative_buggy():\n total = 0...,"Missing input update bug, shown in tutorials (...",does not read new number inside loop,2
24,Find LCM of two numbers,"def lcm_buggy(a, b):\n num = max(a, b)\n ...","LCM calculation, common loop bug (CodeNet/Code...",missing increment of candidate,2
25,Print Fibonacci sequence up to n terms,"def fibonacci_buggy(n):\n a, b = 0, 1\n ...","Sequence and assignment bug, inspired by class...",assignments out of order,2
26,Count multiples of 5 up to n,def count_mult_5_buggy(n):\n i = 1\n cou...,"Missing i update, common beginner error, CodeC...",i not updated,2
27,Find GCD of two numbers using Euclid algorithm,"def gcd_buggy(a, b):\n while a != b:\n ...","Euclid's algorithm off-by-one/condition bug, C...",condition may cause infinite loop,1
28,Prompt user for positive numbers until 5 are e...,def count_positives_buggy():\n count = 0\n ...,"Input accumulation/counting error, basic progr...",counter never incremented,2
29,Sum multiples of 4 between 1 and n,def sum_mult_4_buggy(n):\n i = 1\n while...,"Sum variable scope bug, inspired by sum/accumu...",sum variable is reset inside the loop,2
30,Print the factorial of n,def buggy_factorial():\n while n > 0:\n ...,Initialization errors are a classic mistake (C...,n is not initialized before the while loop,0
31,Reverse a list,def buggy_reverse(lst):\n # missing i = len...,"Initialization and condition errors, common in...",missing initialization and undefined variable ...,3
32,Print numbers from a to b,def buggy_print_range(b):\n # missing a = 1...,Initialization and update errors frequently se...,missing initialization and wrong update in loo...,4
33,Sum even numbers in a list,def buggy_sum_evens(lst):\n i = 0\n sum_...,"Condition and update errors, drawn from typica...",wrong condition and no accumulation in loop body,5
34,Count numbers divisible by 3,def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6

In [ ]:
df_augmented = augment_dataframe(train_full)

row  1
Execute Give me 5 paraphrases of 'Count how many even numbers are up to n' in comma-separated format. like this paraphrase1,paraphrase2,paraphrase3, paraphrase4,paraphrase5

/tmp/ipython-input-2253495512.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  problem_text = row[0]

result problem

 ['Determine the number of even numbers less than or equal to n', 'Find out how many even numbers exist up to n', 'Calculate the total even numbers from 1 to n', 'Count the even integers up to n', 'Figure out how many even numbers are there up to n']
tam: 5
Succefully

/tmp/ipython-input-2253495512.py:64: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  code_text= row[1]

Execute Remove the comments from 'def count_evens_buggy(n):\n    i = 0\n    count = 0\n    while i <= n:\n        if i % 2 == 0:\n            count += 1\n        # missing i += 1\n    return count' then give me 5 paraphrases changing to equivalent arithmetic or logical operators and moving the positions of the variables without altering the logic of the loop. Give me the answer in JSON format (just json, nothing else) with each paraphrase in a sequential dictionary like this: 'codes': [{'ex1':, 'ex2':, 'ex3':, 'ex4':,'ex5':}']
result code

 {
  "codes": [
    {
      "ex1": "def count_evens_buggy(n):\n    count = 0\n    i = 0\n    while i <= n:\n        if (i & 1) == 0:\n            count += 1\n        i += 1\n    return count"
    },
    {
      "ex2": "def count_evens_buggy(n):\n    i = 0\n    total = 0\n    while not (i > n):\n        if not i % 2:\n            total += 1\n        i += 1\n    return total"
    },
    {
      "ex3": "def count_evens_buggy(n):\n    i = 0\n    c = 0\n    while i <= n:\n        c += int(i % 2 == 0)\n        i += 1\n    return c"
    },
    {
      "ex4": "def count_evens_buggy(n):\n    count = 0\n    i = 0\n    while i <= n:\n        count += (i ^ 1 == i + 1)\n        i += 1\n    return count"
    },
    {
      "ex5": "def count_evens_buggy(n):\n    idx = 0\n    res = 0\n    while idx <= n:\n        if idx % 2 == 0:\n            res = res + 1\n        idx = idx + 1\n    return res"
    }
  ]
}
Succefully
Problem:  Determine the number of even numbers less than or equal to n
Code:  def count_evens_buggy(n):
    count = 0
    i = 0
    while i <= n:
        if (i & 1) == 0:
            count += 1
        i += 1
    return count
Problem:  Determine the number of even numbers less than or equal to n
Code:  def count_evens_buggy(n):
    i = 0
    total = 0
    while not (i > n):
        if not i % 2:
            total += 1
        i += 1
    return total
Problem:  Determine the number of even numbers less than or equal to n
Code:  def count_evens_buggy(n):
    i = 0
    c = 0
    while i <= n:
        c += int(i % 2 == 0)
        i += 1
    return c
Problem:  Determine the number of even numbers less than or equal to n
Code:  def count_evens_buggy(n):
    count = 0
    i = 0
    while i <= n:
        count += (i ^ 1 == i + 1)
        i += 1
    return count
Problem:  Determine the number of even numbers less than or equal to n
Code:  def count_evens_buggy(n):
    idx = 0
    res = 0
    while idx <= n:
        if idx % 2 == 0:
            res = res + 1
        idx = idx + 1
    return res
Problem:  Find out how many even numbers exist up to n
Code:  def count_evens_buggy(n):
    count = 0
    i = 0
    while i <= n:
        if (i & 1) == 0:
            count += 1
        i += 1
    return count
Problem:  Find out how many even numbers exist up to n
Code:  def count_evens_buggy(n):
    i = 0
    total = 0
    while not (i > n):
        if not i % 2:
            total += 1
        i += 1
    return total
Problem:  Find out how many even numbers exist up to n
Code:  def count_evens_buggy(n):
    i = 0
    c = 0
    while i <= n:
        c += int(i % 2 == 0)
        i += 1
    return c
Problem:  Find out how many even numbers exist up to n
Code:  def count_evens_buggy(n):
    count = 0
    i = 0
    while i <= n:
        count += (i ^ 1 == i + 1)
        i += 1
    return count
Problem:  Find out how many even numbers exist up to n
Code:  def count_evens_buggy(n):
    idx = 0
    res = 0
    while idx <= n:
        if idx % 2 == 0:
            res = res + 1
        idx = idx + 1
    return res
Problem:  Calculate the total even numbers from 1 to n
Code:  def count_evens_buggy(n):
    count = 0
    i = 0
    while i <= n:
        if (i & 1) == 0:
            count += 1
        i += 1
    return count
Problem:  Calculate the total even numbers from 1 to n
Code:  def count_evens_buggy(n):
    i = 0
    total = 0
    while not (i > n):
        if not i % 2:
            total += 1
        i += 1
    return total
Problem:  Calculate the total even numbers from 1 to n
Code:  def count_evens_buggy(n):
    i = 0
    c = 0
    while i <= n:
        c += int(i % 2 == 0)
        i += 1
    return c
Problem:  Calculate the total even numbers from 1 to n
Code:  def count_evens_buggy(n):
    count = 0
    i = 0
    while i <= n:
        count += (i ^ 1 == i + 1)
        i += 1
    return count
Problem:  Calculate the total even numbers from 1 to n
Code:  def count_evens_buggy(n):
    idx = 0
    res = 0
    while idx <= n:
        if idx % 2 == 0:
            res = res + 1
        idx = idx + 1
    return res
Problem:  Count the even integers up to n
Code:  def count_evens_buggy(n):
    count = 0
    i = 0
    while i <= n:
        if (i & 1) == 0:
            count += 1
        i += 1
    return count
Problem:  Count the even integers up to n
Code:  def count_evens_buggy(n):
    i = 0
    total = 0
    while not (i > n):
        if not i % 2:
            total += 1
        i += 1
    return total
Problem:  Count the even integers up to n
Code:  def count_evens_buggy(n):
    i = 0
    c = 0
    while i <= n:
        c += int(i % 2 == 0)
        i += 1
    return c
Problem:  Count the even integers up to n
Code:  def count_evens_buggy(n):
    count = 0
    i = 0
    while i <= n:
        count += (i ^ 1 == i + 1)
        i += 1
    return count
Problem:  Count the even integers up to n
Code:  def count_evens_buggy(n):
    idx = 0
    res = 0
    while idx <= n:
        if idx % 2 == 0:
            res = res + 1
        idx = idx + 1
    return res
Problem:  Figure out how many even numbers are there up to n
Code:  def count_evens_buggy(n):
    count = 0
    i = 0
    while i <= n:
        if (i & 1) == 0:
            count += 1
        i += 1
    return count
Problem:  Figure out how many even numbers are there up to n
Code:  def count_evens_buggy(n):
    i = 0
    total = 0
    while not (i > n):
        if not i % 2:
            total += 1
        i += 1
    return total
Problem:  Figure out how many even numbers are there up to n
Code:  def count_evens_buggy(n):
    i = 0
    c = 0
    while i <= n:
        c += int(i % 2 == 0)
        i += 1
    return c
Problem:  Figure out how many even numbers are there up to n
Code:  def count_evens_buggy(n):
    count = 0
    i = 0
    while i <= n:
        count += (i ^ 1 == i + 1)
        i += 1
    return count
Problem:  Figure out how many even numbers are there up to n
Code:  def count_evens_buggy(n):
    idx = 0
    res = 0
    while idx <= n:
        if idx % 2 == 0:
            res = res + 1
        idx = idx + 1
    return res
Please wait

/tmp/ipython-input-2253495512.py:78: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  problem_description.append(row[0])
/tmp/ipython-input-2253495512.py:79: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  python_code.append(row[1])
/tmp/ipython-input-2253495512.py:80: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  source.append(row[2])
/tmp/ipython-input-2253495512.py:81: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  description_error.append(row[3])
/tmp/ipython-input-2253495512.py:82: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  error_label.append(row[4])

Streaming output truncated to the last 5000 lines.
    while 1 < n:
        result = n * result
        n = n - 2
    return result
Problem:  determine n factorial
Code:  def factorial_buggy(n):
    result = 1
    while 1 < n:
        result = n * result
        n = n - 2
    return result
Problem:  find the value of n!
Code:  def factorial_buggy(n):
    result = 1
    while 1 < n:
        result = n * result
        n = n - 2
    return result
Problem:  work out the factorial for n
Code:  def factorial_buggy(n):
    result = 1
    while 1 < n:
        result = n * result
        n = n - 2
    return result
Problem:  evaluate the factorial of n
Code:  def factorial_buggy(n):
    result = 1
    while 1 < n:
        result = n * result
        n = n - 2
    return result
Please wait
row  6
Execute Give me 5 paraphrases of 'Count digits in a positive integer n' in comma-separated format. like this paraphrase1,paraphrase2,paraphrase3, paraphrase4,paraphrase5
result problem

 ['Determine the number of digits in a positive integer n', 'find how many digits are present in a positive integer n', 'compute the digit count of a positive integer n', 'calculate the total digits in a positive integer n', 'identify the number of digits in a positive integer n']
tam: 5
Succefully
Execute Remove the comments from 'def count_digits_buggy(n):\n    count = 0\n    while n > 0:\n        n % 10\n        count += 1\n    return count' then give me 5 paraphrases changing to equivalent arithmetic or logical operators and moving the positions of the variables without altering the logic of the loop. Give me the answer in JSON format (just json, nothing else) with each paraphrase in a sequential dictionary like this: 'codes': [{'ex1':, 'ex2':, 'ex3':, 'ex4':,'ex5':}']
result code

 {
  "codes": [
    {
      "ex1": "def count_digits_buggy(n):\n    count = 0\n    while 0 < n:\n        count += 1\n        n = n % 100 + (n // 10) * 0\n    return count"
    },
    {
      "ex2": "def count_digits_buggy(number):\n    c = 0\n    while number > 0:\n        c = c + 1\n        number += 0 * (number // 10)\n    return c"
    },
    {
      "ex3": "def count_digits_buggy(x):\n    result = 0\n    while x and x > 0:\n        result = result + 1\n        x = x - (x // 10) * 0\n    return result"
    },
    {
      "ex4": "def count_digits_buggy(num):\n    digits = 0\n    while not (num <= 0):\n        digits = digits + 1\n        num = num - (num % 10) * 0\n    return digits"
    },
    {
      "ex5": "def count_digits_buggy(val):\n    total = 0\n    while val != 0 and val > 0:\n        total += 1\n        val = val - (val % 10) + 0\n    return total"
    }
  ]
}
Succefully
Problem:  Determine the number of digits in a positive integer n
Code:  def count_digits_buggy(n):
    count = 0
    while 0 < n:
        count += 1
        n = n % 100 + (n // 10) * 0
    return count
Problem:  Determine the number of digits in a positive integer n
Code:  def count_digits_buggy(number):
    c = 0
    while number > 0:
        c = c + 1
        number += 0 * (number // 10)
    return c
Problem:  Determine the number of digits in a positive integer n
Code:  def count_digits_buggy(x):
    result = 0
    while x and x > 0:
        result = result + 1
        x = x - (x // 10) * 0
    return result
Problem:  Determine the number of digits in a positive integer n
Code:  def count_digits_buggy(num):
    digits = 0
    while not (num <= 0):
        digits = digits + 1
        num = num - (num % 10) * 0
    return digits
Problem:  Determine the number of digits in a positive integer n
Code:  def count_digits_buggy(val):
    total = 0
    while val != 0 and val > 0:
        total += 1
        val = val - (val % 10) + 0
    return total
Problem:  find how many digits are present in a positive integer n
Code:  def count_digits_buggy(n):
    count = 0
    while 0 < n:
        count += 1
        n = n % 100 + (n // 10) * 0
    return count
Problem:  find how many digits are present in a positive integer n
Code:  def count_digits_buggy(number):
    c = 0
    while number > 0:
        c = c + 1
        number += 0 * (number // 10)
    return c
Problem:  find how many digits are present in a positive integer n
Code:  def count_digits_buggy(x):
    result = 0
    while x and x > 0:
        result = result + 1
        x = x - (x // 10) * 0
    return result
Problem:  find how many digits are present in a positive integer n
Code:  def count_digits_buggy(num):
    digits = 0
    while not (num <= 0):
        digits = digits + 1
        num = num - (num % 10) * 0
    return digits
Problem:  find how many digits are present in a positive integer n
Code:  def count_digits_buggy(val):
    total = 0
    while val != 0 and val > 0:
        total += 1
        val = val - (val % 10) + 0
    return total
Problem:  compute the digit count of a positive integer n
Code:  def count_digits_buggy(n):
    count = 0
    while 0 < n:
        count += 1
        n = n % 100 + (n // 10) * 0
    return count
Problem:  compute the digit count of a positive integer n
Code:  def count_digits_buggy(number):
    c = 0
    while number > 0:
        c = c + 1
        number += 0 * (number // 10)
    return c
Problem:  compute the digit count of a positive integer n
Code:  def count_digits_buggy(x):
    result = 0
    while x and x > 0:
        result = result + 1
        x = x - (x // 10) * 0
    return result
Problem:  compute the digit count of a positive integer n
Code:  def count_digits_buggy(num):
    digits = 0
    while not (num <= 0):
        digits = digits + 1
        num = num - (num % 10) * 0
    return digits
Problem:  compute the digit count of a positive integer n
Code:  def count_digits_buggy(val):
    total = 0
    while val != 0 and val > 0:
        total += 1
        val = val - (val % 10) + 0
    return total
Problem:  calculate the total digits in a positive integer n
Code:  def count_digits_buggy(n):
    count = 0
    while 0 < n:
        count += 1
        n = n % 100 + (n // 10) * 0
    return count
Problem:  calculate the total digits in a positive integer n
Code:  def count_digits_buggy(number):
    c = 0
    while number > 0:
        c = c + 1
        number += 0 * (number // 10)
    return c
Problem:  calculate the total digits in a positive integer n
Code:  def count_digits_buggy(x):
    result = 0
    while x and x > 0:
        result = result + 1
        x = x - (x // 10) * 0
    return result
Problem:  calculate the total digits in a positive integer n
Code:  def count_digits_buggy(num):
    digits = 0
    while not (num <= 0):
        digits = digits + 1
        num = num - (num % 10) * 0
    return digits
Problem:  calculate the total digits in a positive integer n
Code:  def count_digits_buggy(val):
    total = 0
    while val != 0 and val > 0:
        total += 1
        val = val - (val % 10) + 0
    return total
Problem:  identify the number of digits in a positive integer n
Code:  def count_digits_buggy(n):
    count = 0
    while 0 < n:
        count += 1
        n = n % 100 + (n // 10) * 0
    return count
Problem:  identify the number of digits in a positive integer n
Code:  def count_digits_buggy(number):
    c = 0
    while number > 0:
        c = c + 1
        number += 0 * (number // 10)
    return c
Problem:  identify the number of digits in a positive integer n
Code:  def count_digits_buggy(x):
    result = 0
    while x and x > 0:
        result = result + 1
        x = x - (x // 10) * 0
    return result
Problem:  identify the number of digits in a positive integer n
Code:  def count_digits_buggy(num):
    digits = 0
    while not (num <= 0):
        digits = digits + 1
        num = num - (num % 10) * 0
    return digits
Problem:  identify the number of digits in a positive integer n
Code:  def count_digits_buggy(val):
    total = 0
    while val != 0 and val > 0:
        total += 1
        val = val - (val % 10) + 0
    return total
Please wait
row  7
Execute Give me 5 paraphrases of 'Sum all even numbers up to n' in comma-separated format. like this paraphrase1,paraphrase2,paraphrase3, paraphrase4,paraphrase5
result problem

 ['Add together all even numbers less than or equal to n', 'calculate the sum of every even integer up to n', 'find the total of all even numbers from 1 to n', 'determine the sum of even numbers up to and including n', 'total all even numbers that do not exceed n']
tam: 5
Succefully
Execute Remove the comments from 'def sum_evens_buggy(n):\n    total = 0\n    i = 2\n    while i < n:\n        total += i\n        i += 2\n    return total' then give me 5 paraphrases changing to equivalent arithmetic or logical operators and moving the positions of the variables without altering the logic of the loop. Give me the answer in JSON format (just json, nothing else) with each paraphrase in a sequential dictionary like this: 'codes': [{'ex1':, 'ex2':, 'ex3':, 'ex4':,'ex5':}']
result code

 {
  "codes": [
    {
      "ex1": "def sum_evens_buggy(n):\n    total = 0\n    i = 2\n    while n > i:\n        total += i\n        i = i + 2\n    return total"
    },
    {
      "ex2": "def sum_evens_buggy(n):\n    i = 2\n    total = 0\n    while i < n:\n        total = total + i\n        i += 2\n    return total"
    },
    {
      "ex3": "def sum_evens_buggy(n):\n    total, i = 0, 2\n    while not (i >= n):\n        total += i\n        i += 2\n    return total"
    },
    {
      "ex4": "def sum_evens_buggy(n):\n    total = 0\n    i = 2\n    while i < n:\n        total = total + i\n        i = i + 2\n    return total"
    },
    {
      "ex5": "def sum_evens_buggy(n):\n    i = 2\n    total = 0\n    while i < n:\n        total += i\n        i = i + 2\n    return total"
    }
  ]
}
Succefully
Problem:  Add together all even numbers less than or equal to n
Code:  def sum_evens_buggy(n):
    total = 0
    i = 2
    while n > i:
        total += i
        i = i + 2
    return total
Problem:  Add together all even numbers less than or equal to n
Code:  def sum_evens_buggy(n):
    i = 2
    total = 0
    while i < n:
        total = total + i
        i += 2
    return total
Problem:  Add together all even numbers less than or equal to n
Code:  def sum_evens_buggy(n):
    total, i = 0, 2
    while not (i >= n):
        total += i
        i += 2
    return total
Problem:  Add together all even numbers less than or equal to n
Code:  def sum_evens_buggy(n):
    total = 0
    i = 2
    while i < n:
        total = total + i
        i = i + 2
    return total
Problem:  Add together all even numbers less than or equal to n
Code:  def sum_evens_buggy(n):
    i = 2
    total = 0
    while i < n:
        total += i
        i = i + 2
    return total
Problem:  calculate the sum of every even integer up to n
Code:  def sum_evens_buggy(n):
    total = 0
    i = 2
    while n > i:
        total += i
        i = i + 2
    return total
Problem:  calculate the sum of every even integer up to n
Code:  def sum_evens_buggy(n):
    i = 2
    total = 0
    while i < n:
        total = total + i
        i += 2
    return total
Problem:  calculate the sum of every even integer up to n
Code:  def sum_evens_buggy(n):
    total, i = 0, 2
    while not (i >= n):
        total += i
        i += 2
    return total
Problem:  calculate the sum of every even integer up to n
Code:  def sum_evens_buggy(n):
    total = 0
    i = 2
    while i < n:
        total = total + i
        i = i + 2
    return total
Problem:  calculate the sum of every even integer up to n
Code:  def sum_evens_buggy(n):
    i = 2
    total = 0
    while i < n:
        total += i
        i = i + 2
    return total
Problem:  find the total of all even numbers from 1 to n
Code:  def sum_evens_buggy(n):
    total = 0
    i = 2
    while n > i:
        total += i
        i = i + 2
    return total
Problem:  find the total of all even numbers from 1 to n
Code:  def sum_evens_buggy(n):
    i = 2
    total = 0
    while i < n:
        total = total + i
        i += 2
    return total
Problem:  find the total of all even numbers from 1 to n
Code:  def sum_evens_buggy(n):
    total, i = 0, 2
    while not (i >= n):
        total += i
        i += 2
    return total
Problem:  find the total of all even numbers from 1 to n
Code:  def sum_evens_buggy(n):
    total = 0
    i = 2
    while i < n:
        total = total + i
        i = i + 2
    return total
Problem:  find the total of all even numbers from 1 to n
Code:  def sum_evens_buggy(n):
    i = 2
    total = 0
    while i < n:
        total += i
        i = i + 2
    return total
Problem:  determine the sum of even numbers up to and including n
Code:  def sum_evens_buggy(n):
    total = 0
    i = 2
    while n > i:
        total += i
        i = i + 2
    return total
Problem:  determine the sum of even numbers up to and including n
Code:  def sum_evens_buggy(n):
    i = 2
    total = 0
    while i < n:
        total = total + i
        i += 2
    return total
Problem:  determine the sum of even numbers up to and including n
Code:  def sum_evens_buggy(n):
    total, i = 0, 2
    while not (i >= n):
        total += i
        i += 2
    return total
Problem:  determine the sum of even numbers up to and including n
Code:  def sum_evens_buggy(n):
    total = 0
    i = 2
    while i < n:
        total = total + i
        i = i + 2
    return total
Problem:  determine the sum of even numbers up to and including n
Code:  def sum_evens_buggy(n):
    i = 2
    total = 0
    while i < n:
        total += i
        i = i + 2
    return total
Problem:  total all even numbers that do not exceed n
Code:  def sum_evens_buggy(n):
    total = 0
    i = 2
    while n > i:
        total += i
        i = i + 2
    return total
Problem:  total all even numbers that do not exceed n
Code:  def sum_evens_buggy(n):
    i = 2
    total = 0
    while i < n:
        total = total + i
        i += 2
    return total
Problem:  total all even numbers that do not exceed n
Code:  def sum_evens_buggy(n):
    total, i = 0, 2
    while not (i >= n):
        total += i
        i += 2
    return total
Problem:  total all even numbers that do not exceed n
Code:  def sum_evens_buggy(n):
    total = 0
    i = 2
    while i < n:
        total = total + i
        i = i + 2
    return total
Problem:  total all even numbers that do not exceed n
Code:  def sum_evens_buggy(n):
    i = 2
    total = 0
    while i < n:
        total += i
        i = i + 2
    return total
Please wait
row  8
Execute Give me 5 paraphrases of 'Find a prime number using break' in comma-separated format. like this paraphrase1,paraphrase2,paraphrase3, paraphrase4,paraphrase5
result problem

 ['Identify a prime number with the help of break', 'use break to locate a prime number', 'determine a prime number utilizing break', 'find a prime by implementing break', 'discover a prime number using the break statement']
tam: 5
Succefully
Execute Remove the comments from 'def find_prime_buggy():\n    num = 2\n    while True:\n        is_prime = True\n        divisor = 2\n        while divisor < num:\n            if num % divisor == 0:\n                is_prime = False\n            divisor += 1\n        break\n        if is_prime:\n            return num\n        num += 1' then give me 5 paraphrases changing to equivalent arithmetic or logical operators and moving the positions of the variables without altering the logic of the loop. Give me the answer in JSON format (just json, nothing else) with each paraphrase in a sequential dictionary like this: 'codes': [{'ex1':, 'ex2':, 'ex3':, 'ex4':,'ex5':}']
result code

 {
  "codes": [
    {
      "ex1": "def find_prime_buggy():\n    candidate = 2\n    while True:\n        prime_flag = not False\n        test_div = 2\n        while test_div != candidate:\n            if not (candidate % test_div):\n                prime_flag = False\n            test_div = test_div + 1\n        break\n        if prime_flag == True:\n            return candidate\n        candidate = candidate + 1"
    },
    {
      "ex2": "def find_prime_buggy():\n    n = 2\n    while 1:\n        flag = True\n        d = 2\n        while d < n:\n            if n % d is 0:\n                flag = False\n            d += 1\n        break\n        if flag:\n            return n\n        n += 1"
    },
    {
      "ex3": "def find_prime_buggy():\n    x = 2\n    while True:\n        valid = True\n        y = 2\n        while y < x:\n            if 0 == x % y:\n                valid = False\n            y += 1\n        break\n        if valid is True:\n            return x\n        x += 1"
    },
    {
      "ex4": "def find_prime_buggy():\n    i = 2\n    while True:\n        isprime = 1 == 1\n        j = 2\n        while not (j >= i):\n            if (i % j == 0) == True:\n                isprime = 0 != 1\n            j = j + 1\n        break\n        if isprime:\n            return i\n        i = i + 1"
    },
    {
      "ex5": "def find_prime_buggy():\n    prime_candidate = 2\n    while True:\n        found_prime = True\n        check_divisor = 2\n        while check_divisor < prime_candidate:\n            if (prime_candidate % check_divisor) == 0:\n                found_prime = not True\n            check_divisor += 1\n        break\n        if found_prime == 1:\n            return prime_candidate\n        prime_candidate += 1"
    }
  ]
}
Succefully
Problem:  Identify a prime number with the help of break
Code:  def find_prime_buggy():
    candidate = 2
    while True:
        prime_flag = not False
        test_div = 2
        while test_div != candidate:
            if not (candidate % test_div):
                prime_flag = False
            test_div = test_div + 1
        break
        if prime_flag == True:
            return candidate
        candidate = candidate + 1
Problem:  Identify a prime number with the help of break
Code:  def find_prime_buggy():
    n = 2
    while 1:
        flag = True
        d = 2
        while d < n:
            if n % d is 0:
                flag = False
            d += 1
        break
        if flag:
            return n
        n += 1
Problem:  Identify a prime number with the help of break
Code:  def find_prime_buggy():
    x = 2
    while True:
        valid = True
        y = 2
        while y < x:
            if 0 == x % y:
                valid = False
            y += 1
        break
        if valid is True:
            return x
        x += 1
Problem:  Identify a prime number with the help of break
Code:  def find_prime_buggy():
    i = 2
    while True:
        isprime = 1 == 1
        j = 2
        while not (j >= i):
            if (i % j == 0) == True:
                isprime = 0 != 1
            j = j + 1
        break
        if isprime:
            return i
        i = i + 1
Problem:  Identify a prime number with the help of break
Code:  def find_prime_buggy():
    prime_candidate = 2
    while True:
        found_prime = True
        check_divisor = 2
        while check_divisor < prime_candidate:
            if (prime_candidate % check_divisor) == 0:
                found_prime = not True
            check_divisor += 1
        break
        if found_prime == 1:
            return prime_candidate
        prime_candidate += 1
Problem:  use break to locate a prime number
Code:  def find_prime_buggy():
    candidate = 2
    while True:
        prime_flag = not False
        test_div = 2
        while test_div != candidate:
            if not (candidate % test_div):
                prime_flag = False
            test_div = test_div + 1
        break
        if prime_flag == True:
            return candidate
        candidate = candidate + 1
Problem:  use break to locate a prime number
Code:  def find_prime_buggy():
    n = 2
    while 1:
        flag = True
        d = 2
        while d < n:
            if n % d is 0:
                flag = False
            d += 1
        break
        if flag:
            return n
        n += 1
Problem:  use break to locate a prime number
Code:  def find_prime_buggy():

In [ ]:
df_augmented

,Problem Description,Python Code,Source,Description Error,Error Label,Problem Augmented,Description Augmented
0,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,Determine the number of even numbers less than...,def count_evens_buggy(n):\n count = 0\n ...
1,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,Determine the number of even numbers less than...,def count_evens_buggy(n):\n i = 0\n tota...
2,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,Determine the number of even numbers less than...,def count_evens_buggy(n):\n i = 0\n c = ...
3,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,Determine the number of even numbers less than...,def count_evens_buggy(n):\n count = 0\n ...
4,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,Determine the number of even numbers less than...,def count_evens_buggy(n):\n idx = 0\n re...
...,...,...,...,...,...,...,...
630,Count numbers divisible by 3,def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n i = 0\n cou...
631,Count numbers divisible by 3,def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n i = 0\n cou...
632,Count numbers divisible by 3,def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...
633,Count numbers divisible by 3,def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...
634,Count numbers divisible by 3,def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...

In [ ]:
df_augmented.to_csv('/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/Tuning/BestModels/ExAuCorrectionAug.csv',
                  index=False)

In [ ]:
df_augmented=pd.read_csv('/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/Tuning/BestModels/ExAuCorrectionAug.csv')

In [ ]:
df_augmented

,Problem Description,Python Code,Source,Description Error,Error Label,Problem Augmented,Description Augmented
0,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,Determine the number of even numbers less than...,def count_evens_buggy(n):\n count = 0\n ...
1,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,Determine the number of even numbers less than...,def count_evens_buggy(n):\n i = 0\n tota...
2,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,Determine the number of even numbers less than...,def count_evens_buggy(n):\n i = 0\n c = ...
3,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,Determine the number of even numbers less than...,def count_evens_buggy(n):\n count = 0\n ...
4,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,Determine the number of even numbers less than...,def count_evens_buggy(n):\n idx = 0\n re...
...,...,...,...,...,...,...,...
630,Count numbers divisible by 3,def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n i = 0\n cou...
631,Count numbers divisible by 3,def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n i = 0\n cou...
632,Count numbers divisible by 3,def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...
633,Count numbers divisible by 3,def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...
634,Count numbers divisible by 3,def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...