In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.56.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.8.3)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import re
import shutil
import string
from sklearn.metrics import classification_report
import tensorflow as tf
from keras.models import Model
from tensorflow.keras import layers
from tensorflow.keras import losses
from tensorflow.keras.optimizers import Adam
from keras.callbacks import EarlyStopping,ModelCheckpoint
from tensorflow.keras.layers import Dense, Input, Dropout, Bidirectional, LSTM, Embedding, BatchNormalization,  Reshape, Conv2D, MaxPool2D, concatenate, Flatten, Activation
import torch
import numpy as np
from transformers import BertTokenizer, BertModel,RobertaTokenizer, RobertaModel
import ast

In [ ]:
# Verificar si la GPU está disponible
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
archivo_3 = '/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/Tuning/BestModels/ExternData.csv'
train_full = pd.read_csv(archivo_3)

# AST spliter D. Gries form

In [ ]:
class WhileLoopFinder(ast.NodeVisitor):
    def __init__(self, source_code):
        self.source_code = source_code.splitlines()
        self.functions_with_while = []
        self.current_function = None

    def visit_FunctionDef(self, node):
        original_current_function = self.current_function
        self.current_function = {
            "function_name": node.name,
            "has_while_loop": False,
            "pre_while_code_lines": [],
            "while_loops": []
        }

        function_start_line = node.lineno - 1
        function_end_line = (node.end_lineno if hasattr(node, 'end_lineno') else len(self.source_code))
        function_lines = self.source_code[function_start_line:function_end_line]

        found_while = False
        for stmt in node.body:
            if isinstance(stmt, ast.While):
                self.current_function["has_while_loop"] = True
                found_while = True
                try:
                    while_condition = ast.unparse(stmt.test).strip()
                    print("OK condition")
                except AttributeError:
                    print("Error al obtener la condición del while")
                try:
                    while_body_code = ast.unparse(ast.Module(body=stmt.body, type_ignores=[])).strip()
                    print("Ok body")
                except AttributeError:
                    print("Error al obtener el código del cuerpo del while")

                self.current_function["while_loops"].append({
                    "condition": while_condition,
                    "body_code": while_body_code
                })
            elif not found_while:
                start_line = stmt.lineno - 1
                end_line = (stmt.end_lineno if hasattr(stmt, 'end_lineno') else stmt.lineno)
                self.current_function["pre_while_code_lines"].extend(self.source_code[start_line:end_line])
            self.generic_visit(stmt)

        if self.current_function["has_while_loop"]:
            last_while_end_line = None
            if self.current_function["while_loops"]:
                last_while_node = next((node for node in reversed(node.body) if isinstance(node, ast.While)), None)
                if last_while_node and hasattr(last_while_node, 'end_lineno'):
                    last_while_end_line = last_while_node.end_lineno
            post_while_code_lines = []
            if last_while_end_line:
                function_indent = len(self.source_code[node.lineno - 1]) - len(self.source_code[node.lineno - 1].lstrip())
                for line in self.source_code[last_while_end_line:function_end_line]:
                    if line.startswith(self.source_code[node.lineno - 1][:function_indent] + "    "):
                        post_while_code_lines.append(line[function_indent + 4:])
                    else:
                        post_while_code_lines.append(line[function_indent:])
            self.current_function["post_while_code_lines"] = "\n".join(post_while_code_lines).strip()
            self.current_function["pre_while_code_lines"] = "\n".join(self.current_function["pre_while_code_lines"]).strip()
            self.functions_with_while.append(self.current_function)

        self.current_function = original_current_function

In [ ]:
class WhileLoopFinder(ast.NodeVisitor):
    def __init__(self, source_code):
        self.source_code = source_code.splitlines()
        self.functions_with_while = []
        self.current_function = None

    def visit_FunctionDef(self, node):
        original_current_function = self.current_function
        self.current_function = {
            "function_name": node.name,
            "has_while_loop": False,
            "pre_while_code_lines": [],
            "while_loops": []
        }

        function_start_line = node.lineno - 1
        function_end_line = (node.end_lineno if hasattr(node, 'end_lineno') else len(self.source_code))
        function_lines = self.source_code[function_start_line:function_end_line]

        found_while = False
        for stmt in node.body:
            if isinstance(stmt, ast.While):
                self.current_function["has_while_loop"] = True
                found_while = True
                try:
                    while_condition = ast.unparse(stmt.test).strip()
                    print("OK condition")
                except AttributeError:
                    print("Error al obtener la condición del while")
                try:
                    while_body_code = ast.unparse(ast.Module(body=stmt.body, type_ignores=[])).strip()
                    print("Ok body")
                except AttributeError:
                    print("Error al obtener el código del cuerpo del while")

                self.current_function["while_loops"].append({
                    "condition": while_condition,
                    "body_code": while_body_code
                })
            elif not found_while:
                start_line = stmt.lineno - 1
                end_line = (stmt.end_lineno if hasattr(stmt, 'end_lineno') else stmt.lineno)
                self.current_function["pre_while_code_lines"].extend(self.source_code[start_line:end_line])
            self.generic_visit(stmt)

        if self.current_function["has_while_loop"]:
            last_while_end_line = None
            if self.current_function["while_loops"]:
                last_while_node = next((node for node in reversed(node.body) if isinstance(node, ast.While)), None)
                if last_while_node and hasattr(last_while_node, 'end_lineno'):
                    last_while_end_line = last_while_node.end_lineno
            post_while_code_lines = []
            if last_while_end_line:
                function_indent = len(self.source_code[node.lineno - 1]) - len(self.source_code[node.lineno - 1].lstrip())
                for line in self.source_code[last_while_end_line:function_end_line]:
                    if line.startswith(self.source_code[node.lineno - 1][:function_indent] + "    "):
                        post_while_code_lines.append(line[function_indent + 4:])
                    else:
                        post_while_code_lines.append(line[function_indent:])
            self.current_function["post_while_code_lines"] = "\n".join(post_while_code_lines).strip()
            self.current_function["pre_while_code_lines"] = "\n".join(self.current_function["pre_while_code_lines"]).strip()
            self.functions_with_while.append(self.current_function)

        self.current_function = original_current_function

def DGries_states(solution):
  try:
    # Unescape newline characters
    solution = solution.replace('\\n', '\n')
    # Crear el AST
    tree = ast.parse(solution)
    # Recorrer el AST con nuestro visitante
    finder = WhileLoopFinder(solution)
    finder.visit(tree)
    for func_info in finder.functions_with_while:
      initial_state=func_info["pre_while_code_lines"] if func_info["pre_while_code_lines"] else False
      end_state=""
      transformation_state=""
      for j, wl in enumerate(func_info["while_loops"]):
          end_state=wl["condition"]
          transformation_state=wl["body_code"]

      if not initial_state:
        initial_state=transformation_state
      return initial_state,transformation_state,end_state
  except Exception as error:
    raise error
    #return "Exception:"+str(error),"Exception:"+str(error),"Exception:"+str(error)

In [ ]:
train_full.dropna(inplace=True)

In [ ]:
train_full[["Estado incial","Transformación de estado","Estado final"]]=train_full['Python Code'].apply(DGries_states).apply(pd.Series)
display(train_full.head())

OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body

,Problem Description,Python Code,Error Label,Source,Estado incial,Transformación de estado,Estado final
0,Count how many even numbers are up to n. Logic...,def count_evens_buggy(n):\n i = 0\n coun...,2,Inspired by CodeChef Learn Python (While Loop)...,i = 0\n count = 0,if i % 2 == 0:\n count += 1,i <= n
1,Sum numbers from 1 to n. Error: i is incorrect...,def sum_to_n_buggy(n):\n total = 0\n i =...,2,Based on typical mistakes in Codeforces common...,total = 0\n i = 1,total += i\ni = i + 0,i <= n
2,Prompt user for numbers until 0 is entered. Er...,def input_until_zero_buggy():\n num = int(i...,2,Common error from GeeksforGeeks Python while l...,num = int(input('Enter number (0 to exit): ')),"print('Number:', num)",num != 0
3,Find first multiple of 7 greater than n. Error...,def first_multiple_7_buggy(n):\n i = n + 1\...,2,Typical error in CodeNet beginner loop problems,i = n + 1,pass,i % 7 != 0
4,Calculate factorial of n. Logical error: decre...,def factorial_buggy(n):\n result = 1\n w...,2,Inspired by classic factorial exercises,result = 1,result *= n\nn -= 2,n > 1

In [ ]:
# Assuming the error occurs on the first row, inspect the 'Python Code' column
print(train_full['Python Code'].iloc[0])

def count_evens_buggy(n):\n    i = 0\n    count = 0\n    while i <= n:\n        if i % 2 == 0:\n            count += 1\n        # missing i += 1\n    return count

# Load Dataset

In [ ]:
train_full

,Problem Description,Python Code,Error Label,Source,Estado incial,Transformación de estado,Estado final
0,Count how many even numbers are up to n. Logic...,def count_evens_buggy(n):\n i = 0\n coun...,2,Inspired by CodeChef Learn Python (While Loop)...,i = 0\n count = 0,if i % 2 == 0:\n count += 1,i <= n
1,Sum numbers from 1 to n. Error: i is incorrect...,def sum_to_n_buggy(n):\n total = 0\n i =...,2,Based on typical mistakes in Codeforces common...,total = 0\n i = 1,total += i\ni = i + 0,i <= n
2,Prompt user for numbers until 0 is entered. Er...,def input_until_zero_buggy():\n num = int(i...,2,Common error from GeeksforGeeks Python while l...,num = int(input('Enter number (0 to exit): ')),"print('Number:', num)",num != 0
3,Find first multiple of 7 greater than n. Error...,def first_multiple_7_buggy(n):\n i = n + 1\...,2,Typical error in CodeNet beginner loop problems,i = n + 1,pass,i % 7 != 0
4,Calculate factorial of n. Logical error: decre...,def factorial_buggy(n):\n result = 1\n w...,2,Inspired by classic factorial exercises,result = 1,result *= n\nn -= 2,n > 1
5,Count digits in a positive integer n. Error: n...,def count_digits_buggy(n):\n count = 0\n ...,2,Inspired by digit counting problems in Codefor...,count = 0,n % 10\ncount += 1,n > 0
6,Sum all even numbers up to n. Error: loop cond...,def sum_evens_buggy(n):\n total = 0\n i ...,1,"CodeChef/Codeforces summing problems, conditio...",total = 0\n i = 2,total += i\ni += 2,i < n
7,Find a prime number using break. Error: break ...,def find_prime_buggy():\n num = 2\n whil...,2,Inspired by break/continue loop errors from Py...,num = 2,is_prime = True\ndivisor = 2\nwhile divisor < ...,True
8,Print cubes of numbers from 1 to n. Error: i n...,def print_cubes_buggy(n):\n while i <= n:\n...,0,"Common initialization error, based on CodeNet ...",print(i ** 3)\ni += 1,print(i ** 3)\ni += 1,i <= n
9,Prompt for password until correct. Error: pass...,def prompt_password_buggy():\n password = i...,2,Typical validation loop error from Python begi...,password = input('Enter password: '),print('Incorrect'),password != 'secret'
10,"Print numbers from 1 to n, but condition exclu...",def print_numbers_buggy(n):\n i = 1\n wh...,1,Common inclusive/exclusive error in loops (Cod...,i = 1,print(i)\ni += 1,i < n
11,Divide a number by 2 repeatedly until it's les...,def divide_repeatedly_buggy(n):\n while n >...,2,Inspired by CodeNet loop problems involving di...,print(n)\nn = n // 2,print(n)\nn = n // 2,n >= 1
12,Sum all digits of n. Error: missing update of n.,def sum_digits_buggy(n):\n total = 0\n w...,2,"Classic digit-processing error, Python/Codeforces",total = 0,total += n % 10,n > 0
13,Count how many times 5 can be subtracted from ...,def count_subtract_5_buggy(n):\n count = 0\...,2,Common mistake in decrement loops (CodeNet/Cod...,count = 0,count += 1,n >= 5
14,Calculate power using while loop. Error: missi...,"def power_buggy(base, exp):\n result = 1\n ...",2,Power calculation errors in Codeforces/Python ...,result = 1\n i = 0,result *= base,i < exp
15,Check if number is perfect. Error in sum calcu...,def is_perfect_buggy(n):\n sum_div = 0\n ...,2,"Perfect number mistakes, classic math loops",sum_div = 0\n divisor = 1,if n % divisor == 0:\n sum_div = divisor,divisor < n
16,Convert decimal to binary. Error: n not update...,def decimal_to_binary_buggy(n):\n res = ''\...,2,"Typical binary conversion loop, Codeforces/Cod...",res = '',res = str(n % 2) + res,n > 0
17,Print items in list until negative is found. E...,def print_until_negative_buggy(lst):\n i = ...,2,Inspired by control-flow misplacement from Pyt...,i = 0,print(lst[i])\nbreak\nif lst[i] < 0:\n brea...,i < len(lst)
18,Count multiples of 3 up to n. Error: count nev...,def count_mult_3_buggy(n):\n i = 1\n cou...,2,"Loops with missed accumulation, typical in beg...",i = 1\n count = 0,if i % 3 == 0:\n pass\ni += 1,i <= n
19,Print odd numbers up to n. Error: i is increme...,def print_odds_buggy(n):\n i = 1\n while...,2,"Increment logic error, Codeforces/CodeChef",i = 1,print(i)\ni += 2\ni += 1,i <= n
20,Sum the first n natural numbers. Error: loop c...,def sum_n_buggy(n):\n i = 1\n total = 0\...,1,"Classic off-by-one loop error, inspired by bas...",i = 1\n total = 0,total += i\ni += 1,i < n
21,Sum odd numbers up to n. Error: i increment in...,def sum_odds_buggy(n):\n total = 0\n i =...,2,"Odd number sum, increment bug, beginner mistakes",total = 0\n i = 1,if i % 2 != 0:\n total += i\ni = i + 1 - 1,i <= n
22,Count primes up to n. Error: loop condition ex...,def count_primes_buggy(n):\n count = 0\n ...,1,Classic loop and condition error in prime coun...,count = 0\n i = 2,if is_prime(i):\n count += 1\ni += 1,i < n
23,Read and sum numbers until a negative is enter...,def sum_until_negative_buggy():\n total = 0...,2,"Missing input update bug, shown in tutorials (...",total = 0\n num = int(input('Enter number (...,total += num,num >= 0
24,Find LCM of two numbers. Error: missing increm...,"def lcm_buggy(a, b):\n num = max(a, b)\n ...",2,"LCM calculation, common loop bug (CodeNet/Code...","num = max(a, b)",if num % a == 0 and num % b == 0:\n return num,True
25,Print Fibonacci sequence up to n terms. Error:...,"def fibonacci_buggy(n):\n a, b = 0, 1\n ...",2,"Sequence and assignment bug, inspired by class...","a, b = 0, 1\n i = 0",print(a)\nb = a + b\na = b\ni += 1,i < n
26,Count multiples of 5 up to n. Error: i not upd...,def count_mult_5_buggy(n):\n i = 1\n cou...,2,"Missing i update, common beginner error, CodeC...",i = 1\n count = 0,if i % 5 == 0:\n count += 1,i <= n
27,Find GCD of two numbers using Euclid algorithm...,"def gcd_buggy(a, b):\n while a != b:\n ...",1,"Euclid's algorithm off-by-one/condition bug, C...",if a > b:\n a -= b\nelse:\n b -= a,if a > b:\n a -= b\nelse:\n b -= a,a != b
28,Prompt user for positive numbers until 5 are e...,def count_positives_buggy():\n count = 0\n ...,2,"Input accumulation/counting error, basic progr...",count = 0,num = int(input('Enter positive number: '))\ni...,count < 5
29,Sum multiples of 4 between 1 and n. Error: sum...,def sum_mult_4_buggy(n):\n i = 1\n while...,2,"Sum variable scope bug, inspired by sum/accumu...",i = 1,sum = 0\nif i % 4 == 0:\n sum += i\ni += 1,i <= n
30,"Print the factorial of n, but n is not initial...",def buggy_factorial():\n while n > 0:\n ...,0,Initialization errors are a classic mistake (C...,print(n)\nn -= 1,print(n)\nn -= 1,n > 0
31,Reverse a list but forget to initialize the in...,def buggy_reverse(lst):\n # missing i = len...,3,"Initialization and condition errors, common in...",print(lst[j])\nj -= 1,print(lst[j])\nj -= 1,j >= 0
32,"Print numbers from a to b, missing both variab...",def buggy_print_range(b):\n # missing a = 1...,4,Initialization and update errors frequently se...,a = 1\nprint(a)\na += 1,a = 1\nprint(a)\na += 1,a <= b
33,"Sum even numbers in a list, with an off-by-one...",def buggy_sum_evens(lst):\n i = 0\n sum_...,5,"Condition and update errors, drawn from typica...",i = 0\n sum_evens = 0,if lst[i] % 2 == 0:\n pass\ni += 1,i <= len(lst)
34,"Count numbers divisible by 3, fails to initial...",def buggy_count_mult_3(n):\n while i < n: ...,6,"Simultaneous initialization, condition, and bo...",count = 0\nif i % 3 == 0:\n pass\ni += 1,count = 0\nif i % 3 == 0:\n pass\ni += 1,i < n

In [ ]:
train_full[["Estado incial","Transformación de estado","Estado final"]]=train_full['Python Code'].apply(DGries_states).apply(pd.Series)

OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body

In [ ]:
train_full.dropna(inplace=True)

In [ ]:
np.unique(train_full['Error Label'])

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
train_full.head()

,Problem Description,Python Code,Error Label,Source,Estado incial,Transformación de estado,Estado final
0,Count how many even numbers are up to n. Logic...,def count_evens_buggy(n):\n i = 0\n coun...,2,Inspired by CodeChef Learn Python (While Loop)...,i = 0\n count = 0,if i % 2 == 0:\n count += 1,i <= n
1,Sum numbers from 1 to n. Error: i is incorrect...,def sum_to_n_buggy(n):\n total = 0\n i =...,2,Based on typical mistakes in Codeforces common...,total = 0\n i = 1,total += i\ni = i + 0,i <= n
2,Prompt user for numbers until 0 is entered. Er...,def input_until_zero_buggy():\n num = int(i...,2,Common error from GeeksforGeeks Python while l...,num = int(input('Enter number (0 to exit): ')),"print('Number:', num)",num != 0
3,Find first multiple of 7 greater than n. Error...,def first_multiple_7_buggy(n):\n i = n + 1\...,2,Typical error in CodeNet beginner loop problems,i = n + 1,pass,i % 7 != 0
4,Calculate factorial of n. Logical error: decre...,def factorial_buggy(n):\n result = 1\n w...,2,Inspired by classic factorial exercises,result = 1,result *= n\nn -= 2,n > 1

In [ ]:
encoder=EncodeTextSource()
encoder.start_tokenizer()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/498 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

In [ ]:
%%time
problem=train_full['Problem Description'].apply(encoder.tokenize_and_generate_embeddings_descriptions).to_numpy()
code=train_full['Python Code'].apply(encoder.tokenize_and_generate_embeddings_codes).to_numpy()
startstate = train_full['Estado incial'].apply(encoder.tokenize_and_generate_embeddings_codes).to_numpy()
finalstate = train_full['Estado final'].apply(encoder.tokenize_and_generate_embeddings_codes).to_numpy()
transstate = train_full['Transformación de estado'].apply(encoder.tokenize_and_generate_embeddings_codes).to_numpy()

CPU times: user 3.9 s, sys: 1.73 s, total: 5.64 s
Wall time: 8.62 s

In [ ]:
problem.shape,code.shape,startstate.shape,finalstate.shape,transstate.shape

((35,), (35,), (35,), (35,), (35,))

In [ ]:
print(startstate.shape)
print(startstate[30].shape)

(35,)
(1, 10, 768)

In [ ]:
Xp=np.array([sentence[0].mean(axis=0) for sentence in problem])
Xcode=np.array([sentence[0].mean(axis=0) for sentence in code])
Xs=np.array([sentence[0].mean(axis=0) for sentence in startstate])
Xf=np.array([sentence[0].mean(axis=0) for sentence in finalstate])
Xt=np.array([sentence[0].mean(axis=0) for sentence in transstate])
Xp.shape,Xs.shape,Xf.shape,Xt.shape

((35, 768), (35, 768), (35, 768), (35, 768))

In [ ]:
y=train_full['Error Label']
y=y.to_numpy()
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
from sklearn.metrics import matthews_corrcoef, precision_recall_curve, auc
from sklearn.preprocessing import label_binarize
import numpy as np

def calculate_mcc_multiclass(y_true, y_pred_probs):
    y_pred_labels = np.argmax(y_pred_probs, axis=1)
    # Convertir etiquetas verdaderas one-hot a etiquetas enteras si es necesario
    #y_true_labels = np.argmax(y_true, axis=1) if y_true.ndim > 1 else y_true
    return matthews_corrcoef(y_true, y_pred_labels)

def calculate_auc_pr_multiclass(y_true, y_pred_probs, average='macro'):
    n_classes = y_pred_probs.shape[1]
    #y_true_labels = np.argmax(y_true, axis=1) if y_true.ndim > 1 else y_true
    y_true_bin = label_binarize(y_true, classes=range(n_classes))

    auc_pr_list = []
    for i in range(n_classes):
        precision, recall, _ = precision_recall_curve(y_true_bin[:, i], y_pred_probs[:, i])
        auc_pr_list.append(auc(recall, precision))

    if average == 'macro':
        return np.mean(auc_pr_list)
    elif average == 'weighted':
        class_counts = y_true_bin.sum(axis=0)
        return np.average(auc_pr_list, weights=class_counts)
    else:
        return auc_pr_list

In [ ]:
from tensorflow import keras
from time import time
accuracies_predict=[]
loss_predict=[]
times_predict=[]
mccs_predict=[]
aucpr_predict=[]
models_names=["problemall","problem_gries","code_gries","gries","problem_code","code"]


Model_Xtest=[Xp,Xcode,Xs,Xt,Xf]
for i,my_model in enumerate(models_names):
  model=keras.models.load_model('/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/ResultsBERT/ablations_finall_{0}.keras'.format(my_model))
  if(i==1):
    Model_Xtest=[Xp,Xs,Xt,Xf]
  if(i==2):
    Model_Xtest=[Xcode,Xs,Xt,Xf]
  if(i==3):
    Model_Xtest=[Xs,Xt,Xf]
  if(i==4):
    Model_Xtest=[Xp,Xcode]
  if(i==5):
    Model_Xtest=[Xcode]


  evaluate=model.evaluate(Model_Xtest,y)

  t1=time()
  y_pred=model.predict(Model_Xtest)
  t2=time()
  mcc=calculate_mcc_multiclass(y, y_pred)
  auc_pr=calculate_auc_pr_multiclass(y, y_pred)

  times_predict.append(t2-t1)
  accuracies_predict.append(evaluate[1])
  loss_predict.append(evaluate[0])
  mccs_predict.append(mcc)
  aucpr_predict.append(auc_pr)


  accuracy=evaluate[1]
  loss=evaluate[0]

  print("accuracy",accuracy)
  print("loss",loss)
  print("mcc",mcc)
  print("auc_pr",auc_pr)
  print("time predict",t2-t1)

2/2 ━━━━━━━━━━━━━━━━━━━━ 5s 1s/step - accuracy: 0.2946 - loss: 2.8522
2/2 ━━━━━━━━━━━━━━━━━━━━ 5s 3s/step
accuracy 0.2857142984867096
loss 2.9015676975250244
mcc 0.06268035106150013
auc_pr 0.2069570819281064
time predict 4.781700372695923

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(

2/2 ━━━━━━━━━━━━━━━━━━━━ 4s 875ms/step - accuracy: 0.2652 - loss: 2.7634
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 1s/step
accuracy 0.2571428716182709
loss 2.7938945293426514
mcc 0.015166081788042879
auc_pr 0.20332598676705735
time predict 2.5224905014038086

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(

2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 514ms/step - accuracy: 0.2946 - loss: 2.5657

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7fdd5f695e40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 709ms/step

WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7fdd5f695e40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 725ms/step

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(

accuracy 0.2857142984867096
loss 2.6152827739715576
mcc 0.09691098082930297
auc_pr 0.2196274521897154
time predict 1.4772028923034668

In [ ]:
model=keras.models.load_model('/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/ResultsBERT/ablations_finall_{0}.keras'.format("problemall"))

In [ ]:
Model_Xtest=[Xp,Xcode,Xs,Xt,Xf]
y_pred=model.predict(Model_Xtest)

2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 1s/step

In [ ]:
train_full["y_pred"]=y_pred.argmax(axis=1)

In [ ]:
train_full.to_csv('/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/ResultsBERT/test_best_modelbert.csv')

In [ ]:
import pandas as pd
df_final=pd.read_csv('/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/ResultsBERT/test_best_modelbert.csv')

In [ ]:
df_final

,Unnamed: 0,Problem Description,Python Code,Error Label,Source,Estado incial,Transformación de estado,Estado final,y_pred
0,0,Count how many even numbers are up to n. Logic...,def count_evens_buggy(n):\n i = 0\n coun...,2,Inspired by CodeChef Learn Python (While Loop)...,i = 0\n count = 0,if i % 2 == 0:\n count += 1,i <= n,0
1,1,Sum numbers from 1 to n. Error: i is incorrect...,def sum_to_n_buggy(n):\n total = 0\n i =...,2,Based on typical mistakes in Codeforces common...,total = 0\n i = 1,total += i\ni = i + 0,i <= n,5
2,2,Prompt user for numbers until 0 is entered. Er...,def input_until_zero_buggy():\n num = int(i...,2,Common error from GeeksforGeeks Python while l...,num = int(input('Enter number (0 to exit): ')),"print('Number:', num)",num != 0,0
3,3,Find first multiple of 7 greater than n. Error...,def first_multiple_7_buggy(n):\n i = n + 1\...,2,Typical error in CodeNet beginner loop problems,i = n + 1,pass,i % 7 != 0,2
4,4,Calculate factorial of n. Logical error: decre...,def factorial_buggy(n):\n result = 1\n w...,2,Inspired by classic factorial exercises,result = 1,result *= n\nn -= 2,n > 1,2
5,5,Count digits in a positive integer n. Error: n...,def count_digits_buggy(n):\n count = 0\n ...,2,Inspired by digit counting problems in Codefor...,count = 0,n % 10\ncount += 1,n > 0,2
6,6,Sum all even numbers up to n. Error: loop cond...,def sum_evens_buggy(n):\n total = 0\n i ...,1,"CodeChef/Codeforces summing problems, conditio...",total = 0\n i = 2,total += i\ni += 2,i < n,0
7,7,Find a prime number using break. Error: break ...,def find_prime_buggy():\n num = 2\n whil...,2,Inspired by break/continue loop errors from Py...,num = 2,is_prime = True\ndivisor = 2\nwhile divisor < ...,True,0
8,8,Print cubes of numbers from 1 to n. Error: i n...,def print_cubes_buggy(n):\n while i <= n:\n...,0,"Common initialization error, based on CodeNet ...",print(i ** 3)\ni += 1,print(i ** 3)\ni += 1,i <= n,0
9,9,Prompt for password until correct. Error: pass...,def prompt_password_buggy():\n password = i...,2,Typical validation loop error from Python begi...,password = input('Enter password: '),print('Incorrect'),password != 'secret',0
10,10,"Print numbers from 1 to n, but condition exclu...",def print_numbers_buggy(n):\n i = 1\n wh...,1,Common inclusive/exclusive error in loops (Cod...,i = 1,print(i)\ni += 1,i < n,0
11,11,Divide a number by 2 repeatedly until it's les...,def divide_repeatedly_buggy(n):\n while n >...,2,Inspired by CodeNet loop problems involving di...,print(n)\nn = n // 2,print(n)\nn = n // 2,n >= 1,0
12,12,Sum all digits of n. Error: missing update of n.,def sum_digits_buggy(n):\n total = 0\n w...,2,"Classic digit-processing error, Python/Codeforces",total = 0,total += n % 10,n > 0,0
13,13,Count how many times 5 can be subtracted from ...,def count_subtract_5_buggy(n):\n count = 0\...,2,Common mistake in decrement loops (CodeNet/Cod...,count = 0,count += 1,n >= 5,2
14,14,Calculate power using while loop. Error: missi...,"def power_buggy(base, exp):\n result = 1\n ...",2,Power calculation errors in Codeforces/Python ...,result = 1\n i = 0,result *= base,i < exp,1
15,15,Check if number is perfect. Error in sum calcu...,def is_perfect_buggy(n):\n sum_div = 0\n ...,2,"Perfect number mistakes, classic math loops",sum_div = 0\n divisor = 1,if n % divisor == 0:\n sum_div = divisor,divisor < n,2
16,16,Convert decimal to binary. Error: n not update...,def decimal_to_binary_buggy(n):\n res = ''\...,2,"Typical binary conversion loop, Codeforces/Cod...",res = '',res = str(n % 2) + res,n > 0,0
17,17,Print items in list until negative is found. E...,def print_until_negative_buggy(lst):\n i = ...,2,Inspired by control-flow misplacement from Pyt...,i = 0,print(lst[i])\nbreak\nif lst[i] < 0:\n brea...,i < len(lst),1
18,18,Count multiples of 3 up to n. Error: count nev...,def count_mult_3_buggy(n):\n i = 1\n cou...,2,"Loops with missed accumulation, typical in beg...",i = 1\n count = 0,if i % 3 == 0:\n pass\ni += 1,i <= n,0
19,19,Print odd numbers up to n. Error: i is increme...,def print_odds_buggy(n):\n i = 1\n while...,2,"Increment logic error, Codeforces/CodeChef",i = 1,print(i)\ni += 2\ni += 1,i <= n,0
20,20,Sum the first n natural numbers. Error: loop c...,def sum_n_buggy(n):\n i = 1\n total = 0\...,1,"Classic off-by-one loop error, inspired by bas...",i = 1\n total = 0,total += i\ni += 1,i < n,1
21,21,Sum odd numbers up to n. Error: i increment in...,def sum_odds_buggy(n):\n total = 0\n i =...,2,"Odd number sum, increment bug, beginner mistakes",total = 0\n i = 1,if i % 2 != 0:\n total += i\ni = i + 1 - 1,i <= n,2
22,22,Count primes up to n. Error: loop condition ex...,def count_primes_buggy(n):\n count = 0\n ...,1,Classic loop and condition error in prime coun...,count = 0\n i = 2,if is_prime(i):\n count += 1\ni += 1,i < n,0
23,23,Read and sum numbers until a negative is enter...,def sum_until_negative_buggy():\n total = 0...,2,"Missing input update bug, shown in tutorials (...",total = 0\n num = int(input('Enter number (...,total += num,num >= 0,1
24,24,Find LCM of two numbers. Error: missing increm...,"def lcm_buggy(a, b):\n num = max(a, b)\n ...",2,"LCM calculation, common loop bug (CodeNet/Code...","num = max(a, b)",if num % a == 0 and num % b == 0:\n return num,True,2
25,25,Print Fibonacci sequence up to n terms. Error:...,"def fibonacci_buggy(n):\n a, b = 0, 1\n ...",2,"Sequence and assignment bug, inspired by class...","a, b = 0, 1\n i = 0",print(a)\nb = a + b\na = b\ni += 1,i < n,0
26,26,Count multiples of 5 up to n. Error: i not upd...,def count_mult_5_buggy(n):\n i = 1\n cou...,2,"Missing i update, common beginner error, CodeC...",i = 1\n count = 0,if i % 5 == 0:\n count += 1,i <= n,0
27,27,Find GCD of two numbers using Euclid algorithm...,"def gcd_buggy(a, b):\n while a != b:\n ...",1,"Euclid's algorithm off-by-one/condition bug, C...",if a > b:\n a -= b\nelse:\n b -= a,if a > b:\n a -= b\nelse:\n b -= a,a != b,2
28,28,Prompt user for positive numbers until 5 are e...,def count_positives_buggy():\n count = 0\n ...,2,"Input accumulation/counting error, basic progr...",count = 0,num = int(input('Enter positive number: '))\ni...,count < 5,1
29,29,Sum multiples of 4 between 1 and n. Error: sum...,def sum_mult_4_buggy(n):\n i = 1\n while...,2,"Sum variable scope bug, inspired by sum/accumu...",i = 1,sum = 0\nif i % 4 == 0:\n sum += i\ni += 1,i <= n,0
30,30,"Print the factorial of n, but n is not initial...",def buggy_factorial():\n while n > 0:\n ...,0,Initialization errors are a classic mistake (C...,print(n)\nn -= 1,print(n)\nn -= 1,n > 0,0
31,31,Reverse a list but forget to initialize the in...,def buggy_reverse(lst):\n # missing i = len...,3,"Initialization and condition errors, common in...",print(lst[j])\nj -= 1,print(lst[j])\nj -= 1,j >= 0,0
32,32,"Print numbers from a to b, missing both variab...",def buggy_print_range(b):\n # missing a = 1...,4,Initialization and update errors frequently se...,a = 1\nprint(a)\na += 1,a = 1\nprint(a)\na += 1,a <= b,2
33,33,"Sum even numbers in a list, with an off-by-one...",def buggy_sum_evens(lst):\n i = 0\n sum_...,5,"Condition and update errors, drawn from typica...",i = 0\n sum_evens = 0,if lst[i] % 2 == 0:\n pass\ni += 1,i <= len(lst),1
34,34,"Count numbers divisible by 3, fails to initial...",def buggy_count_mult_3(n):\n while i < n: ...,6,"Simultaneous initialization, condition, and bo...",count = 0\nif i % 3 == 0:\n pass\ni += 1,count = 0\nif i % 3 == 0:\n pass\ni += 1,i < n,2

In [ ]:
model.fi

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 23s 23s/step - accuracy: 0.8857 - loss: 0.6587 - learning_rate: 0.0010
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.8857 - loss: 0.5464 - learning_rate: 0.0010
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.8857 - loss: 0.3989 - learning_rate: 0.0010
Epoch 4/1000

/usr/local/lib/python3.12/dist-packages/keras/src/callbacks/early_stopping.py:153: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: accuracy,loss
  current = self.get_monitor_value(logs)
/usr/local/lib/python3.12/dist-packages/keras/src/callbacks/callback_list.py:145: UserWarning: Learning rate reduction is conditioned on metric `val_loss` which is not available. Available metrics are: accuracy,loss,learning_rate.
  callback.on_epoch_end(epoch, logs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9143 - loss: 0.3124 - learning_rate: 0.0010
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.9714 - loss: 0.2243 - learning_rate: 0.0010
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.9714 - loss: 0.1787 - learning_rate: 0.0010
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 1.0000 - loss: 0.1025 - learning_rate: 0.0010
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 1.0000 - loss: 0.1165 - learning_rate: 0.0010
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 1.0000 - loss: 0.0976 - learning_rate: 0.0010
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 1.0000 - loss: 0.0959 - learning_rate: 0.0010
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 1.0000 - loss: 0.0850 - learning_rate: 0.0010
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 1.0000 - loss: 0.0765 - learning_rate: 0.0010
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 1.0000 - loss: 0.0827 - learning_rate: 0.0010
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 1.0000 - loss: 0.0759 - learning_rate: 0.0010
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 1.0000 - loss: 0.0745 - learning_rate: 0.0010
Epoch 16/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 1.0000 - loss: 0.0704 - learning_rate: 0.0010
Epoch 17/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 1.0000 - loss: 0.0716 - learning_rate: 0.0010
Epoch 18/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 1.0000 - loss: 0.0671 - learning_rate: 0.0010
Epoch 19/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 1.0000 - loss: 0.0583 - learning_rate: 0.0010
Epoch 20/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 1.0000 - loss: 0.0615 - learning_rate: 0.0010
Epoch 21/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 1.0000 - loss: 0.0578 - learning_rate: 0.0010
Epoch 22/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 1.0000 - loss: 0.0525 - learning_rate: 0.0010
Epoch 23/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.0560 - learning_rate: 0.0010
Epoch 24/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 1.0000 - loss: 0.0558 - learning_rate: 0.0010
Epoch 25/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 1.0000 - loss: 0.0544 - learning_rate: 0.0010
Epoch 26/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 1.0000 - loss: 0.0572 - learning_rate: 0.0010
Epoch 27/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 1.0000 - loss: 0.0521 - learning_rate: 0.0010
Epoch 28/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 1.0000 - loss: 0.0512 - learning_rate: 0.0010
Epoch 29/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 1.0000 - loss: 0.0508 - learning_rate: 0.0010
Epoch 30/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 1.0000 - loss: 0.0505 - learning_rate: 0.0010
Epoch 31/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0512 - learning_rate: 0.0010
Epoch 32/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0489 - learning_rate: 0.0010
Epoch 33/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.0462 - learning_rate: 0.0010
Epoch 34/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 1.0000 - loss: 0.0486 - learning_rate: 0.0010
Epoch 35/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0470 - learning_rate: 0.0010
Epoch 36/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0477 - learning_rate: 0.0010
Epoch 37/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.0507 - learning_rate: 0.0010
Epoch 38/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0457 - learning_rate: 0.0010
Epoch 39/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0462 - learning_rate: 0.0010
Epoch 40/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0484 - learning_rate: 0.0010
Epoch 41/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0492 - learning_rate: 0.0010
Epoch 42/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.0456 - learning_rate: 0.0010
Epoch 43/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0480 - learning_rate: 0.0010
Epoch 44/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0475 - learning_rate: 0.0010
Epoch 45/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0441 - learning_rate: 0.0010
Epoch 46/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.0438 - learning_rate: 0.0010
Epoch 47/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0440 - learning_rate: 0.0010
Epoch 48/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0447 - learning_rate: 0.0010
Epoch 49/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0459 - learning_rate: 0.0010
Epoch 50/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.0451 - learning_rate: 0.0010
Epoch 51/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.0442 - learning_rate: 0.0010
Epoch 52/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0464 - learning_rate: 0.0010
Epoch 53/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0430 - learning_rate: 0.0010
Epoch 54/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.0423 - learning_rate: 0.0010
Epoch 55/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.0409 - learning_rate: 0.0010
Epoch 56/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0427 - learning_rate: 0.0010
Epoch 57/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0429 - learning_rate: 0.0010
Epoch 58/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.0421 - learning_rate: 0.0010
Epoch 59/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.0416 - learning_rate: 0.0010
Epoch 60/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0419 - learning_rate: 0.0010
Epoch 61/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0409 - learning_rate: 0.0010
Epoch 62/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.0422 - learning_rate: 0.0010
Epoch 63/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0423 - learning_rate: 0.0010
Epoch 64/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0405 - learning_rate: 0.0010
Epoch 65/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0412 - learning_rate: 0.0010
Epoch 66/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.0425 - learning_rate: 0.0010
Epoch 67/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0422 - learning_rate: 0.0010
Epoch 68/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.0410 - learning_rate: 0.0010
Epoch 69/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0403 - learning_rate: 0.0010
Epoch 70/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.0404 - learning_rate: 0.0010
Epoch 71/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0412 - learning_rate: 0.0010
Epoch 72/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.0398 - learning_rate: 0.0010
Epoch 73/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0394 - learning_rate: 0.0010
Epoch 74/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0408 - learning_rate: 0.0010
Epoch 75/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.0415 - learning_rate: 0.0010
Epoch 76/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0399 - learning_rate: 0.0010
Epoch 77/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0394 - learning_rate: 0.0010
Epoch 78/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0393 - learning_rate: 0.0010
Epoch 79/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0394 - learning_rate: 0.0010
Epoch 80/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0377 - learning_rate: 0.0010
Epoch 81/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0390 - learning_rate: 0.0010
Epoch 82/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0400 - learning_rate: 0.0010
Epoch 83/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0374 - learning_rate: 0.0010
Epoch 84/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0392 - learning_rate: 0.0010
Epoch 85/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.0393 - learning_rate: 0.0010
Epoch 86/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0381 - learning_rate: 0.0010
Epoch 87/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0385 - learning_rate: 0.0010
Epoch 88/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.0382 - learning_rate: 0.0010
Epoch 89/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0393 - learning_rate: 0.0010
Epoch 90/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0378 - learning_rate: 0.0010
Epoch 91/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 1.0000 - loss: 0.0377 - learning_rate: 0.0010
Epoch 92/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0416 - learning_rate: 0.0010
Epoch 93/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0374 - learning_rate: 0.0010
Epoch 94/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0379 - learning_rate: 0.0010
Epoch 95/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0373 - learning_rate: 0.0010
Epoch 96/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.0379 - learning_rate: 0.0010
Epoch 97/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0368 - learning_rate: 0.0010
Epoch 98/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0358 - learning_rate: 0.0010
Epoch 99/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0372 - learning_rate: 0.0010
Epoch 100/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0374 - learning_rate: 0.0010
Epoch 101/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0365 - learning_rate: 0.0010
Epoch 102/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0366 - learning_rate: 0.0010
Epoch 103/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0371 - learning_rate: 0.0010
Epoch 104/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0355 - learning_rate: 0.0010
Epoch 105/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0367 - learning_rate: 0.0010
Epoch 106/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 1.0000 - loss: 0.0361 - learning_rate: 0.0010
Epoch 107/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 1.0000 - loss: 0.0367 - learning_rate: 0.0010
Epoch 108/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.0369 - learning_rate: 0.0010
Epoch 109/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0366 - learning_rate: 0.0010
Epoch 110/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0361 - learning_rate: 0.0010
Epoch 111/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.0378 - learning_rate: 0.0010
Epoch 112/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.0359 - learning_rate: 0.0010
Epoch 113/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0356 - learning_rate: 0.0010
Epoch 114/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0375 - learning_rate: 0.0010
Epoch 115/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0353 - learning_rate: 0.0010
Epoch 116/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0355 - learning_rate: 0.0010
Epoch 117/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 1.0000 - loss: 0.0354 - learning_rate: 0.0010
Epoch 118/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.0355 - learning_rate: 0.0010
Epoch 119/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0351 - learning_rate: 0.0010
Epoch 120/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0356 - learning_rate: 0.0010
Epoch 121/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0343 - learning_rate: 0.0010
Epoch 122/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0351 - learning_rate: 0.0010
Epoch 123/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 1.0000 - loss: 0.0344 - learning_rate: 0.0010
Epoch 124/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.0368 - learning_rate: 0.0010
Epoch 125/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.0343 - learning_rate: 0.0010
Epoch 126/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0349 - learning_rate: 0.0010
Epoch 127/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0340 - learning_rate: 0.0010
Epoch 128/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0342 - learning_rate: 0.0010
Epoch 129/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0343 - learning_rate: 0.0010
Epoch 130/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0342 - learning_rate: 0.0010
Epoch 131/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0341 - learning_rate: 0.0010
Epoch 132/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0341 - learning_rate: 0.0010
Epoch 133/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.0333 - learning_rate: 0.0010
Epoch 134/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.0346 - learning_rate: 0.0010
Epoch 135/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.0333 - learning_rate: 0.0010
Epoch 136/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0336 - learning_rate: 0.0010
Epoch 137/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.0350 - learning_rate: 0.0010
Epoch 138/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0335 - learning_rate: 0.0010
Epoch 139/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.0332 - learning_rate: 0.0010
Epoch 140/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.0339 - learning_rate: 0.0010
Epoch 141/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 1.0000 - loss: 0.0331 - learning_rate: 0.0010
Epoch 142/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.0320 - learning_rate: 0.0010
Epoch 143/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.0330 - learning_rate: 0.0010
Epoch 144/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0368 - learning_rate: 0.0010
Epoch 145/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0326 - learning_rate: 0.0010
Epoch 146/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0330 - learning_rate: 0.0010
Epoch 147/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 1.0000 - loss: 0.0327 - learning_rate: 0.0010
Epoch 148/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0334 - learning_rate: 0.0010
Epoch 149/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0326 - learning_rate: 0.0010
Epoch 150/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0324 - learning_rate: 0.0010
Epoch 151/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.0319 - learning_rate: 0.0010
Epoch 152/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0316 - learning_rate: 0.0010
Epoch 153/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0318 - learning_rate: 0.0010
Epoch 154/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.0316 - learning_rate: 0.0010
Epoch 155/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 1.0000 - loss: 0.0320 - learning_rate: 0.0010
Epoch 156/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0328 - learning_rate: 0.0010
Epoch 157/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.0318 - learning_rate: 0.0010
Epoch 158/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0324 - learning_rate: 0.0010
Epoch 159/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 1.0000 - loss: 0.0324 - learning_rate: 0.0010
Epoch 160/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.0321 - learning_rate: 0.0010
Epoch 161/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0319 - learning_rate: 0.0010
Epoch 162/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0313 - learning_rate: 0.0010
Epoch 163/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0314 - learning_rate: 0.0010
Epoch 164/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.0321 - learning_rate: 0.0010
Epoch 165/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0309 - learning_rate: 0.0010
Epoch 166/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0312 - learning_rate: 0.0010
Epoch 167/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0315 - learning_rate: 0.0010
Epoch 168/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0322 - learning_rate: 0.0010
Epoch 169/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 1.0000 - loss: 0.0315 - learning_rate: 0.0010
Epoch 170/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0307 - learning_rate: 0.0010
Epoch 171/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.0313 - learning_rate: 0.0010
Epoch 172/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.0307 - learning_rate: 0.0010
Epoch 173/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0301 - learning_rate: 0.0010
Epoch 174/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.0301 - learning_rate: 0.0010
Epoch 175/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0305 - learning_rate: 0.0010
Epoch 176/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0312 - learning_rate: 0.0010
Epoch 177/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.0301 - learning_rate: 0.0010
Epoch 178/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 1.0000 - loss: 0.0304 - learning_rate: 0.0010
Epoch 179/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0310 - learning_rate: 0.0010
Epoch 180/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0311 - learning_rate: 0.0010
Epoch 181/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0306 - learning_rate: 0.0010
Epoch 182/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.0309 - learning_rate: 0.0010
Epoch 183/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.0303 - learning_rate: 0.0010
Epoch 184/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.0308 - learning_rate: 0.0010