In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.56.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.8.3)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import re
import shutil
import string
from sklearn.metrics import classification_report
import tensorflow as tf
from keras.models import Model
from tensorflow.keras import layers
from tensorflow.keras import losses
from tensorflow.keras.optimizers import Adam
from keras.callbacks import EarlyStopping,ModelCheckpoint
from tensorflow.keras.layers import Dense, Input, Dropout, Bidirectional, LSTM, Embedding, BatchNormalization,  Reshape, Conv2D, MaxPool2D, concatenate, Flatten, Activation
import torch
import numpy as np
from transformers import BertTokenizer, BertModel,RobertaTokenizer, RobertaModel,AutoTokenizer, AutoModel
import ast

In [ ]:
# Verificar si la GPU está disponible
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
archivo_3 = '/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/ResultsBERT/DataProgramsandDescriptions-CatRetroalimentacion5000.xlsx'
train_full = pd.read_excel(archivo_3)

# AST spliter D. Gries form

In [ ]:
class WhileLoopFinder(ast.NodeVisitor):
    def __init__(self, source_code):
        self.source_code = source_code.splitlines()
        self.functions_with_while = []
        self.current_function = None

    def visit_FunctionDef(self, node):
        original_current_function = self.current_function
        self.current_function = {
            "function_name": node.name,
            "has_while_loop": False,
            "pre_while_code_lines": [],
            "while_loops": []
        }

        function_start_line = node.lineno - 1
        function_end_line = (node.end_lineno if hasattr(node, 'end_lineno') else len(self.source_code))
        function_lines = self.source_code[function_start_line:function_end_line]

        found_while = False
        for stmt in node.body:
            if isinstance(stmt, ast.While):
                self.current_function["has_while_loop"] = True
                found_while = True
                try:
                    while_condition = ast.unparse(stmt.test).strip()
                    print("OK condition")
                except AttributeError:
                    print("Error al obtener la condición del while")
                try:
                    while_body_code = ast.unparse(ast.Module(body=stmt.body, type_ignores=[])).strip()
                    print("Ok body")
                except AttributeError:
                    print("Error al obtener el código del cuerpo del while")

                self.current_function["while_loops"].append({
                    "condition": while_condition,
                    "body_code": while_body_code
                })
            elif not found_while:
                start_line = stmt.lineno - 1
                end_line = (stmt.end_lineno if hasattr(stmt, 'end_lineno') else stmt.lineno)
                self.current_function["pre_while_code_lines"].extend(self.source_code[start_line:end_line])
            self.generic_visit(stmt)

        if self.current_function["has_while_loop"]:
            last_while_end_line = None
            if self.current_function["while_loops"]:
                last_while_node = next((node for node in reversed(node.body) if isinstance(node, ast.While)), None)
                if last_while_node and hasattr(last_while_node, 'end_lineno'):
                    last_while_end_line = last_while_node.end_lineno
            post_while_code_lines = []
            if last_while_end_line:
                function_indent = len(self.source_code[node.lineno - 1]) - len(self.source_code[node.lineno - 1].lstrip())
                for line in self.source_code[last_while_end_line:function_end_line]:
                    if line.startswith(self.source_code[node.lineno - 1][:function_indent] + "    "):
                        post_while_code_lines.append(line[function_indent + 4:])
                    else:
                        post_while_code_lines.append(line[function_indent:])
            self.current_function["post_while_code_lines"] = "\n".join(post_while_code_lines).strip()
            self.current_function["pre_while_code_lines"] = "\n".join(self.current_function["pre_while_code_lines"]).strip()
            self.functions_with_while.append(self.current_function)

        self.current_function = original_current_function

In [ ]:
def DGries_states(solution):
  try:
    # Crear el AST
    tree = ast.parse(solution)
    # Recorrer el AST con nuestro visitante
    finder = WhileLoopFinder(solution)
    finder.visit(tree)
    for func_info in finder.functions_with_while:
      initial_state=func_info["pre_while_code_lines"] if func_info["pre_while_code_lines"] else False
      end_state=""
      transformation_state=""
      for j, wl in enumerate(func_info["while_loops"]):
          end_state=wl["condition"]
          transformation_state=wl["body_code"]

      if not initial_state:
        initial_state=transformation_state
      return initial_state,transformation_state,end_state
  except Exception as error:
    return "Exception:"+str(error),"Exception:"+str(error),"Exception:"+str(error)

# Encoder Description and Code

In [ ]:
class Encoder:
  def __init__(self):
    self.is_loadtokenizers=False



  def tokenize_and_generate_embeddings_descriptions(self,description):
    if not self.is_loadtokenizers:
      raise ValueError("tokenizers dont load")
    # Tokenize input description and move tokens to GPU
    tokens = self.beart_tokenizer.encode_plus(description, return_tensors="pt", truncation=True)
    tokens = {key: value.to(device) for key, value in tokens.items()}
    # Generate embeddings
    with torch.no_grad():
        outputs = self.beart_model(**tokens)
    # Extract embeddings for all tokens
    desc_embeddings = outputs.last_hidden_state.cpu().numpy()
    return desc_embeddings

  def tokenize_and_generate_embeddings_codes(self,code):
    if not self.is_loadtokenizers:
      raise ValueError("tokenizers dont load")
    # Tokenize input code and move tokens to GPU
    tokens = self.codebeart_tokenizer.encode_plus(code, return_tensors="pt", truncation=True)
    tokens = {key: value.to(device) for key, value in tokens.items()}
    # Generate embeddings
    with torch.no_grad():
        outputs = self.codebeart_model(**tokens)
    # Extract embeddings for all tokens
    code_embeddings = outputs.last_hidden_state.cpu().numpy()

    return code_embeddings


  def tokenize_and_generate_embeddings_graphcodes(self,code):
    if not self.is_loadtokenizers:
      raise ValueError("tokenizers dont load")
    # Tokenize input code and move tokens to GPU
    tokens = self.graphcodebert_tokenizer.encode_plus(code, return_tensors="pt", truncation=True)
    tokens = {key: value.to(device) for key, value in tokens.items()}
    # Generate embeddings
    with torch.no_grad():
        outputs = self.graphcodebert_model(**tokens)
    # Extract embeddings for all tokens
    code_embeddings = outputs.last_hidden_state.cpu().numpy()
    return code_embeddings

  def load_beart_tokenizer(self):
    # Verificar si la GPU está disponible
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Cargar el tokenizer y el modelo en la GPU si está disponible
    model_name = "bert-base-uncased"
    self.beart_model = BertModel.from_pretrained(model_name)
    self.beart_tokenizer = BertTokenizer.from_pretrained(model_name)
    self.beart_model.to(device)

  def load_graphcodebert_tokenizer(self):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    self.graphcodebert_tokenizer = AutoTokenizer.from_pretrained("microsoft/graphcodebert-base")
    self.graphcodebert_model = AutoModel.from_pretrained("microsoft/graphcodebert-base")
    self.graphcodebert_model.to(device)


  def load_codebert_tokenizer(self):
    # Verificar si la GPU está disponible
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Cargar el tokenizer y el modelo en la GPU si está disponible
    self.codebeart_tokenizer = RobertaTokenizer.from_pretrained("microsoft/codebert-base")
    self.codebeart_model = RobertaModel.from_pretrained("microsoft/codebert-base")
    self.codebeart_model.to(device)

  def start_tokenizer(self):
    self.load_beart_tokenizer()
    #self.load_codebert_tokenizer()
    self.load_graphcodebert_tokenizer()
    self.is_loadtokenizers=True

# All characteristics

In [ ]:
def categoricallabelAll(w):
  if w=="['Correct']":
    return 0
  if w=="['Initial state']":
    return 1
  if w=="['Final state']":
    return 2
  if w=="['State transformation']":
    return 3
  if w=="['Initial state', 'Final state']":
    return 4
  if w=="['Initial state', 'State transformation']":
    return 5
  if w=="['Final state', 'State transformation']":
    return 6
  if w=="['Initial state', 'Final state', 'State transformation']":
    return 7
  return 8

category=np.array([
    'Correct',
    'Initial state',
    'Final state',
    'State transformation',
    'Initial state, Final state',
    'Initial state, State transformation',
    'Final state, State transformation',
    'Initial state, Final state, State transformation'

])

# Load Dataset

In [ ]:
train_full.head()

,No.,Problema,Solución,Estado incial,Estado final,Transformación de estado,Etiqueta 1,Etiqueta 2,Realimentación
0,1,Write a Python function that returns the facto...,def factorial(n):\n result = 1\n i = 1\n...,"result = 1, i = 1",i <= n,"result *= i, i += 1",Correct,['Correct'],NaN
1,2,Write a Python function that returns the sum o...,def sum_1_to_100():\n total = 0\n i = 1\...,"total = 0, i = 1, n = 100",i <= n,"total += i, i += 1",Correct,['Correct'],NaN
2,3,Write a Python function that prints the number...,def print_and_store():\n numbers = []\n ...,"numbers = [], i = 0, n = 10",i <= n,"print(i), numbers.append(i), i += 1",Correct,['Correct'],NaN
3,4,Write a Python function to print the numbers f...,def print_and_store_reverse():\n numbers = ...,"numbers = [], i = 10, n = 1",i >= n,"print(i), numbers.append(i), i -= 1",Correct,['Correct'],NaN
4,5,Write a Python function to check if a number i...,def is_prime(num):\n if num <= 1:\n ...,"i = 2, i = = 0:",i <= num//2,"if num % i == 0:, return False, i += 1",Correct,['Correct'],NaN

In [ ]:
train_full.drop(["No.","Realimentación","Estado incial","Estado final","Transformación de estado"],axis=1,inplace=True)
train_full

,Problema,Solución,Etiqueta 1,Etiqueta 2
0,Write a Python function that returns the facto...,def factorial(n):\n result = 1\n i = 1\n...,Correct,['Correct']
1,Write a Python function that returns the sum o...,def sum_1_to_100():\n total = 0\n i = 1\...,Correct,['Correct']
2,Write a Python function that prints the number...,def print_and_store():\n numbers = []\n ...,Correct,['Correct']
3,Write a Python function to print the numbers f...,def print_and_store_reverse():\n numbers = ...,Correct,['Correct']
4,Write a Python function to check if a number i...,def is_prime(num):\n if num <= 1:\n ...,Correct,['Correct']
...,...,...,...,...
4995,Write a Python function that returns the sum o...,def sum_of_first_five_numbers():\n number =...,Incorrect,"['Initial state', 'Final state']"
4996,Write a Python function that returns the facto...,def factorial(n):\n result = 0\n i = 0\n...,Incorrect,"['Initial state', 'Final state']"
4997,Write a Python function that prints the number...,def print_and_store_numbers():\n numbers = ...,Incorrect,"['Initial state', 'Final state']"
4998,Write a Python function to print the numbers f...,def print_and_store_numbers():\n numbers = ...,Incorrect,"['Initial state', 'Final state']"
4999,Write a Python function that finds the smalles...,def find_smallest(numbers):\n smallest = nu...,Incorrect,"['Initial state', 'Final state']"

In [ ]:
train_full[["Estado incial","Transformación de estado","Estado final"]]=train_full['Solución'].apply(DGries_states).apply(pd.Series)

Streaming output truncated to the last 5000 lines.
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition

In [ ]:
y=train_full['Etiqueta 2'].apply(categoricallabelAll)
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
train_full.dropna(inplace=True)

In [ ]:
np.unique(train_full['Etiqueta 2'])

array(["['Correct']", "['Final state', 'State transformation']",
       "['Final state']",
       "['Initial state', 'Final state', 'State transformation']",
       "['Initial state', 'Final state']",
       "['Initial state', 'State transformation']", "['Initial state']",
       "['State transformation']"], dtype=object)

In [ ]:
train_full

,Problema,Solución,Etiqueta 1,Etiqueta 2,Estado incial,Transformación de estado,Estado final
0,Write a Python function that returns the facto...,def factorial(n):\n result = 1\n i = 1\n...,Correct,['Correct'],result = 1\n i = 1,result *= i\ni += 1,i <= n
1,Write a Python function that returns the sum o...,def sum_1_to_100():\n total = 0\n i = 1\...,Correct,['Correct'],total = 0\n i = 1\n n = 100,total += i\ni += 1,i <= n
2,Write a Python function that prints the number...,def print_and_store():\n numbers = []\n ...,Correct,['Correct'],numbers = []\n i = 0\n n = 10,print(i)\nnumbers.append(i)\ni += 1,i <= n
3,Write a Python function to print the numbers f...,def print_and_store_reverse():\n numbers = ...,Correct,['Correct'],numbers = []\n i = 10\n n = 1,print(i)\nnumbers.append(i)\ni -= 1,i >= n
4,Write a Python function to check if a number i...,def is_prime(num):\n if num <= 1:\n ...,Correct,['Correct'],if num <= 1:\n return False\n i = 2,if num % i == 0:\n return False\ni += 1,i <= num // 2
...,...,...,...,...,...,...,...
4995,Write a Python function that returns the sum o...,def sum_of_first_five_numbers():\n number =...,Incorrect,"['Initial state', 'Final state']",number = 1\n total_sum = 0\n count = 1,total_sum = total_sum + number\ncount = count - 1,count < 5
4996,Write a Python function that returns the facto...,def factorial(n):\n result = 0\n i = 0\n...,Incorrect,"['Initial state', 'Final state']",result = 0\n i = 0,result *= i\ni += 1,i < n
4997,Write a Python function that prints the number...,def print_and_store_numbers():\n numbers = ...,Incorrect,"['Initial state', 'Final state']",numbers = []\n n = 1,print(n)\nnumbers.append(n)\nn += 1,n <= 11
4998,Write a Python function to print the numbers f...,def print_and_store_numbers():\n numbers = ...,Incorrect,"['Initial state', 'Final state']",numbers = []\n n = 9,print(n)\nnumbers.append(n)\nn -= 1,n >= 0
4999,Write a Python function that finds the smalles...,def find_smallest(numbers):\n smallest = nu...,Incorrect,"['Initial state', 'Final state']",smallest = numbers[0]\n i = 1,if numbers[i] < smallest:\n smallest = numb...,i > len(numbers)

In [ ]:
encoder=Encoder()
encoder.start_tokenizer()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/539 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at microsoft/graphcodebert-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
%%time
problem=train_full['Problema'].apply(encoder.tokenize_and_generate_embeddings_descriptions).to_numpy()
code=train_full['Solución'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
startstate = train_full['Estado incial'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
finalstate = train_full['Estado final'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
transstate = train_full['Transformación de estado'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()

CPU times: user 3min 10s, sys: 816 ms, total: 3min 10s
Wall time: 3min 10s

In [ ]:
problem.shape,code.shape,startstate.shape,finalstate.shape,transstate.shape

((4919,), (4919,), (4919,), (4919,), (4919,))

In [ ]:
print(startstate.shape)
print(startstate[1262].shape)

(4919,)
(1, 17, 768)

In [ ]:
Xp=np.array([sentence[0].mean(axis=0) for sentence in problem])
Xcode=np.array([sentence[0].mean(axis=0) for sentence in code])
Xs=np.array([sentence[0].mean(axis=0) for sentence in startstate])
Xf=np.array([sentence[0].mean(axis=0) for sentence in finalstate])
Xt=np.array([sentence[0].mean(axis=0) for sentence in transstate])
Xp.shape,Xs.shape,Xf.shape,Xt.shape

((4919, 768), (4919, 768), (4919, 768), (4919, 768))

In [ ]:
y=train_full['Etiqueta 2'].apply(categoricallabelAll)
y=y.to_numpy()
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
from sklearn.model_selection import train_test_split

Xp_train,Xp_test,Xcode_train,Xcode_test,Xs_train,Xs_test,Xt_train,Xt_test,Xf_train,Xf_test,y_train,y_test=train_test_split(Xp,Xcode,Xs,Xt,Xf,y,test_size=0.2,random_state=2023, stratify=y)

In [ ]:
Xp_train.shape,Xp_test.shape,Xcode_train.shape, Xcode_test.shape, Xs_train.shape,Xs_test.shape,Xt_train.shape,Xt_test.shape,Xf_train.shape,Xf_test.shape,y_train.shape,y_test.shape

((3935, 768),
 (984, 768),
 (3935, 768),
 (984, 768),
 (3935, 768),
 (984, 768),
 (3935, 768),
 (984, 768),
 (3935, 768),
 (984, 768),
 (3935,),
 (984,))

In [ ]:
#random search
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import matthews_corrcoef
#XGBoost
from xgboost import XGBClassifier
#pipeline
from sklearn.pipeline import Pipeline
from sklearn.neural_network import MLPClassifier

In [ ]:
from sklearn.metrics import matthews_corrcoef, precision_recall_curve, auc
from sklearn.preprocessing import label_binarize
import numpy as np

def calculate_mcc_multiclass(y_true, y_pred_probs):
    y_pred_labels = np.argmax(y_pred_probs, axis=1)
    # Convertir etiquetas verdaderas one-hot a etiquetas enteras si es necesario
    #y_true_labels = np.argmax(y_true, axis=1) if y_true.ndim > 1 else y_true
    return matthews_corrcoef(y_true, y_pred_labels)

def calculate_auc_pr_multiclass(y_true, y_pred_probs, average='macro'):
    n_classes = y_pred_probs.shape[1]
    #y_true_labels = np.argmax(y_true, axis=1) if y_true.ndim > 1 else y_true
    y_true_bin = label_binarize(y_true, classes=range(n_classes))

    auc_pr_list = []
    for i in range(n_classes):
        precision, recall, _ = precision_recall_curve(y_true_bin[:, i], y_pred_probs[:, i])
        auc_pr_list.append(auc(recall, precision))

    if average == 'macro':
        return np.mean(auc_pr_list)
    elif average == 'weighted':
        class_counts = y_true_bin.sum(axis=0)
        return np.average(auc_pr_list, weights=class_counts)
    else:
        return auc_pr_list

# KNN

In [ ]:
from tensorflow.keras.losses import sparse_categorical_crossentropy
from sklearn.ensemble import VotingClassifier,StackingClassifier
from sklearn.linear_model import LogisticRegression

In [ ]:
accuracies_train=[]
accuracies_predict=[]
loss_predict=[]
times_train=[]
times_predict=[]
mccs_predict=[]
aucpr_predict=[]
ml_names=[]
abl_names=[]

In [ ]:
import joblib

In [ ]:
path="/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/1. Tradicional Machine Learning/"

In [ ]:
from time import time
knn=KNeighborsClassifier(n_neighbors=3,p=1,weights='distance')
svm_pipe=Pipeline([
    ('scaler',StandardScaler()),
    ('classifier',SVC(kernel='rbf',gamma=0.000379269019073225,C=233.57214690901213,probability=True))
])
mlp_pipe=Pipeline([
    ('scaler',StandardScaler()),
    ('classifier',MLPClassifier(hidden_layer_sizes=(100,100,100),learning_rate='adaptive'))
])

rf=RandomForestClassifier(n_estimators=70,max_depth=15)

vt=VotingClassifier(estimators=[('mlp',mlp_pipe),('rf',rf)],voting='soft')
st=StackingClassifier(estimators=[('mlp',mlp_pipe),('rf',rf)],final_estimator=LogisticRegression())

models=[knn,svm_pipe,mlp_pipe,rf,vt,st]
models_names=["KNN","SVM","MLP","Random Forest","Voting","Stacking"]
ablations_names=["problemall","problem_gries","code_gries","gries","problem_code","code"]

for model,name in zip(models,models_names):
  print(name)
  # Define the full datasets outside the inner loop
  X_train_full = np.concatenate((Xp_train,Xcode_train,Xs_train,Xt_train,Xf_train),axis=1)
  X_test_full = np.concatenate((Xp_test,Xcode_test,Xs_test,Xt_test,Xf_test),axis=1)

  for ablations_name in ablations_names:
    ml_names.append(name)
    abl_names.append(ablations_name)
    print(ablations_name)

    if ablations_name=="problemall":
      X_train = X_train_full
      X_test = X_test_full
    elif ablations_name=="problem_gries":
      X_train=np.concatenate((Xp_train,Xs_train,Xt_train,Xf_train),axis=1)
      X_test=np.concatenate((Xp_test,Xs_test,Xt_test,Xf_test),axis=1) # Corrected X_test construction
    elif ablations_name=="code_gries":
      X_train=np.concatenate((Xcode_train,Xs_train,Xt_train,Xf_train),axis=1)
      X_test=np.concatenate((Xcode_test,Xs_test,Xt_test,Xf_test),axis=1) # Corrected X_test construction
    elif ablations_name=="gries":
      X_train=np.concatenate((Xs_train,Xt_train,Xf_train),axis=1)
      X_test=np.concatenate((Xs_test,Xt_test,Xf_test),axis=1) # Corrected X_test construction
    elif ablations_name=="problem_code":
      X_train=np.concatenate((Xp_train,Xcode_train),axis=1)
      X_test=np.concatenate((Xp_test,Xcode_test),axis=1) # Corrected X_test construction
    elif ablations_name=="code":
      X_train=Xcode_train # Corrected X_train construction
      X_test=Xcode_test # Corrected X_test construction

    time1=time()
    model.fit(X_train,y_train)
    time2=time()
    joblib.dump(model,path+"graph_"+name+"_"+ablations_name+".joblib")
    times_train.append(time2-time1)
    time1=time()
    y_pred=model.predict(X_test)
    time2=time()
    times_predict.append(time2-time1)

    accuracie_train=model.score(X_train,y_train)
    accuracies_train.append(accuracie_train)
    accuracie_test=model.score(X_test,y_test)
    accuracies_predict.append(accuracie_test)
    #sparse_categorical_crossentropy
    y_pred_proba = model.predict_proba(X_test)
    loss=np.mean(sparse_categorical_crossentropy(y_test,y_pred_proba))
    loss_predict.append(loss)
    mcc = matthews_corrcoef(y_test, y_pred)
    mccs_predict.append(mcc)
    auc_pr = calculate_auc_pr_multiclass(y_test, model.predict_proba(X_test))
    aucpr_predict.append(auc_pr)
    print(classification_report(y_test,y_pred))
    print("Accuracy train",accuracie_train)
    print("Accuracy predict",accuracie_test)
    print("Loss",loss)
    print("MCC",mcc)
    print("AUC",auc_pr)
    print("==================================")

KNN
problemall
              precision    recall  f1-score   support

           0       0.90      0.83      0.86       292
           1       0.93      0.93      0.93       198
           2       0.94      0.95      0.95       197
           3       0.83      0.91      0.87       197
           4       0.93      0.96      0.94        26
           5       0.79      0.76      0.78        25
           6       1.00      0.93      0.96        28
           7       1.00      1.00      1.00        21

    accuracy                           0.90       984
   macro avg       0.91      0.91      0.91       984
weighted avg       0.90      0.90      0.90       984

Accuracy train 0.9956797966963151
Accuracy predict 0.9004065040650406
Loss 0.9900802896212624
MCC 0.8745241037893227
AUC 0.9515437658415379
==================================
problem_gries
              precision    recall  f1-score   support

           0       0.88      0.83      0.85       292
           1       0.93      0.94      0.94       198
           2       0.95      0.95      0.95       197
           3       0.82      0.87      0.84       197
           4       0.89      0.96      0.93        26
           5       0.83      0.76      0.79        25
           6       1.00      0.93      0.96        28
           7       0.95      1.00      0.98        21

    accuracy                           0.89       984
   macro avg       0.91      0.91      0.91       984
weighted avg       0.90      0.89      0.89       984

Accuracy train 0.9921219822109276
Accuracy predict 0.8943089430894309
Loss 1.0610689007886869
MCC 0.8664962937001177
AUC 0.9443267809676767
==================================
code_gries
              precision    recall  f1-score   support

           0       0.90      0.83      0.86       292
           1       0.93      0.93      0.93       198
           2       0.94      0.95      0.95       197
           3       0.83      0.91      0.87       197
           4       0.93      0.96      0.94        26
           5       0.79      0.76      0.78        25
           6       1.00      0.93      0.96        28
           7       1.00      1.00      1.00        21

    accuracy                           0.90       984
   macro avg       0.91      0.91      0.91       984
weighted avg       0.90      0.90      0.90       984

Accuracy train 0.995425667090216
Accuracy predict 0.9004065040650406
Loss 0.9593525398503607
MCC 0.8745241037893227
AUC 0.9517827076221853
==================================
gries
              precision    recall  f1-score   support

           0       0.87      0.84      0.85       292
           1       0.94      0.94      0.94       198
           2       0.95      0.95      0.95       197
           3       0.82      0.87      0.85       197
           4       0.89      0.96      0.93        26
           5       0.83      0.76      0.79        25
           6       1.00      0.93      0.96        28
           7       0.95      1.00      0.98        21

    accuracy                           0.90       984
   macro avg       0.91      0.91      0.91       984
weighted avg       0.90      0.90      0.90       984

Accuracy train 0.9911054637865311
Accuracy predict 0.8963414634146342
Loss 0.9990623064968115
MCC 0.8689067245034162
AUC 0.945152979672865
==================================
problem_code
              precision    recall  f1-score   support

           0       0.92      0.83      0.87       292
           1       0.95      0.95      0.95       198
           2       0.88      0.95      0.91       197
           3       0.87      0.89      0.88       197
           4       0.86      0.96      0.91        26
           5       0.70      0.76      0.73        25
           6       0.90      0.93      0.91        28
           7       1.00      1.00      1.00        21

    accuracy                           0.90       984
   macro avg       0.88      0.91      0.90       984
weighted avg       0.90      0.90      0.90       984

Accuracy train 0.9951715374841169
Accuracy predict 0.899390243902439
Loss 1.087104413868321
MCC 0.8737405061614923
AUC 0.9436200441275898
==================================
code
              precision    recall  f1-score   support

           0       0.92      0.83      0.87       292
           1       0.94      0.95      0.95       198
           2       0.89      0.95      0.92       197
           3       0.87      0.89      0.88       197
           4       0.93      0.96      0.94        26
           5       0.70      0.76      0.73        25
           6       0.90      0.93      0.91        28
           7       1.00      1.00      1.00        21

    accuracy                           0.90       984
   macro avg       0.89      0.91      0.90       984
weighted avg       0.90      0.90      0.90       984

Accuracy train 0.995425667090216
Accuracy predict 0.9014227642276422
Loss 1.0402226173715123
MCC 0.8761122811098873
AUC 0.9482830963144862
==================================
SVM
problemall
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       292
           1       0.93      0.96      0.95       198
           2       0.97      0.96      0.97       197
           3       0.92      0.94      0.93       197
           4       1.00      0.96      0.98        26
           5       0.95      0.72      0.82        25
           6       0.96      0.93      0.95        28
           7       1.00      1.00      1.00        21

    accuracy                           0.94       984
   macro avg       0.96      0.92      0.94       984
weighted avg       0.94      0.94      0.94       984

Accuracy train 0.9951715374841169
Accuracy predict 0.9390243902439024
Loss 0.26330889964942045
MCC 0.9226708079035775
AUC 0.9589024464255563
==================================
problem_gries
              precision    recall  f1-score   support

           0       0.89      0.91      0.90       292
           1       0.96      0.95      0.96       198
           2       0.96      0.96      0.96       197
           3       0.88      0.90      0.89       197
           4       1.00      0.96      0.98        26
           5       0.95      0.72      0.82        25
           6       0.96      0.93      0.95        28
           7       1.00      1.00      1.00        21

    accuracy                           0.93       984
   macro avg       0.95      0.92      0.93       984
weighted avg       0.93      0.93      0.93       984

Accuracy train 0.9911054637865311
Accuracy predict 0.9258130081300813
Loss 0.29467115419693385
MCC 0.9057630880869394
AUC 0.9564843727998293
==================================
code_gries
              precision    recall  f1-score   support

           0       0.93      0.92      0.93       292
           1       0.94      0.96      0.95       198
           2       0.97      0.97      0.97       197
           3       0.92      0.94      0.93       197
           4       1.00      0.96      0.98        26
           5       0.95      0.72      0.82        25
           6       0.96      0.93      0.95        28
           7       1.00      1.00      1.00        21

    accuracy                           0.94       984
   macro avg       0.96      0.93      0.94       984
weighted avg       0.94      0.94      0.94       984

Accuracy train 0.9949174078780177
Accuracy predict 0.943089430894309
Loss 0.25662822656736056
MCC 0.9278238366507737
AUC 0.9604332622002782
==================================
gries
              precision    recall  f1-score   support

           0       0.89      0.91      0.90       292
           1       0.96      0.95      0.96       198
           2       0.96      0.97      0.97       197
           3       0.87      0.89      0.88       197
           4       1.00      0.96      0.98        26
           5       0.95      0.72      0.82        25
           6       0.96      0.86      0.91        28
           7       1.00      1.00      1.00        21

    accuracy                           0.92       984
   macro avg       0.95      0.91      0.93       984
weighted avg       0.92      0.92      0.92       984

Accuracy train 0.9893265565438374
Accuracy predict 0.9237804878048781
Loss 0.2935676784045946
MCC 0.9031445127377953
AUC 0.9578897421925456
==================================
problem_code
              precision    recall  f1-score   support

           0       0.90      0.88      0.89       292
           1       0.93      0.92      0.93       198
           2       0.91      0.95      0.93       197
           3       0.88      0.92      0.90       197
           4       1.00      0.96      0.98        26
           5       0.84      0.64      0.73        25
           6       1.00      1.00      1.00        28
           7       1.00      1.00      1.00        21

    accuracy                           0.91       984
   macro avg       0.93      0.91      0.92       984
weighted avg       0.91      0.91      0.91       984

Accuracy train 0.9888182973316392
Accuracy predict 0.9115853658536586
Loss 0.3491863563191163
MCC 0.88795677217749
AUC 0.9481401253877857
==================================
code
              precision    recall  f1-score   support

           0       0.88      0.89      0.88       292
           1       0.94      0.91      0.92       198
           2       0.94      0.93      0.94       197
           3       0.88      0.93      0.90       197
           4       1.00      0.96      0.98        26
           5       0.94      0.64      0.76        25
           6       1.00      1.00      1.00        28
           7       1.00      1.00      1.00        21

    accuracy                           0.91       984
   macro avg       0.95      0.91      0.92       984
weighted avg       0.91      0.91      0.91       984

Accuracy train 0.9850063532401525
Accuracy predict 0.9115853658536586
Loss 0.36667245226851486
MCC 0.887746708369285
AUC 0.9443915161675088
==================================
MLP
problemall
              precision    recall  f1-score   support

           0       0.90      0.92      0.91       292
           1       0.96      0.93      0.95       198
           2       0.95      1.00      0.97       197
           3       0.89      0.88      0.88       197
           4       0.96      0.88      0.92        26
           5       0.94      0.68      0.79        25
           6       1.00      0.89      0.94        28
           7       0.91      1.00      0.95        21

    accuracy                           0.92       984
   macro avg       0.94      0.90      0.92       984
weighted avg       0.93      0.92      0.92       984

Accuracy train 0.9811944091486658
Accuracy predict 0.9247967479674797
Loss 0.3498859
MCC 0.9045170314681878
AUC 0.9588061484149417
==================================
problem_gries
              precision    recall  f1-score   support

           0       0.88      0.92      0.90       292
           1       0.93      0.93      0.93       198
           2       0.95      0.97      0.96       197
           3       0.91      0.85      0.88       197
           4       0.93      1.00      0.96        26
           5       1.00      0.72      0.84        25
           6       1.00      0.89      0.94        28
           7       0.88      1.00      0.93        21

    accuracy                           0.92       984
   macro avg       0.93      0.91      0.92       984
weighted avg       0.92      0.92      0.92       984

Accuracy train 0.9773824650571792
Accuracy predict 0.9176829268292683
Loss 0.411167
MCC 0.8956059311883482
AUC 0.9598566774965335
==================================
code_gries
              precision    recall  f1-score   support

           0       0.94      0.91      0.93       292
           1       0.95      0.94      0.94       198
           2       0.95      0.98      0.97       197
           3       0.88      0.93      0.90       197
           4       0.96      0.96      0.96        26
           5       1.00      0.76      0.86        25
           6       1.00      0.86      0.92        28
           7       0.91      1.00      0.95        21

    accuracy                           0.93       984
   macro avg       0.95      0.92      0.93       984
weighted avg       0.94      0.93      0.93       984

Accuracy train 0.988310038119441
Accuracy predict 0.9339430894308943
Loss 0.41551098
MCC 0.9164265706562089
AUC 0.9552828800977475
==================================
gries
              precision    recall  f1-score   support

           0       0.87      0.87      0.87       292
           1       0.97      0.92      0.95       198
           2       0.96      0.96      0.96       197
           3       0.83      0.87      0.85       197
           4       0.93      1.00      0.96        26
           5       0.78      0.84      0.81        25
           6       0.96      0.86      0.91        28
           7       1.00      1.00      1.00        21

    accuracy                           0.90       984
   macro avg       0.91      0.92      0.91       984
weighted avg       0.91      0.90      0.90       984

Accuracy train 0.9730622617534943
Accuracy predict 0.9044715447154471
Loss 0.37980542
MCC 0.8790354612629335
AUC 0.9574687082149205
==================================
problem_code
              precision    recall  f1-score   support

           0       0.89      0.86      0.88       292
           1       0.91      0.94      0.93       198
           2       0.91      0.88      0.89       197
           3       0.84      0.89      0.86       197
           4       0.89      0.96      0.93        26
           5       0.89      0.64      0.74        25
           6       0.88      1.00      0.93        28
           7       0.90      0.90      0.90        21

    accuracy                           0.89       984
   macro avg       0.89      0.88      0.88       984
weighted avg       0.89      0.89      0.89       984

Accuracy train 0.9689961880559085
Accuracy predict 0.8882113821138211
Loss 0.54620165
MCC 0.858622873169259
AUC 0.944575968934509
==================================
code
              precision    recall  f1-score   support

           0       0.92      0.89      0.91       292
           1       0.91      0.94      0.93       198
           2       0.86      0.96      0.91       197
           3       0.92      0.86      0.89       197
           4       1.00      0.85      0.92        26
           5       1.00      0.68      0.81        25
           6       0.87      0.93      0.90        28
           7       1.00      1.00      1.00        21

    accuracy                           0.91       984
   macro avg       0.93      0.89      0.91       984
weighted avg       0.91      0.91      0.91       984

Accuracy train 0.9720457433290979
Accuracy predict 0.907520325203252
Loss 0.45686308
MCC 0.8831699235029223
AUC 0.9524741534205612
==================================
Random Forest
problemall
              precision    recall  f1-score   support

           0       0.90      0.93      0.91       292
           1       0.96      0.94      0.95       198
           2       0.97      0.96      0.97       197
           3       0.90      0.92      0.91       197
           4       1.00      0.96      0.98        26
           5       1.00      0.72      0.84        25
           6       1.00      0.93      0.96        28
           7       1.00      1.00      1.00        21

    accuracy                           0.93       984
   macro avg       0.97      0.92      0.94       984
weighted avg       0.94      0.93      0.93       984

Accuracy train 0.9941550190597205
Accuracy predict 0.9339430894308943
Loss 0.38095994890787144
MCC 0.9160834810109921
AUC 0.9673332295876946
==================================
problem_gries
              precision    recall  f1-score   support

           0       0.88      0.90      0.89       292
           1       0.94      0.93      0.94       198
           2       0.97      0.96      0.97       197
           3       0.86      0.89      0.88       197
           4       1.00      0.96      0.98        26
           5       1.00      0.72      0.84        25
           6       1.00      0.89      0.94        28
           7       1.00      1.00      1.00        21

    accuracy                           0.92       984
   macro avg       0.96      0.91      0.93       984
weighted avg       0.92      0.92      0.92       984

Accuracy train 0.9903430749682338
Accuracy predict 0.9176829268292683
Loss 0.39401657440449656
MCC 0.895376330269981
AUC 0.9609193966919641
==================================
code_gries
              precision    recall  f1-score   support

           0       0.88      0.91      0.90       292
           1       0.96      0.94      0.95       198
           2       0.98      0.95      0.96       197
           3       0.88      0.93      0.91       197
           4       1.00      0.96      0.98        26
           5       1.00      0.68      0.81        25
           6       1.00      0.93      0.96        28
           7       1.00      1.00      1.00        21

    accuracy                           0.93       984
   macro avg       0.96      0.91      0.93       984
weighted avg       0.93      0.93      0.93       984

Accuracy train 0.9946632782719187
Accuracy predict 0.9278455284552846
Loss 0.38209156636082925
MCC 0.9083965539109112
AUC 0.9685756350673701
==================================
gries
              precision    recall  f1-score   support

           0       0.87      0.92      0.89       292
           1       0.96      0.94      0.95       198
           2       0.96      0.97      0.97       197
           3       0.87      0.87      0.87       197
           4       1.00      0.96      0.98        26
           5       1.00      0.68      0.81        25
           6       1.00      0.86      0.92        28
           7       1.00      1.00      1.00        21

    accuracy                           0.92       984
   macro avg       0.96      0.90      0.93       984
weighted avg       0.92      0.92      0.92       984

Accuracy train 0.9890724269377382
Accuracy predict 0.9207317073170732
Loss 0.39081375827852116
MCC 0.8992146683222475
AUC 0.9560510972857181
==================================
problem_code
              precision    recall  f1-score   support

           0       0.90      0.91      0.91       292
           1       0.95      0.95      0.95       198
           2       0.94      0.95      0.95       197
           3       0.90      0.92      0.91       197
           4       1.00      0.96      0.98        26
           5       1.00      0.76      0.86        25
           6       1.00      0.93      0.96        28
           7       1.00      1.00      1.00        21

    accuracy                           0.93       984
   macro avg       0.96      0.92      0.94       984
weighted avg       0.93      0.93      0.93       984

Accuracy train 0.9956797966963151
Accuracy predict 0.9308943089430894
Loss 0.4641104103583592
MCC 0.9122257051565089
AUC 0.9596211755490546
==================================
code
              precision    recall  f1-score   support

           0       0.88      0.90      0.89       292
           1       0.94      0.93      0.94       198
           2       0.94      0.95      0.95       197
           3       0.91      0.91      0.91       197
           4       1.00      0.96      0.98        26
           5       1.00      0.76      0.86        25
           6       1.00      0.86      0.92        28
           7       1.00      1.00      1.00        21

    accuracy                           0.92       984
   macro avg       0.96      0.91      0.93       984
weighted avg       0.92      0.92      0.92       984

Accuracy train 0.995425667090216
Accuracy predict 0.9207317073170732
Loss 0.4503467942542932
MCC 0.8992253204453801
AUC 0.9621174712317003

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "Model":ml_names,
    "Ablation":abl_names,
    "Accuracy_train":accuracies_train,
    "Accuracy_predict":accuracies_predict,
    "Loss":loss_predict,
    "Time_train":times_train,
    "Time_predict":times_predict,
    "MCC":mccs_predict,
    "AUC":aucpr_predict
})

In [ ]:
df

,Model,Ablation,Accuracy_train,Accuracy_predict,Loss,Time_train,Time_predict,MCC,AUC
0,KNN,problemall,0.995680,0.900407,0.990080,0.006368,5.087431,0.874524,0.951544
1,KNN,problem_gries,0.992122,0.894309,1.061069,0.004771,3.989551,0.866496,0.944327
2,KNN,code_gries,0.995426,0.900407,0.959353,0.004988,4.023134,0.874524,0.951783
3,KNN,gries,0.991105,0.896341,0.999062,0.004053,3.061593,0.868907,0.945153
4,KNN,problem_code,0.995172,0.899390,1.087104,0.003142,1.995194,0.873741,0.943620
5,KNN,code,0.995426,0.901423,1.040223,0.001751,0.999232,0.876112,0.948283
6,SVM,problemall,0.995172,0.939024,0.263309,134.778715,7.578310,0.922671,0.958902
7,SVM,problem_gries,0.991105,0.925813,0.294671,86.281680,6.228316,0.905763,0.956484
8,SVM,code_gries,0.994917,0.943089,0.256628,86.819225,6.569305,0.927824,0.960433
9,SVM,gries,0.989327,0.923780,0.293568,52.342694,4.118089,0.903145,0.957890
10,SVM,problem_code,0.988818,0.911585,0.349186,35.009496,4.308959,0.887957,0.948140
11,SVM,code,0.985006,0.911585,0.366672,16.298671,1.161547,0.887747,0.944392
12,MLP,problemall,0.981194,0.924797,0.349886,19.226512,0.029025,0.904517,0.958806
13,MLP,problem_gries,0.977382,0.917683,0.411167,13.698492,0.023787,0.895606,0.959857
14,MLP,code_gries,0.988310,0.933943,0.415511,18.747298,0.023566,0.916427,0.955283
15,MLP,gries,0.973062,0.904472,0.379805,11.469443,0.018743,0.879035,0.957469
16,MLP,problem_code,0.968996,0.888211,0.546202,11.353462,0.014165,0.858623,0.944576
17,MLP,code,0.972046,0.907520,0.456863,5.378038,0.007616,0.883170,0.952474
18,Random Forest,problemall,0.994155,0.933943,0.380960,9.371697,0.022302,0.916083,0.967333
19,Random Forest,problem_gries,0.990343,0.917683,0.394017,7.174493,0.021836,0.895376,0.960919
20,Random Forest,code_gries,0.994663,0.927846,0.382092,9.256532,0.025126,0.908397,0.968576
21,Random Forest,gries,0.989072,0.920732,0.390814,6.993985,0.020505,0.899215,0.956051
22,Random Forest,problem_code,0.995680,0.930894,0.464110,6.131774,0.022343,0.912226,0.959621
23,Random Forest,code,0.995426,0.920732,0.450347,6.299091,0.022080,0.899225,0.962117
24,Voting,problemall,0.988056,0.917683,0.289832,21.467621,0.059708,0.895570,0.965291
25,Voting,problem_gries,0.985260,0.924797,0.298639,22.687917,0.049333,0.904798,0.960816
26,Voting,code_gries,0.991360,0.929878,0.270337,18.388629,0.046824,0.910974,0.973850
27,Voting,gries,0.985769,0.924797,0.293648,18.647189,0.041337,0.904564,0.959558
28,Voting,problem_code,0.987548,0.907520,0.359680,12.782745,0.038049,0.882989,0.960093
29,Voting,code,0.993647,0.935976,0.313207,13.210489,0.061367,0.918786,0.969247
30,Stacking,problemall,0.992630,0.929878,0.234758,133.558836,0.054969,0.910974,0.970517
31,Stacking,problem_gries,0.990851,0.926829,0.240903,119.991588,0.046677,0.907108,0.971363
32,Stacking,code_gries,0.993901,0.933943,0.227273,111.720418,0.051657,0.916169,0.977256
33,Stacking,gries,0.990597,0.929878,0.245302,95.042710,0.041918,0.910934,0.967449
34,Stacking,problem_code,0.993901,0.930894,0.260417,91.865022,0.037976,0.912314,0.964060
35,Stacking,code,0.993901,0.928862,0.250475,65.868880,0.032152,0.909738,0.979067

In [ ]:
path="/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/1. Tradicional Machine Learning/"

In [ ]:
df.to_csv(path+"graphtradicionalML_ablationsResults.csv",index=False)

In [ ]:
df=pd.read_csv(path+"graphtradicionalML_ablationsResults.csv")
df

,Model,Ablation,Accuracy_train,Accuracy_predict,Loss,Time_train,Time_predict,MCC,AUC
0,KNN,problemall,0.995680,0.900407,0.990080,0.006368,5.087431,0.874524,0.951544
1,KNN,problem_gries,0.992122,0.894309,1.061069,0.004771,3.989551,0.866496,0.944327
2,KNN,code_gries,0.995426,0.900407,0.959353,0.004988,4.023134,0.874524,0.951783
3,KNN,gries,0.991105,0.896341,0.999062,0.004053,3.061593,0.868907,0.945153
4,KNN,problem_code,0.995172,0.899390,1.087104,0.003142,1.995194,0.873741,0.943620
5,KNN,code,0.995426,0.901423,1.040223,0.001751,0.999232,0.876112,0.948283
6,SVM,problemall,0.995172,0.939024,0.263309,134.778715,7.578310,0.922671,0.958902
7,SVM,problem_gries,0.991105,0.925813,0.294671,86.281680,6.228316,0.905763,0.956484
8,SVM,code_gries,0.994917,0.943089,0.256628,86.819225,6.569305,0.927824,0.960433
9,SVM,gries,0.989327,0.923780,0.293568,52.342694,4.118089,0.903145,0.957890
10,SVM,problem_code,0.988818,0.911585,0.349186,35.009496,4.308959,0.887957,0.948140
11,SVM,code,0.985006,0.911585,0.366672,16.298671,1.161547,0.887747,0.944392
12,MLP,problemall,0.981194,0.924797,0.349886,19.226512,0.029025,0.904517,0.958806
13,MLP,problem_gries,0.977382,0.917683,0.411167,13.698492,0.023787,0.895606,0.959857
14,MLP,code_gries,0.988310,0.933943,0.415511,18.747298,0.023566,0.916427,0.955283
15,MLP,gries,0.973062,0.904472,0.379805,11.469443,0.018743,0.879035,0.957469
16,MLP,problem_code,0.968996,0.888211,0.546202,11.353462,0.014165,0.858623,0.944576
17,MLP,code,0.972046,0.907520,0.456863,5.378038,0.007616,0.883170,0.952474
18,Random Forest,problemall,0.994155,0.933943,0.380960,9.371697,0.022302,0.916083,0.967333
19,Random Forest,problem_gries,0.990343,0.917683,0.394017,7.174493,0.021836,0.895376,0.960919
20,Random Forest,code_gries,0.994663,0.927846,0.382092,9.256532,0.025126,0.908397,0.968576
21,Random Forest,gries,0.989072,0.920732,0.390814,6.993985,0.020505,0.899215,0.956051
22,Random Forest,problem_code,0.995680,0.930894,0.464110,6.131774,0.022343,0.912226,0.959621
23,Random Forest,code,0.995426,0.920732,0.450347,6.299091,0.022080,0.899225,0.962117
24,Voting,problemall,0.988056,0.917683,0.289832,21.467621,0.059708,0.895570,0.965291
25,Voting,problem_gries,0.985260,0.924797,0.298639,22.687917,0.049333,0.904798,0.960816
26,Voting,code_gries,0.991360,0.929878,0.270337,18.388629,0.046824,0.910974,0.973850
27,Voting,gries,0.985769,0.924797,0.293648,18.647189,0.041337,0.904564,0.959558
28,Voting,problem_code,0.987548,0.907520,0.359680,12.782745,0.038049,0.882989,0.960093
29,Voting,code,0.993647,0.935976,0.313207,13.210489,0.061367,0.918786,0.969247
30,Stacking,problemall,0.992630,0.929878,0.234758,133.558836,0.054969,0.910974,0.970517
31,Stacking,problem_gries,0.990851,0.926829,0.240903,119.991588,0.046677,0.907108,0.971363
32,Stacking,code_gries,0.993901,0.933943,0.227273,111.720418,0.051657,0.916169,0.977256
33,Stacking,gries,0.990597,0.929878,0.245302,95.042710,0.041918,0.910934,0.967449
34,Stacking,problem_code,0.993901,0.930894,0.260417,91.865022,0.037976,0.912314,0.964060
35,Stacking,code,0.993901,0.928862,0.250475,65.868880,0.032152,0.909738,0.979067

# Externd Data

In [ ]:
extern_file = '/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/Tuning/BestModels/Copia de ExternData.csv'
train_full = pd.read_csv(extern_file)
train_full

,Problem Description,Python Code,Source,Description Error,Error Label
0,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2
1,Sum numbers from 1 to n,def sum_to_n_buggy(n):\n total = 0\n i =...,Based on typical mistakes in Codeforces common...,i is incorrectly incremented,2
2,Prompt user for numbers until 0 is entered,def input_until_zero_buggy():\n num = int(i...,Common error from GeeksforGeeks Python while l...,number is never updated in the loop,2
3,Find first multiple of 7 greater than n,def first_multiple_7_buggy(n):\n i = n + 1\...,Typical error in CodeNet beginner loop problems,i not incremented,2
4,Calculate factorial of n,def factorial_buggy(n):\n result = 1\n w...,Inspired by classic factorial exercises,"decrement by 2, not 1",2
5,Count digits in a positive integer n,def count_digits_buggy(n):\n count = 0\n ...,Inspired by digit counting problems in Codefor...,n not updated inside the loop,2
6,Sum all even numbers up to n,def sum_evens_buggy(n):\n total = 0\n i ...,"CodeChef/Codeforces summing problems, conditio...",loop condition incorrect,1
7,Find a prime number using break,def find_prime_buggy():\n num = 2\n whil...,Inspired by break/continue loop errors from Py...,break outside the if block,2
8,Print cubes of numbers from 1 to n,def print_cubes_buggy(n):\n while i <= n:\n...,"Common initialization error, based on CodeNet ...",i not initialized,0
9,Prompt for password until correct,def prompt_password_buggy():\n password = i...,Typical validation loop error from Python begi...,password requested only once,2
10,"Print numbers from 1 to n, but condition exclu...",def print_numbers_buggy(n):\n i = 1\n wh...,Common inclusive/exclusive error in loops (Cod...,condition excludes n,1
11,Divide a number by 2 repeatedly until it's les...,def divide_repeatedly_buggy(n):\n while n >...,Inspired by CodeNet loop problems involving di...,integer division and missing update,2
12,Sum all digits of n,def sum_digits_buggy(n):\n total = 0\n w...,"Classic digit-processing error, Python/Codeforces",missing update of n,2
13,Count how many times 5 can be subtracted from n,def count_subtract_5_buggy(n):\n count = 0\...,Common mistake in decrement loops (CodeNet/Cod...,n is not updated,2
14,Calculate power using while loop,"def power_buggy(base, exp):\n result = 1\n ...",Power calculation errors in Codeforces/Python ...,missing increment of i,2
15,Check if number is perfect,def is_perfect_buggy(n):\n sum_div = 0\n ...,"Perfect number mistakes, classic math loops",sum calculation and missing increment,2
16,Convert decimal to binary,def decimal_to_binary_buggy(n):\n res = ''\...,"Typical binary conversion loop, Codeforces/Cod...",n not updated inside the loop,2
17,Print items in list until negative is found,def print_until_negative_buggy(lst):\n i = ...,Inspired by control-flow misplacement from Pyt...,break outside the if block,2
18,Count multiples of 3 up to n,def count_mult_3_buggy(n):\n i = 1\n cou...,"Loops with missed accumulation, typical in beg...",count never updated,2
19,Print odd numbers up to n,def print_odds_buggy(n):\n i = 1\n while...,"Increment logic error, Codeforces/CodeChef",i is incremented incorrectly,2
20,Sum the first n natural numbers,def sum_n_buggy(n):\n i = 1\n total = 0\...,"Classic off-by-one loop error, inspired by bas...",loop condition excludes n,1
21,Sum odd numbers up to n,def sum_odds_buggy(n):\n total = 0\n i =...,"Odd number sum, increment bug, beginner mistakes",i increment incorrect,2
22,Count primes up to n,def count_primes_buggy(n):\n count = 0\n ...,Classic loop and condition error in prime coun...,loop condition excludes n,1
23,Read and sum numbers until a negative is entered,def sum_until_negative_buggy():\n total = 0...,"Missing input update bug, shown in tutorials (...",does not read new number inside loop,2
24,Find LCM of two numbers,"def lcm_buggy(a, b):\n num = max(a, b)\n ...","LCM calculation, common loop bug (CodeNet/Code...",missing increment of candidate,2
25,Print Fibonacci sequence up to n terms,"def fibonacci_buggy(n):\n a, b = 0, 1\n ...","Sequence and assignment bug, inspired by class...",assignments out of order,2
26,Count multiples of 5 up to n,def count_mult_5_buggy(n):\n i = 1\n cou...,"Missing i update, common beginner error, CodeC...",i not updated,2
27,Find GCD of two numbers using Euclid algorithm,"def gcd_buggy(a, b):\n while a != b:\n ...","Euclid's algorithm off-by-one/condition bug, C...",condition may cause infinite loop,1
28,Prompt user for positive numbers until 5 are e...,def count_positives_buggy():\n count = 0\n ...,"Input accumulation/counting error, basic progr...",counter never incremented,2
29,Sum multiples of 4 between 1 and n,def sum_mult_4_buggy(n):\n i = 1\n while...,"Sum variable scope bug, inspired by sum/accumu...",sum variable is reset inside the loop,2
30,"Print the factorial of n, but n is not initial...",def buggy_factorial():\n while n > 0:\n ...,Initialization errors are a classic mistake (C...,n is not initialized before the while loop,0
31,Reverse a list but forget to initialize the in...,def buggy_reverse(lst):\n # missing i = len...,"Initialization and condition errors, common in...",missing initialization and undefined variable ...,3
32,"Print numbers from a to b, missing both variab...",def buggy_print_range(b):\n # missing a = 1...,Initialization and update errors frequently se...,missing initialization and wrong update in loo...,4
33,"Sum even numbers in a list, with an off-by-one...",def buggy_sum_evens(lst):\n i = 0\n sum_...,"Condition and update errors, drawn from typica...",wrong condition and no accumulation in loop body,5
34,"Count numbers divisible by 3, fails to initial...",def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6

In [ ]:
train_full['Python Code']=train_full['Python Code'].apply(lambda x: x.replace("\\n","\n"))

In [ ]:
train_full[["Estado incial","Transformación de estado","Estado final"]]=train_full['Python Code'].apply(DGries_states).apply(pd.Series)

OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body

In [ ]:
train_full

,Problem Description,Python Code,Source,Description Error,Error Label,Estado incial,Transformación de estado,Estado final
0,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,i = 0\n count = 0,if i % 2 == 0:\n count += 1,i <= n
1,Sum numbers from 1 to n,def sum_to_n_buggy(n):\n total = 0\n i =...,Based on typical mistakes in Codeforces common...,i is incorrectly incremented,2,total = 0\n i = 1,total += i\ni = i + 0,i <= n
2,Prompt user for numbers until 0 is entered,def input_until_zero_buggy():\n num = int(i...,Common error from GeeksforGeeks Python while l...,number is never updated in the loop,2,num = int(input('Enter number (0 to exit): ')),"print('Number:', num)",num != 0
3,Find first multiple of 7 greater than n,def first_multiple_7_buggy(n):\n i = n + 1\...,Typical error in CodeNet beginner loop problems,i not incremented,2,i = n + 1,pass,i % 7 != 0
4,Calculate factorial of n,def factorial_buggy(n):\n result = 1\n w...,Inspired by classic factorial exercises,"decrement by 2, not 1",2,result = 1,result *= n\nn -= 2,n > 1
5,Count digits in a positive integer n,def count_digits_buggy(n):\n count = 0\n ...,Inspired by digit counting problems in Codefor...,n not updated inside the loop,2,count = 0,n % 10\ncount += 1,n > 0
6,Sum all even numbers up to n,def sum_evens_buggy(n):\n total = 0\n i ...,"CodeChef/Codeforces summing problems, conditio...",loop condition incorrect,1,total = 0\n i = 2,total += i\ni += 2,i < n
7,Find a prime number using break,def find_prime_buggy():\n num = 2\n whil...,Inspired by break/continue loop errors from Py...,break outside the if block,2,num = 2,is_prime = True\ndivisor = 2\nwhile divisor < ...,True
8,Print cubes of numbers from 1 to n,def print_cubes_buggy(n):\n while i <= n:\n...,"Common initialization error, based on CodeNet ...",i not initialized,0,print(i ** 3)\ni += 1,print(i ** 3)\ni += 1,i <= n
9,Prompt for password until correct,def prompt_password_buggy():\n password = i...,Typical validation loop error from Python begi...,password requested only once,2,password = input('Enter password: '),print('Incorrect'),password != 'secret'
10,"Print numbers from 1 to n, but condition exclu...",def print_numbers_buggy(n):\n i = 1\n wh...,Common inclusive/exclusive error in loops (Cod...,condition excludes n,1,i = 1,print(i)\ni += 1,i < n
11,Divide a number by 2 repeatedly until it's les...,def divide_repeatedly_buggy(n):\n while n >...,Inspired by CodeNet loop problems involving di...,integer division and missing update,2,print(n)\nn = n // 2,print(n)\nn = n // 2,n >= 1
12,Sum all digits of n,def sum_digits_buggy(n):\n total = 0\n w...,"Classic digit-processing error, Python/Codeforces",missing update of n,2,total = 0,total += n % 10,n > 0
13,Count how many times 5 can be subtracted from n,def count_subtract_5_buggy(n):\n count = 0\...,Common mistake in decrement loops (CodeNet/Cod...,n is not updated,2,count = 0,count += 1,n >= 5
14,Calculate power using while loop,"def power_buggy(base, exp):\n result = 1\n ...",Power calculation errors in Codeforces/Python ...,missing increment of i,2,result = 1\n i = 0,result *= base,i < exp
15,Check if number is perfect,def is_perfect_buggy(n):\n sum_div = 0\n ...,"Perfect number mistakes, classic math loops",sum calculation and missing increment,2,sum_div = 0\n divisor = 1,if n % divisor == 0:\n sum_div = divisor,divisor < n
16,Convert decimal to binary,def decimal_to_binary_buggy(n):\n res = ''\...,"Typical binary conversion loop, Codeforces/Cod...",n not updated inside the loop,2,res = '',res = str(n % 2) + res,n > 0
17,Print items in list until negative is found,def print_until_negative_buggy(lst):\n i = ...,Inspired by control-flow misplacement from Pyt...,break outside the if block,2,i = 0,print(lst[i])\nbreak\nif lst[i] < 0:\n brea...,i < len(lst)
18,Count multiples of 3 up to n,def count_mult_3_buggy(n):\n i = 1\n cou...,"Loops with missed accumulation, typical in beg...",count never updated,2,i = 1\n count = 0,if i % 3 == 0:\n pass\ni += 1,i <= n
19,Print odd numbers up to n,def print_odds_buggy(n):\n i = 1\n while...,"Increment logic error, Codeforces/CodeChef",i is incremented incorrectly,2,i = 1,print(i)\ni += 2\ni += 1,i <= n
20,Sum the first n natural numbers,def sum_n_buggy(n):\n i = 1\n total = 0\...,"Classic off-by-one loop error, inspired by bas...",loop condition excludes n,1,i = 1\n total = 0,total += i\ni += 1,i < n
21,Sum odd numbers up to n,def sum_odds_buggy(n):\n total = 0\n i =...,"Odd number sum, increment bug, beginner mistakes",i increment incorrect,2,total = 0\n i = 1,if i % 2 != 0:\n total += i\ni = i + 1 - 1,i <= n
22,Count primes up to n,def count_primes_buggy(n):\n count = 0\n ...,Classic loop and condition error in prime coun...,loop condition excludes n,1,count = 0\n i = 2,if is_prime(i):\n count += 1\ni += 1,i < n
23,Read and sum numbers until a negative is entered,def sum_until_negative_buggy():\n total = 0...,"Missing input update bug, shown in tutorials (...",does not read new number inside loop,2,total = 0\n num = int(input('Enter number (...,total += num,num >= 0
24,Find LCM of two numbers,"def lcm_buggy(a, b):\n num = max(a, b)\n ...","LCM calculation, common loop bug (CodeNet/Code...",missing increment of candidate,2,"num = max(a, b)",if num % a == 0 and num % b == 0:\n return num,True
25,Print Fibonacci sequence up to n terms,"def fibonacci_buggy(n):\n a, b = 0, 1\n ...","Sequence and assignment bug, inspired by class...",assignments out of order,2,"a, b = 0, 1\n i = 0",print(a)\nb = a + b\na = b\ni += 1,i < n
26,Count multiples of 5 up to n,def count_mult_5_buggy(n):\n i = 1\n cou...,"Missing i update, common beginner error, CodeC...",i not updated,2,i = 1\n count = 0,if i % 5 == 0:\n count += 1,i <= n
27,Find GCD of two numbers using Euclid algorithm,"def gcd_buggy(a, b):\n while a != b:\n ...","Euclid's algorithm off-by-one/condition bug, C...",condition may cause infinite loop,1,if a > b:\n a -= b\nelse:\n b -= a,if a > b:\n a -= b\nelse:\n b -= a,a != b
28,Prompt user for positive numbers until 5 are e...,def count_positives_buggy():\n count = 0\n ...,"Input accumulation/counting error, basic progr...",counter never incremented,2,count = 0,num = int(input('Enter positive number: '))\ni...,count < 5
29,Sum multiples of 4 between 1 and n,def sum_mult_4_buggy(n):\n i = 1\n while...,"Sum variable scope bug, inspired by sum/accumu...",sum variable is reset inside the loop,2,i = 1,sum = 0\nif i % 4 == 0:\n sum += i\ni += 1,i <= n
30,"Print the factorial of n, but n is not initial...",def buggy_factorial():\n while n > 0:\n ...,Initialization errors are a classic mistake (C...,n is not initialized before the while loop,0,print(n)\nn -= 1,print(n)\nn -= 1,n > 0
31,Reverse a list but forget to initialize the in...,def buggy_reverse(lst):\n # missing i = len...,"Initialization and condition errors, common in...",missing initialization and undefined variable ...,3,print(lst[j])\nj -= 1,print(lst[j])\nj -= 1,j >= 0
32,"Print numbers from a to b, missing both variab...",def buggy_print_range(b):\n # missing a = 1...,Initialization and update errors frequently se...,missing initialization and wrong update in loo...,4,a = 1\nprint(a)\na += 1,a = 1\nprint(a)\na += 1,a <= b
33,"Sum even numbers in a list, with an off-by-one...",def buggy_sum_evens(lst):\n i = 0\n sum_...,"Condition and update errors, drawn from typica...",wrong condition and no accumulation in loop body,5,i = 0\n sum_evens = 0,if lst[i] % 2 == 0:\n pass\ni += 1,i <= len(lst)
34,"Count numbers divisible by 3, fails to initial...",def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,count = 0\nif i % 3 == 0:\n pass\ni += 1,count = 0\nif i % 3 == 0:\n pass\ni += 1,i < n

In [ ]:
train_full['Python Code']=train_full['Python Code'].apply(lambda x: x.replace("\\n","\n"))

In [ ]:
train_full[["Estado incial","Transformación de estado","Estado final"]]=train_full['Python Code'].apply(DGries_states).apply(pd.Series)

OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body

In [ ]:
%%time
problem=train_full['Problem Description'].apply(encoder.tokenize_and_generate_embeddings_descriptions).to_numpy()
code=train_full['Python Code'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
startstate = train_full['Estado incial'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
finalstate = train_full['Estado final'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
transstate = train_full['Transformación de estado'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()

CPU times: user 1.44 s, sys: 3 µs, total: 1.44 s
Wall time: 1.44 s

In [ ]:
problem.shape,code.shape,startstate.shape,finalstate.shape,transstate.shape

((35,), (35,), (35,), (35,), (35,))

In [ ]:
print(startstate.shape)
print(startstate[0].shape)

(35,)
(1, 12, 768)

In [ ]:
Xp=np.array([sentence[0].mean(axis=0) for sentence in problem])
Xcode=np.array([sentence[0].mean(axis=0) for sentence in code])
Xs=np.array([sentence[0].mean(axis=0) for sentence in startstate])
Xf=np.array([sentence[0].mean(axis=0) for sentence in finalstate])
Xt=np.array([sentence[0].mean(axis=0) for sentence in transstate])
Xp.shape,Xs.shape,Xf.shape,Xt.shape

((35, 768), (35, 768), (35, 768), (35, 768))

In [ ]:
y=train_full['Error Label']+1
y=y.to_numpy()
np.unique(y)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
accuracies_predict=[]
loss_predict=[]
times_predict=[]
mccs_predict=[]
aucpr_predict=[]
ml_names=[]
abl_names=[]

ml_names=[]
abl_names=[]

In [ ]:
from time import time


models_names=["KNN","SVM","MLP","Random Forest","Voting","Stacking"]
ablations_names=["problemall","problem_gries","code_gries","gries","problem_code","code"]

for name in models_names:
  print(name)
  for ablations_name in ablations_names:
    ml_names.append(name)
    abl_names.append(ablations_name)
    print(ablations_name)
    model=joblib.load(path+"graph_"+name+"_"+ablations_name+".joblib")
    print(model)
    if ablations_name=="problemall":
      Xe= np.concatenate((Xp,Xcode,Xs,Xt,Xf),axis=1)
    elif ablations_name=="problem_gries":
      Xe=np.concatenate((Xp,Xs,Xt,Xf),axis=1)
    elif ablations_name=="code_gries":
      Xe=np.concatenate((Xcode,Xs,Xt,Xf),axis=1)
    elif ablations_name=="gries":
      Xe=np.concatenate((Xs,Xt,Xf),axis=1)
    elif ablations_name=="problem_code":
      Xe=np.concatenate((Xp,Xcode),axis=1)
    elif ablations_name=="code":
      Xe=Xcode

    time1=time()
    y_pred=model.predict(Xe)
    time2=time()
    times_predict.append(time2-time1)

    accuracie_test=model.score(Xe,y)
    accuracies_predict.append(accuracie_test)
    #sparse_categorical_crossentropy
    y_pred_proba = model.predict_proba(Xe)
    loss=np.mean(sparse_categorical_crossentropy(y,y_pred_proba))
    loss_predict.append(loss)
    mcc = matthews_corrcoef(y, y_pred)
    mccs_predict.append(mcc)
    auc_pr = calculate_auc_pr_multiclass(y, y_pred_proba)
    aucpr_predict.append(auc_pr)
    print(classification_report(y,y_pred))
    print("Accuracy predict",accuracie_test)
    print("Loss",loss)
    print("MCC",mcc)
    print("AUC",auc_pr)
    print("==================================")

KNN
problemall
KNeighborsClassifier(n_neighbors=3, p=1, weights='distance')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.20      0.20      0.20         5
           3       0.75      0.12      0.21        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.11        35
   macro avg       0.12      0.04      0.05        35
weighted avg       0.54      0.11      0.18        35

Accuracy predict 0.11428571428571428
Loss 12.583647273350799
MCC 0.007026575862457513
AUC 0.2609902033730158
==================================
problem_gries
KNeighborsClassifier(n_neighbors=3, p=1, weights='distance')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.20      0.20      0.20         5
           3       0.83      0.21      0.33        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.17        35
   macro avg       0.13      0.05      0.07        35
weighted avg       0.60      0.17      0.26        35

Accuracy predict 0.17142857142857143
Loss 12.531909572004695
MCC 0.032708842027137225
AUC 0.329060226521164
==================================
code_gries
KNeighborsClassifier(n_neighbors=3, p=1, weights='distance')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.17      0.50      0.25         2
           2       0.20      0.20      0.20         5
           3       0.75      0.12      0.21        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.14        35
   macro avg       0.14      0.10      0.08        35
weighted avg       0.55      0.14      0.19        35

Accuracy predict 0.14285714285714285
Loss 12.56556897786739
MCC 0.058922644159768986
AUC 0.3271205357142857
==================================
gries
KNeighborsClassifier(n_neighbors=3, p=1, weights='distance')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.20      0.20      0.20         5
           3       0.80      0.17      0.28        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.14        35
   macro avg       0.12      0.05      0.06        35
weighted avg       0.58      0.14      0.22        35

Accuracy predict 0.14285714285714285
Loss 12.5537449551987
MCC 0.02400746823186455
AUC 0.3305059523809523
==================================
problem_code
KNeighborsClassifier(n_neighbors=3, p=1, weights='distance')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         5
           3       0.75      0.12      0.21        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.09        35
   macro avg       0.09      0.02      0.03        35
weighted avg       0.51      0.09      0.15        35

Accuracy predict 0.08571428571428572
Loss 13.472438796733062
MCC -0.026805666403405017
AUC 0.3007750496031746
==================================
code
KNeighborsClassifier(n_neighbors=3, p=1, weights='distance')
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.20      0.20      0.20         5
           3       1.00      0.17      0.29        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.14        35
   macro avg       0.15      0.05      0.06        35
weighted avg       0.71      0.14      0.22        35

Accuracy predict 0.14285714285714285
Loss 11.705481749240313
MCC 0.05997943914497855
AUC 0.29943989748677247
==================================
SVM
problemall
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=233.57214690901213, gamma=0.000379269019073225,
                     probability=True))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.67      0.40      0.50         5
           3       1.00      0.29      0.45        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.26        35
   macro avg       0.21      0.09      0.12        35
weighted avg       0.78      0.26      0.38        35

Accuracy predict 0.2571428571428571
Loss 1.7916661003731797
MCC 0.2284461965842071
AUC 0.28601386645903865
==================================
problem_gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=233.57214690901213, gamma=0.000379269019073225,
                     probability=True))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.57      0.80      0.67         5
           3       1.00      0.25      0.40        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.29        35
   macro avg       0.20      0.13      0.13        35
weighted avg       0.77      0.29      0.37        35

Accuracy predict 0.2857142857142857
Loss 1.6704295157555131
MCC 0.26900096292600073
AUC 0.2983405704846534
==================================
code_gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=233.57214690901213, gamma=0.000379269019073225,
                     probability=True))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.17      0.20      0.18         5
           3       0.80      0.33      0.47        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.26        35
   macro avg       0.12      0.07      0.08        35
weighted avg       0.57      0.26      0.35        35

Accuracy predict 0.2571428571428571
Loss 1.8890342523532735
MCC 0.05239191890414813
AUC 0.24588367529774027
==================================
gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=233.57214690901213, gamma=0.000379269019073225,
                     probability=True))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.29      0.40      0.33         5
           3       0.86      0.25      0.39        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.23        35
   macro avg       0.14      0.08      0.09        35
weighted avg       0.63      0.23      0.31        35

Accuracy predict 0.22857142857142856
Loss 2.098319049734931
MCC 0.10398902601941963
AUC 0.24937027254682725
==================================
problem_code
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=233.57214690901213, gamma=0.000379269019073225,
                     probability=True))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         5
           3       0.72      0.96      0.82        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.66        35
   macro avg       0.09      0.12      0.10        35
weighted avg       0.49      0.66      0.56        35

Accuracy predict 0.6571428571428571
Loss 1.3615471696529922
MCC 0.07770435724530453
AUC 0.24446189726847983
==================================
code
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=233.57214690901213, gamma=0.000379269019073225,
                     probability=True))])
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.09      0.50      0.15         2
           2       0.43      0.60      0.50         5
           3       0.75      0.25      0.38        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.29        35
   macro avg       0.16      0.17      0.13        35
weighted avg       0.58      0.29      0.34        35

Accuracy predict 0.2857142857142857
Loss 1.881945943446883
MCC 0.13023970964230708
AUC 0.2913057722238726
==================================
MLP
problemall
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.10      0.50      0.17         2
           2       0.25      0.20      0.22         5
           3       0.86      0.25      0.39        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.23        35
   macro avg       0.15      0.12      0.10        35
weighted avg       0.63      0.23      0.31        35

Accuracy predict 0.22857142857142856
Loss 5.5266128
MCC 0.08703559659814526
AUC 0.2321849511554178
==================================
problem_gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.20      0.40      0.27         5
           3       0.82      0.38      0.51        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.31        35
   macro avg       0.13      0.10      0.10        35
weighted avg       0.59      0.31      0.39        35

Accuracy predict 0.3142857142857143
Loss 5.36553
MCC 0.06965007472819787
AUC 0.34072312302689567
==================================
code_gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.17      0.50      0.25         2
           2       0.20      0.20      0.20         5
           3       0.85      0.46      0.59        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.37        35
   macro avg       0.15      0.14      0.13        35
weighted avg       0.62      0.37      0.45        35

Accuracy predict 0.37142857142857144
Loss 5.090208
MCC 0.13875401668929802
AUC 0.3586027420099619
==================================
gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.25      0.20      0.22         5
           3       0.91      0.42      0.57        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.31        35
   macro avg       0.14      0.08      0.10        35
weighted avg       0.66      0.31      0.42        35

Accuracy predict 0.3142857142857143
Loss 6.7403526
MCC 0.11658553803785897
AUC 0.23219041325834772
==================================
problem_code
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.20      0.50      0.29         2
           2       0.24      0.80      0.36         5
           3       0.86      0.25      0.39        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.31        35
   macro avg       0.16      0.19      0.13        35
weighted avg       0.63      0.31      0.33        35

Accuracy predict 0.3142857142857143
Loss 5.691837
MCC 0.1650385434072771
AUC 0.24793158579385785
==================================
code
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.25      0.40      0.31         5
           3       0.86      0.25      0.39        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.25      1.00      0.40         1
           7       0.00      0.00      0.00         1

    accuracy                           0.26        35
   macro avg       0.17      0.21      0.14        35
weighted avg       0.63      0.26      0.32        35

Accuracy predict 0.2571428571428571
Loss 6.494056
MCC 0.11537483351609976
AUC 0.259479212428385
==================================
Random Forest
problemall
RandomForestClassifier(max_depth=15, n_estimators=70)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.60      0.60      0.60         5
           3       1.00      0.17      0.29        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.20        35
   macro avg       0.20      0.10      0.11        35
weighted avg       0.77      0.20      0.28        35

Accuracy predict 0.2
Loss 1.7752792895362044
MCC 0.1794613623484058
AUC 0.27028003978298243
==================================
problem_gries
RandomForestClassifier(max_depth=15, n_estimators=70)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.50      0.40      0.44         5
           3       0.50      0.04      0.08        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.09        35
   macro avg       0.12      0.06      0.07        35
weighted avg       0.41      0.09      0.12        35

Accuracy predict 0.08571428571428572
Loss 1.9875210511106485
MCC 0.04108907018066591
AUC 0.21869391435229668
==================================
code_gries
RandomForestClassifier(max_depth=15, n_estimators=70)

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.50      0.50      0.50         2
           2       0.43      0.60      0.50         5
           3       0.67      0.08      0.15        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.17        35
   macro avg       0.20      0.15      0.14        35
weighted avg       0.55      0.17      0.20        35

Accuracy predict 0.17142857142857143
Loss 1.7805946152924774
MCC 0.15164247801006833
AUC 0.38798391104996055
==================================
gries
RandomForestClassifier(max_depth=15, n_estimators=70)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.29      0.40      0.33         5
           3       1.00      0.08      0.15        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.11        35
   macro avg       0.16      0.06      0.06        35
weighted avg       0.73      0.11      0.15        35

Accuracy predict 0.11428571428571428
Loss 1.9273222469408913
MCC 0.0773686112296267
AUC 0.25765800650079623
==================================
problem_code
RandomForestClassifier(max_depth=15, n_estimators=70)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         5
           3       0.33      0.04      0.07        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.03        35
   macro avg       0.04      0.01      0.01        35
weighted avg       0.23      0.03      0.05        35

Accuracy predict 0.02857142857142857
Loss 1.968315745407211
MCC -0.1075872368273232
AUC 0.21459493853273487
==================================
code
RandomForestClassifier(max_depth=15, n_estimators=70)
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         5
           3       0.60      0.12      0.21        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.09        35
   macro avg       0.07      0.02      0.03        35
weighted avg       0.41      0.09      0.14        35

Accuracy predict 0.08571428571428572
Loss 1.8730635656753554
MCC -0.036200706965373766
AUC 0.22651368892010076
==================================
Voting
problemall

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=70))],
                 voting='soft')
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.14      0.20      0.17         5
           3       0.62      0.21      0.31        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.17        35
   macro avg       0.10      0.05      0.06        35
weighted avg       0.45      0.17      0.24        35

Accuracy predict 0.17142857142857143
Loss 2.120112272017842
MCC -0.04846497241573919
AUC 0.24364005680586048
==================================
problem_gries

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=70))],
                 voting='soft')
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.25      0.40      0.31         5
           3       0.57      0.17      0.26        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.17        35
   macro avg       0.10      0.07      0.07        35
weighted avg       0.43      0.17      0.22        35

Accuracy predict 0.17142857142857143
Loss 2.2847951959419857
MCC -0.024354811499103072
AUC 0.22852295463132247
==================================
code_gries

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=70))],
                 voting='soft')
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.33      0.20      0.25         5
           3       0.67      0.33      0.44        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.26        35
   macro avg       0.12      0.07      0.09        35
weighted avg       0.50      0.26      0.34        35

Accuracy predict 0.2571428571428571
Loss 1.9328753935913963
MCC -0.002659612093013038
AUC 0.25574788558450384
==================================
gries

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=70))],
                 voting='soft')
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.25      0.20      0.22         5
           3       0.75      0.25      0.38        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.20        35
   macro avg       0.12      0.06      0.07        35
weighted avg       0.55      0.20      0.29        35

Accuracy predict 0.2
Loss 2.1452816282836964
MCC 0.023654742360520033
AUC 0.2436570162855735
==================================
problem_code

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=70))],
                 voting='soft')
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.25      0.50      0.33         2
           2       0.33      0.60      0.43         5
           3       0.80      0.50      0.62        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.46        35
   macro avg       0.17      0.20      0.17        35
weighted avg       0.61      0.46      0.50        35

Accuracy predict 0.45714285714285713
Loss 1.7851775593037083
MCC 0.19739020272217248
AUC 0.2261056293607981
==================================
code

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=70))],
                 voting='soft')
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.11      0.20      0.14         5
           3       0.50      0.17      0.25        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.14        35
   macro avg       0.08      0.05      0.05        35
weighted avg       0.36      0.14      0.19        35

Accuracy predict 0.14285714285714285
Loss 2.0978911412598626
MCC -0.09110394612959738
AUC 0.25981950212095684
==================================
Stacking
problemall

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=70))],
                   final_estimator=LogisticRegression())
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.50      0.40      0.44         5
           3       0.86      0.25      0.39        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.23        35
   macro avg       0.17      0.08      0.10        35
weighted avg       0.66      0.23      0.33        35

Accuracy predict 0.22857142857142856
Loss 2.0008930956298743
MCC 0.10399330142645262
AUC 0.2687107093072457
==================================
problem_gries

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=70))],
                   final_estimator=LogisticRegression())
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.43      0.60      0.50         5
           3       1.00      0.21      0.34        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.23        35
   macro avg       0.18      0.10      0.11        35
weighted avg       0.75      0.23      0.31        35

Accuracy predict 0.22857142857142856
Loss 2.2358801912664568
MCC 0.15885882886655933
AUC 0.24231543119511456
==================================
code_gries
StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=70))],
                   final_estimator=LogisticRegression())

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.40      0.40      0.40         5
           3       0.86      0.25      0.39        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.23        35
   macro avg       0.16      0.08      0.10        35
weighted avg       0.64      0.23      0.32        35

Accuracy predict 0.22857142857142856
Loss 2.2551949861870084
MCC 0.09881335454324008
AUC 0.28532675009841
==================================
gries
StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=70))],
                   final_estimator=LogisticRegression())

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         2
           2       0.50      0.40      0.44         5
           3       0.80      0.17      0.28        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.17        35
   macro avg       0.16      0.07      0.09        35
weighted avg       0.62      0.17      0.25        35

Accuracy predict 0.17142857142857143
Loss 2.2546924463112847
MCC 0.07962012158517946
AUC 0.2623595343481502
==================================
problem_code
StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=70))],
                   final_estimator=LogisticRegression())
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.29      1.00      0.44         2
           2       0.29      0.40      0.33         5
           3       0.67      0.17      0.27        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.23        35
   macro avg       0.15      0.20      0.13        35
weighted avg       0.51      0.23      0.26        35

Accuracy predict 0.22857142857142856
Loss 2.0211163668421865
MCC 0.1034105846713105
AUC 0.3010700680315033
==================================
code
StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=70))],
                   final_estimator=LogisticRegression())
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.50      0.50      0.50         2
           2       0.50      0.20      0.29         5
           3       0.80      0.33      0.47        24
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.29        35
   macro avg       0.23      0.13      0.16        35
weighted avg       0.65      0.29      0.39        35

Accuracy predict 0.2857142857142857
Loss 2.128825009187811
MCC 0.12944656935349785
AUC 0.29334439122200767
==================================

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:1033: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import pandas as pd
dfe=pd.DataFrame({
    "Model":ml_names,
    "Ablation":abl_names,
    "Accuracy_predict":accuracies_predict,
    "Loss":loss_predict,
    "Time_predict":times_predict,
    "MCC":mccs_predict,
    "AUC":aucpr_predict
})

In [ ]:
dfe

,Model,Ablation,Accuracy_predict,Loss,Time_predict,MCC,AUC
0,KNN,problemall,0.114286,12.583647,0.205471,0.007027,0.260990
1,KNN,problem_gries,0.171429,12.531910,0.151275,0.032709,0.329060
2,KNN,code_gries,0.142857,12.565569,0.145434,0.058923,0.327121
3,KNN,gries,0.142857,12.553745,0.114011,0.024007,0.330506
4,KNN,problem_code,0.085714,13.472439,0.084205,-0.026806,0.300775
5,KNN,code,0.142857,11.705482,0.042005,0.059979,0.299440
6,SVM,problemall,0.257143,1.791666,0.293558,0.228446,0.286014
7,SVM,problem_gries,0.285714,1.670430,0.226819,0.269001,0.298341
8,SVM,code_gries,0.257143,1.889034,0.212783,0.052392,0.245884
9,SVM,gries,0.228571,2.098319,0.153664,0.103989,0.249370
10,SVM,problem_code,0.657143,1.361547,0.181428,0.077704,0.244462
11,SVM,code,0.285714,1.881946,0.047348,0.130240,0.291306
12,MLP,problemall,0.228571,5.526613,0.053592,0.087036,0.232185
13,MLP,problem_gries,0.314286,5.365530,0.007252,0.069650,0.340723
14,MLP,code_gries,0.371429,5.090208,0.004885,0.138754,0.358603
15,MLP,gries,0.314286,6.740353,0.002907,0.116586,0.232190
16,MLP,problem_code,0.314286,5.691837,0.003322,0.165039,0.247932
17,MLP,code,0.257143,6.494056,0.018676,0.115375,0.259479
18,Random Forest,problemall,0.200000,1.775279,0.007088,0.179461,0.270280
19,Random Forest,problem_gries,0.085714,1.987521,0.005489,0.041089,0.218694
20,Random Forest,code_gries,0.171429,1.780595,0.005958,0.151642,0.387984
21,Random Forest,gries,0.114286,1.927322,0.009431,0.077369,0.257658
22,Random Forest,problem_code,0.028571,1.968316,0.005321,-0.107587,0.214595
23,Random Forest,code,0.085714,1.873064,0.005228,-0.036201,0.226514
24,Voting,problemall,0.171429,2.120112,0.052783,-0.048465,0.243640
25,Voting,problem_gries,0.171429,2.284795,0.100742,-0.024355,0.228523
26,Voting,code_gries,0.257143,1.932875,0.071846,-0.002660,0.255748
27,Voting,gries,0.200000,2.145282,0.034858,0.023655,0.243657
28,Voting,problem_code,0.457143,1.785178,0.023237,0.197390,0.226106
29,Voting,code,0.142857,2.097891,0.033697,-0.091104,0.259820
30,Stacking,problemall,0.228571,2.000893,0.047836,0.103993,0.268711
31,Stacking,problem_gries,0.228571,2.235880,0.042678,0.158859,0.242315
32,Stacking,code_gries,0.228571,2.255195,0.037537,0.098813,0.285327
33,Stacking,gries,0.171429,2.254692,0.055315,0.079620,0.262360
34,Stacking,problem_code,0.228571,2.021116,0.037615,0.103411,0.301070
35,Stacking,code,0.285714,2.128825,0.009136,0.129447,0.293344

In [ ]:
dfe.to_csv(path+"graph_externData_ablationsResults.csv",index=False)

In [ ]:
dfe=pd.read_csv(path+"graph_externData_ablationsResults.csv")
dfe

,Model,Ablation,Accuracy_predict,Loss,Time_predict,MCC,AUC
0,KNN,problemall,0.114286,12.583647,0.205471,0.007027,0.260990
1,KNN,problem_gries,0.171429,12.531910,0.151275,0.032709,0.329060
2,KNN,code_gries,0.142857,12.565569,0.145434,0.058923,0.327121
3,KNN,gries,0.142857,12.553745,0.114011,0.024007,0.330506
4,KNN,problem_code,0.085714,13.472439,0.084205,-0.026806,0.300775
5,KNN,code,0.142857,11.705482,0.042005,0.059979,0.299440
6,SVM,problemall,0.257143,1.791666,0.293558,0.228446,0.286014
7,SVM,problem_gries,0.285714,1.670430,0.226819,0.269001,0.298341
8,SVM,code_gries,0.257143,1.889034,0.212783,0.052392,0.245884
9,SVM,gries,0.228571,2.098319,0.153664,0.103989,0.249370
10,SVM,problem_code,0.657143,1.361547,0.181428,0.077704,0.244462
11,SVM,code,0.285714,1.881946,0.047348,0.130240,0.291306
12,MLP,problemall,0.228571,5.526613,0.053592,0.087036,0.232185
13,MLP,problem_gries,0.314286,5.365530,0.007252,0.069650,0.340723
14,MLP,code_gries,0.371429,5.090208,0.004885,0.138754,0.358603
15,MLP,gries,0.314286,6.740353,0.002907,0.116586,0.232190
16,MLP,problem_code,0.314286,5.691837,0.003322,0.165039,0.247932
17,MLP,code,0.257143,6.494056,0.018676,0.115375,0.259479
18,Random Forest,problemall,0.200000,1.775279,0.007088,0.179461,0.270280
19,Random Forest,problem_gries,0.085714,1.987521,0.005489,0.041089,0.218694
20,Random Forest,code_gries,0.171429,1.780595,0.005958,0.151642,0.387984
21,Random Forest,gries,0.114286,1.927322,0.009431,0.077369,0.257658
22,Random Forest,problem_code,0.028571,1.968316,0.005321,-0.107587,0.214595
23,Random Forest,code,0.085714,1.873064,0.005228,-0.036201,0.226514
24,Voting,problemall,0.171429,2.120112,0.052783,-0.048465,0.243640
25,Voting,problem_gries,0.171429,2.284795,0.100742,-0.024355,0.228523
26,Voting,code_gries,0.257143,1.932875,0.071846,-0.002660,0.255748
27,Voting,gries,0.200000,2.145282,0.034858,0.023655,0.243657
28,Voting,problem_code,0.457143,1.785178,0.023237,0.197390,0.226106
29,Voting,code,0.142857,2.097891,0.033697,-0.091104,0.259820
30,Stacking,problemall,0.228571,2.000893,0.047836,0.103993,0.268711
31,Stacking,problem_gries,0.228571,2.235880,0.042678,0.158859,0.242315
32,Stacking,code_gries,0.228571,2.255195,0.037537,0.098813,0.285327
33,Stacking,gries,0.171429,2.254692,0.055315,0.079620,0.262360
34,Stacking,problem_code,0.228571,2.021116,0.037615,0.103411,0.301070
35,Stacking,code,0.285714,2.128825,0.009136,0.129447,0.293344