In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.56.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.8.3)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import re
import shutil
import string
from sklearn.metrics import classification_report
import tensorflow as tf
from keras.models import Model
from tensorflow.keras import layers
from tensorflow.keras import losses
from tensorflow.keras.optimizers import Adam
from keras.callbacks import EarlyStopping,ModelCheckpoint
from tensorflow.keras.layers import Dense, Input, Dropout, Bidirectional, LSTM, Embedding, BatchNormalization,  Reshape, Conv2D, MaxPool2D, concatenate, Flatten, Activation
import torch
import numpy as np
from transformers import BertTokenizer, BertModel,RobertaTokenizer, RobertaModel,AutoTokenizer, AutoModel
import ast

In [ ]:
# Verificar si la GPU está disponible
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
archivo_3 = '/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/Tuning/BestModels/finallDataset.csv'
train_full = pd.read_csv(archivo_3)

# AST spliter D. Gries form

In [ ]:
class WhileLoopFinder(ast.NodeVisitor):
    def __init__(self, source_code):
        self.source_code = source_code.splitlines()
        self.functions_with_while = []
        self.current_function = None

    def visit_FunctionDef(self, node):
        original_current_function = self.current_function
        self.current_function = {
            "function_name": node.name,
            "has_while_loop": False,
            "pre_while_code_lines": [],
            "while_loops": []
        }

        function_start_line = node.lineno - 1
        function_end_line = (node.end_lineno if hasattr(node, 'end_lineno') else len(self.source_code))
        function_lines = self.source_code[function_start_line:function_end_line]

        found_while = False
        for stmt in node.body:
            if isinstance(stmt, ast.While):
                self.current_function["has_while_loop"] = True
                found_while = True
                try:
                    while_condition = ast.unparse(stmt.test).strip()
                    print("OK condition")
                except AttributeError:
                    print("Error al obtener la condición del while")
                try:
                    while_body_code = ast.unparse(ast.Module(body=stmt.body, type_ignores=[])).strip()
                    print("Ok body")
                except AttributeError:
                    print("Error al obtener el código del cuerpo del while")

                self.current_function["while_loops"].append({
                    "condition": while_condition,
                    "body_code": while_body_code
                })
            elif not found_while:
                start_line = stmt.lineno - 1
                end_line = (stmt.end_lineno if hasattr(stmt, 'end_lineno') else stmt.lineno)
                self.current_function["pre_while_code_lines"].extend(self.source_code[start_line:end_line])
            self.generic_visit(stmt)

        if self.current_function["has_while_loop"]:
            last_while_end_line = None
            if self.current_function["while_loops"]:
                last_while_node = next((node for node in reversed(node.body) if isinstance(node, ast.While)), None)
                if last_while_node and hasattr(last_while_node, 'end_lineno'):
                    last_while_end_line = last_while_node.end_lineno
            post_while_code_lines = []
            if last_while_end_line:
                function_indent = len(self.source_code[node.lineno - 1]) - len(self.source_code[node.lineno - 1].lstrip())
                for line in self.source_code[last_while_end_line:function_end_line]:
                    if line.startswith(self.source_code[node.lineno - 1][:function_indent] + "    "):
                        post_while_code_lines.append(line[function_indent + 4:])
                    else:
                        post_while_code_lines.append(line[function_indent:])
            self.current_function["post_while_code_lines"] = "\n".join(post_while_code_lines).strip()
            self.current_function["pre_while_code_lines"] = "\n".join(self.current_function["pre_while_code_lines"]).strip()
            self.functions_with_while.append(self.current_function)

        self.current_function = original_current_function

In [ ]:
def DGries_states(solution):
  try:
    # Crear el AST
    tree = ast.parse(solution)
    # Recorrer el AST con nuestro visitante
    finder = WhileLoopFinder(solution)
    finder.visit(tree)
    for func_info in finder.functions_with_while:
      initial_state=func_info["pre_while_code_lines"] if func_info["pre_while_code_lines"] else False
      end_state=""
      transformation_state=""
      for j, wl in enumerate(func_info["while_loops"]):
          end_state=wl["condition"]
          transformation_state=wl["body_code"]

      if not initial_state:
        initial_state=transformation_state
      return initial_state,transformation_state,end_state
  except Exception as error:
    return "Exception:"+str(error),"Exception:"+str(error),"Exception:"+str(error)

# Encoder Description and Code

In [ ]:
class Encoder:
  def __init__(self):
    self.is_loadtokenizers=False



  def tokenize_and_generate_embeddings_descriptions(self,description):
    if not self.is_loadtokenizers:
      raise ValueError("tokenizers dont load")
    # Tokenize input description and move tokens to GPU
    tokens = self.beart_tokenizer.encode_plus(description, return_tensors="pt", truncation=True)
    tokens = {key: value.to(device) for key, value in tokens.items()}
    # Generate embeddings
    with torch.no_grad():
        outputs = self.beart_model(**tokens)
    # Extract embeddings for all tokens
    desc_embeddings = outputs.last_hidden_state.cpu().numpy()
    return desc_embeddings

  def tokenize_and_generate_embeddings_codes(self,code):
    if not self.is_loadtokenizers:
      raise ValueError("tokenizers dont load")
    # Tokenize input code and move tokens to GPU
    tokens = self.codebeart_tokenizer.encode_plus(code, return_tensors="pt", truncation=True)
    tokens = {key: value.to(device) for key, value in tokens.items()}
    # Generate embeddings
    with torch.no_grad():
        outputs = self.codebeart_model(**tokens)
    # Extract embeddings for all tokens
    code_embeddings = outputs.last_hidden_state.cpu().numpy()

    return code_embeddings


  def tokenize_and_generate_embeddings_graphcodes(self,code):
    if not self.is_loadtokenizers:
      raise ValueError("tokenizers dont load")
    # Tokenize input code and move tokens to GPU
    tokens = self.graphcodebert_tokenizer.encode_plus(code, return_tensors="pt", truncation=True)
    tokens = {key: value.to(device) for key, value in tokens.items()}
    # Generate embeddings
    with torch.no_grad():
        outputs = self.graphcodebert_model(**tokens)
    # Extract embeddings for all tokens
    code_embeddings = outputs.last_hidden_state.cpu().numpy()
    return code_embeddings

  def load_beart_tokenizer(self):
    # Verificar si la GPU está disponible
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Cargar el tokenizer y el modelo en la GPU si está disponible
    model_name = "bert-base-uncased"
    self.beart_model = BertModel.from_pretrained(model_name)
    self.beart_tokenizer = BertTokenizer.from_pretrained(model_name)
    self.beart_model.to(device)

  def load_graphcodebert_tokenizer(self):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    self.graphcodebert_tokenizer = AutoTokenizer.from_pretrained("microsoft/graphcodebert-base")
    self.graphcodebert_model = AutoModel.from_pretrained("microsoft/graphcodebert-base")
    self.graphcodebert_model.to(device)


  def load_codebert_tokenizer(self):
    # Verificar si la GPU está disponible
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Cargar el tokenizer y el modelo en la GPU si está disponible
    self.codebeart_tokenizer = RobertaTokenizer.from_pretrained("microsoft/codebert-base")
    self.codebeart_model = RobertaModel.from_pretrained("microsoft/codebert-base")
    self.codebeart_model.to(device)

  def start_tokenizer(self):
    self.load_beart_tokenizer()
    #self.load_codebert_tokenizer()
    self.load_graphcodebert_tokenizer()
    self.is_loadtokenizers=True

# All characteristics

In [ ]:
def categoricallabelAll(w):
  if w=="['Correct']":
    return 0
  if w=="['Initial state']":
    return 1
  if w=="['Final state']":
    return 2
  if w=="['State transformation']":
    return 3
  if w=="['Initial state', 'Final state']":
    return 4
  if w=="['Initial state', 'State transformation']":
    return 5
  if w=="['Final state', 'State transformation']":
    return 6
  if w=="['Initial state', 'Final state', 'State transformation']":
    return 7
  return 8

category=np.array([
    'Correct',
    'Initial state',
    'Final state',
    'State transformation',
    'Initial state, Final state',
    'Initial state, State transformation',
    'Final state, State transformation',
    'Initial state, Final state, State transformation'

])

# Load Dataset

In [ ]:
train_full.head()

,Problema,Solución,y
0,Write a Python function that returns the facto...,def factorial(n):\n result = 0\n i = 1\n...,0
1,Write a Python function that returns the sum o...,def sum_1_to_100():\n total = 0\n i = 1\...,0
2,Write a Python function that prints the number...,def print_and_store():\n numbers = []\n ...,0
3,Write a Python function to print the numbers f...,def print_and_store_reverse():\n numbers = ...,0
4,Write a Python function to check if a number i...,def is_prime(num):\n i = 2\n while i < n...,0

In [ ]:
train_full[["Estado incial","Transformación de estado","Estado final"]]=train_full['Solución'].apply(DGries_states).apply(pd.Series)

Streaming output truncated to the last 5000 lines.
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition

In [ ]:
train_full

,Problema,Solución,y,Estado incial,Transformación de estado,Estado final
0,Write a Python function that returns the facto...,def factorial(n):\n result = 0\n i = 1\n...,0,result = 0\n i = 1,result += i\ni += 1,i <= n
1,Write a Python function that returns the sum o...,def sum_1_to_100():\n total = 0\n i = 1\...,0,total = 0\n i = 1,total += i\ni += 2,i < 100
2,Write a Python function that prints the number...,def print_and_store():\n numbers = []\n ...,0,numbers = []\n i = 0,print(i)\nnumbers[i] = i\ni += 1,i < 10
3,Write a Python function to print the numbers f...,def print_and_store_reverse():\n numbers = ...,0,numbers = []\n i = 0,print(10 - i)\nnumbers.append(i)\ni += 1,i < 10
4,Write a Python function to check if a number i...,def is_prime(num):\n i = 2\n while i < n...,0,i = 2,if num % i == 0:\n return False\ni += 1,i < num
...,...,...,...,...,...,...
4130,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n i = 0\n cou...,6,i = 0\n count = 0,if i % 3 == 0:\n count = count + 1\ni = i + 1,i < n
4131,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n i = 0\n cou...,6,i = 0\n count = 0,if i % 3 == 0:\n count += 1\ni += 1,not i >= n
4132,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...,6,count = 0\n i = 0,if not i % 3:\n count += 1\ni += 1,n > i
4133,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...,6,count = 0\n i = 0,if i % 3 == 0 and True:\n count = count + 1...,i != n
4134,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...,6,count = 0\n i = 0,count += int(i % 3 == 0)\ni += 1,i < n

In [ ]:
y=train_full['y'].to_numpy()
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
train_full.dropna(inplace=True)

In [ ]:
train_full

,Problema,Solución,y,Estado incial,Transformación de estado,Estado final
0,Write a Python function that returns the facto...,def factorial(n):\n result = 0\n i = 1\n...,0,result = 0\n i = 1,result += i\ni += 1,i <= n
1,Write a Python function that returns the sum o...,def sum_1_to_100():\n total = 0\n i = 1\...,0,total = 0\n i = 1,total += i\ni += 2,i < 100
2,Write a Python function that prints the number...,def print_and_store():\n numbers = []\n ...,0,numbers = []\n i = 0,print(i)\nnumbers[i] = i\ni += 1,i < 10
3,Write a Python function to print the numbers f...,def print_and_store_reverse():\n numbers = ...,0,numbers = []\n i = 0,print(10 - i)\nnumbers.append(i)\ni += 1,i < 10
4,Write a Python function to check if a number i...,def is_prime(num):\n i = 2\n while i < n...,0,i = 2,if num % i == 0:\n return False\ni += 1,i < num
...,...,...,...,...,...,...
4130,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n i = 0\n cou...,6,i = 0\n count = 0,if i % 3 == 0:\n count = count + 1\ni = i + 1,i < n
4131,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n i = 0\n cou...,6,i = 0\n count = 0,if i % 3 == 0:\n count += 1\ni += 1,not i >= n
4132,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...,6,count = 0\n i = 0,if not i % 3:\n count += 1\ni += 1,n > i
4133,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...,6,count = 0\n i = 0,if i % 3 == 0 and True:\n count = count + 1...,i != n
4134,calculate how many numbers are divisible by 3,def buggy_count_mult_3(n):\n count = 0\n ...,6,count = 0\n i = 0,count += int(i % 3 == 0)\ni += 1,i < n

In [ ]:
encoder=Encoder()
encoder.start_tokenizer()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/539 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at microsoft/graphcodebert-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
%%time
problem=train_full['Problema'].apply(encoder.tokenize_and_generate_embeddings_descriptions).to_numpy()
code=train_full['Solución'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
startstate = train_full['Estado incial'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
finalstate = train_full['Estado final'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
transstate = train_full['Transformación de estado'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

CPU times: user 2min 48s, sys: 2.52 s, total: 2min 50s
Wall time: 2min 48s

In [ ]:
problem.shape,code.shape,startstate.shape,finalstate.shape,transstate.shape

((4094,), (4094,), (4094,), (4094,), (4094,))

In [ ]:
print(startstate.shape)
print(startstate[1262].shape)

(4094,)
(1, 13, 768)

In [ ]:
Xp=np.array([sentence[0].mean(axis=0) for sentence in problem])
Xcode=np.array([sentence[0].mean(axis=0) for sentence in code])
Xs=np.array([sentence[0].mean(axis=0) for sentence in startstate])
Xf=np.array([sentence[0].mean(axis=0) for sentence in finalstate])
Xt=np.array([sentence[0].mean(axis=0) for sentence in transstate])
Xp.shape,Xs.shape,Xf.shape,Xt.shape

((4094, 768), (4094, 768), (4094, 768), (4094, 768))

In [ ]:
y=train_full['y'].to_numpy()
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
y.shape

(4094,)

In [ ]:
from sklearn.model_selection import train_test_split

Xp_train,Xp_test,Xcode_train,Xcode_test,Xs_train,Xs_test,Xt_train,Xt_test,Xf_train,Xf_test,y_train,y_test=train_test_split(Xp,Xcode,Xs,Xt,Xf,y,test_size=0.2,random_state=2023, stratify=y)

In [ ]:
Xp_train.shape,Xp_test.shape,Xcode_train.shape, Xcode_test.shape, Xs_train.shape,Xs_test.shape,Xt_train.shape,Xt_test.shape,Xf_train.shape,Xf_test.shape,y_train.shape,y_test.shape

((3275, 768),
 (819, 768),
 (3275, 768),
 (819, 768),
 (3275, 768),
 (819, 768),
 (3275, 768),
 (819, 768),
 (3275, 768),
 (819, 768),
 (3275,),
 (819,))

In [ ]:
#random search
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import matthews_corrcoef
#XGBoost
from xgboost import XGBClassifier
#pipeline
from sklearn.pipeline import Pipeline
from sklearn.neural_network import MLPClassifier

In [ ]:
from sklearn.metrics import matthews_corrcoef, precision_recall_curve, auc
from sklearn.preprocessing import label_binarize
import numpy as np

def calculate_mcc_multiclass(y_true, y_pred_probs):
    y_pred_labels = np.argmax(y_pred_probs, axis=1)
    # Convertir etiquetas verdaderas one-hot a etiquetas enteras si es necesario
    #y_true_labels = np.argmax(y_true, axis=1) if y_true.ndim > 1 else y_true
    return matthews_corrcoef(y_true, y_pred_labels)

def calculate_auc_pr_multiclass(y_true, y_pred_probs, average='macro'):
    n_classes = y_pred_probs.shape[1]
    #y_true_labels = np.argmax(y_true, axis=1) if y_true.ndim > 1 else y_true
    y_true_bin = label_binarize(y_true, classes=range(n_classes))

    auc_pr_list = []
    for i in range(n_classes):
        precision, recall, _ = precision_recall_curve(y_true_bin[:, i], y_pred_probs[:, i])
        auc_pr_list.append(auc(recall, precision))

    if average == 'macro':
        return np.mean(auc_pr_list)
    elif average == 'weighted':
        class_counts = y_true_bin.sum(axis=0)
        return np.average(auc_pr_list, weights=class_counts)
    else:
        return auc_pr_list

# KNN

In [ ]:
from tensorflow.keras.losses import sparse_categorical_crossentropy
from sklearn.ensemble import VotingClassifier,StackingClassifier
from sklearn.linear_model import LogisticRegression

In [ ]:
accuracies_train=[]
accuracies_predict=[]
loss_predict=[]
times_train=[]
times_predict=[]
mccs_predict=[]
aucpr_predict=[]
ml_names=[]
abl_names=[]

In [ ]:
import joblib

In [ ]:
path="/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/1. Tradicional Machine Learning/BestResult6/"

In [31]:
from time import time
knn=KNeighborsClassifier(n_neighbors=15,p=1,weights='distance')
svm_pipe=Pipeline([
    ('scaler',StandardScaler()),
    ('classifier',SVC(kernel='rbf',gamma=3.359818286283781e-05,C=69.51927961775606,probability=True))
])
mlp_pipe=Pipeline([
    ('scaler',StandardScaler()),
    ('classifier',MLPClassifier(hidden_layer_sizes=(100,100,100),learning_rate='adaptive'))
])

rf=RandomForestClassifier(n_estimators=80,max_depth=15)

vt=VotingClassifier(estimators=[('mlp',mlp_pipe),('rf',rf)],voting='soft')
st=StackingClassifier(estimators=[('mlp',mlp_pipe),('rf',rf)],final_estimator=LogisticRegression())

models=[knn,svm_pipe,mlp_pipe,rf,vt,st]
models_names=["KNN","SVM","MLP","Random Forest","Voting","Stacking"]
ablations_names=["problemall","problem_gries","code_gries","gries","problem_code","code"]

for model,name in zip(models,models_names):
  print(name)
  # Define the full datasets outside the inner loop
  X_train_full = np.concatenate((Xp_train,Xcode_train,Xs_train,Xt_train,Xf_train),axis=1)
  X_test_full = np.concatenate((Xp_test,Xcode_test,Xs_test,Xt_test,Xf_test),axis=1)

  for ablations_name in ablations_names:
    ml_names.append(name)
    abl_names.append(ablations_name)
    print(ablations_name)

    if ablations_name=="problemall":
      X_train = X_train_full
      X_test = X_test_full
    elif ablations_name=="problem_gries":
      X_train=np.concatenate((Xp_train,Xs_train,Xt_train,Xf_train),axis=1)
      X_test=np.concatenate((Xp_test,Xs_test,Xt_test,Xf_test),axis=1) # Corrected X_test construction
    elif ablations_name=="code_gries":
      X_train=np.concatenate((Xcode_train,Xs_train,Xt_train,Xf_train),axis=1)
      X_test=np.concatenate((Xcode_test,Xs_test,Xt_test,Xf_test),axis=1) # Corrected X_test construction
    elif ablations_name=="gries":
      X_train=np.concatenate((Xs_train,Xt_train,Xf_train),axis=1)
      X_test=np.concatenate((Xs_test,Xt_test,Xf_test),axis=1) # Corrected X_test construction
    elif ablations_name=="problem_code":
      X_train=np.concatenate((Xp_train,Xcode_train),axis=1)
      X_test=np.concatenate((Xp_test,Xcode_test),axis=1) # Corrected X_test construction
    elif ablations_name=="code":
      X_train=Xcode_train # Corrected X_train construction
      X_test=Xcode_test # Corrected X_test construction

    time1=time()
    model.fit(X_train,y_train)
    time2=time()
    joblib.dump(model,path+"graph_"+name+"_"+ablations_name+".joblib")
    times_train.append(time2-time1)
    time1=time()
    y_pred=model.predict(X_test)
    time2=time()
    times_predict.append(time2-time1)

    accuracie_train=model.score(X_train,y_train)
    accuracies_train.append(accuracie_train)
    accuracie_test=model.score(X_test,y_test)
    accuracies_predict.append(accuracie_test)
    #sparse_categorical_crossentropy
    y_pred_proba = model.predict_proba(X_test)
    loss=np.mean(sparse_categorical_crossentropy(y_test,y_pred_proba))
    loss_predict.append(loss)
    mcc = matthews_corrcoef(y_test, y_pred)
    mccs_predict.append(mcc)
    auc_pr = calculate_auc_pr_multiclass(y_test, model.predict_proba(X_test))
    aucpr_predict.append(auc_pr)
    print(classification_report(y_test,y_pred))
    print("Accuracy train",accuracie_train)
    print("Accuracy predict",accuracie_test)
    print("Loss",loss)
    print("MCC",mcc)
    print("AUC",auc_pr)
    print("==================================")

KNN
problemall
              precision    recall  f1-score   support

           0       0.94      0.97      0.96       208
           1       0.94      0.97      0.95       210
           2       0.96      0.93      0.94       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.88      0.94        33
           6       0.93      1.00      0.96        26

    accuracy                           0.95       819
   macro avg       0.96      0.94      0.95       819
weighted avg       0.95      0.95      0.95       819

Accuracy train 0.9987786259541984
Accuracy predict 0.9487179487179487
Loss 0.3826905791312813
MCC 0.9314327240529273
AUC 0.9718385824902965
==================================
problem_gries
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       208
           1       0.94      0.98      0.96       210
           2       0.96      0.93      0.94       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.88      0.94        33
           6       0.93      1.00      0.96        26

    accuracy                           0.95       819
   macro avg       0.96      0.94      0.95       819
weighted avg       0.95      0.95      0.95       819

Accuracy train 0.9987786259541984
Accuracy predict 0.9511599511599511
Loss 0.383415808740212
MCC 0.9347191817929315
AUC 0.9723003856780207
==================================
code_gries
              precision    recall  f1-score   support

           0       0.94      0.97      0.96       208
           1       0.93      0.97      0.95       210
           2       0.96      0.93      0.94       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.82      0.90        33
           6       0.93      1.00      0.96        26

    accuracy                           0.95       819
   macro avg       0.96      0.93      0.94       819
weighted avg       0.95      0.95      0.95       819

Accuracy train 0.9987786259541984
Accuracy predict 0.9462759462759462
Loss 0.3677460963718306
MCC 0.9281594656903975
AUC 0.9734294472921398
==================================
gries
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       208
           1       0.93      0.98      0.95       210
           2       0.96      0.93      0.94       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.82      0.90        33
           6       0.93      1.00      0.96        26

    accuracy                           0.95       819
   macro avg       0.96      0.93      0.94       819
weighted avg       0.95      0.95      0.95       819

Accuracy train 0.9981679389312977
Accuracy predict 0.9487179487179487
Loss 0.3682766935540487
MCC 0.9314558638535773
AUC 0.9724065129466142
==================================
problem_code
              precision    recall  f1-score   support

           0       0.87      0.94      0.90       208
           1       0.93      0.95      0.94       210
           2       0.95      0.90      0.92       281
           3       1.00      1.00      1.00        31
           4       0.92      0.80      0.86        30
           5       1.00      0.82      0.90        33
           6       0.87      1.00      0.93        26

    accuracy                           0.92       819
   macro avg       0.93      0.92      0.92       819
weighted avg       0.93      0.92      0.92       819

Accuracy train 0.9987786259541984
Accuracy predict 0.9230769230769231
Loss 0.4166089861674832
MCC 0.8975937827990464
AUC 0.9638684090770809
==================================
code
              precision    recall  f1-score   support

           0       0.88      0.95      0.92       208
           1       0.94      0.98      0.96       210
           2       0.97      0.90      0.94       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.82      0.90        33
           6       0.87      1.00      0.93        26

    accuracy                           0.94       819
   macro avg       0.95      0.92      0.93       819
weighted avg       0.94      0.94      0.94       819

Accuracy train 0.9987786259541984
Accuracy predict 0.9352869352869353
Loss 0.36072829832777775
MCC 0.9140777146587616
AUC 0.9657206243911031
==================================
SVM
problemall
              precision    recall  f1-score   support

           0       0.88      0.95      0.91       208
           1       0.88      0.93      0.91       210
           2       0.93      0.89      0.91       281
           3       0.97      0.94      0.95        31
           4       0.85      0.73      0.79        30
           5       1.00      0.64      0.78        33
           6       0.93      0.96      0.94        26

    accuracy                           0.90       819
   macro avg       0.92      0.86      0.88       819
weighted avg       0.90      0.90      0.90       819

Accuracy train 0.966412213740458
Accuracy predict 0.9023199023199023
Loss 0.3407657992666123
MCC 0.8693530166890832
AUC 0.9146666502528005
==================================
problem_gries
              precision    recall  f1-score   support

           0       0.83      0.94      0.88       208
           1       0.87      0.90      0.89       210
           2       0.91      0.88      0.89       281
           3       0.93      0.81      0.86        31
           4       0.81      0.57      0.67        30
           5       0.88      0.64      0.74        33
           6       0.88      0.85      0.86        26

    accuracy                           0.88       819
   macro avg       0.87      0.80      0.83       819
weighted avg       0.88      0.88      0.87       819

Accuracy train 0.9502290076335878
Accuracy predict 0.8754578754578755
Loss 0.39716217604923804
MCC 0.8330772453887463
AUC 0.9043071064784245
==================================
code_gries
              precision    recall  f1-score   support

           0       0.85      0.95      0.90       208
           1       0.87      0.91      0.89       210
           2       0.93      0.88      0.90       281
           3       0.97      0.90      0.93        31
           4       0.88      0.70      0.78        30
           5       1.00      0.58      0.73        33
           6       0.93      0.96      0.94        26

    accuracy                           0.89       819
   macro avg       0.92      0.84      0.87       819
weighted avg       0.89      0.89      0.89       819

Accuracy train 0.9627480916030534
Accuracy predict 0.8901098901098901
Loss 0.3407126265569201
MCC 0.8530341090911426
AUC 0.9173394502312985
==================================
gries
              precision    recall  f1-score   support

           0       0.85      0.95      0.90       208
           1       0.87      0.90      0.88       210
           2       0.91      0.89      0.90       281
           3       0.93      0.81      0.86        31
           4       0.85      0.57      0.68        30
           5       0.87      0.61      0.71        33
           6       0.92      0.85      0.88        26

    accuracy                           0.88       819
   macro avg       0.88      0.80      0.83       819
weighted avg       0.88      0.88      0.88       819

Accuracy train 0.9435114503816794
Accuracy predict 0.8803418803418803
Loss 0.4090849538255297
MCC 0.8392556293323317
AUC 0.8967176291624269
==================================
problem_code
              precision    recall  f1-score   support

           0       0.66      0.81      0.73       208
           1       0.73      0.78      0.76       210
           2       0.83      0.80      0.82       281
           3       0.86      0.39      0.53        31
           4       0.62      0.17      0.26        30
           5       0.82      0.42      0.56        33
           6       0.72      0.88      0.79        26

    accuracy                           0.75       819
   macro avg       0.75      0.61      0.64       819
weighted avg       0.75      0.75      0.74       819

Accuracy train 0.8085496183206107
Accuracy predict 0.746031746031746
Loss 0.7368911148594605
MCC 0.6568805933584932
AUC 0.7472515743146666
==================================
code
              precision    recall  f1-score   support

           0       0.64      0.82      0.72       208
           1       0.70      0.75      0.72       210
           2       0.84      0.78      0.81       281
           3       0.86      0.39      0.53        31
           4       1.00      0.10      0.18        30
           5       0.81      0.39      0.53        33
           6       0.79      0.88      0.84        26

    accuracy                           0.73       819
   macro avg       0.80      0.59      0.62       819
weighted avg       0.75      0.73      0.72       819

Accuracy train 0.7932824427480916
Accuracy predict 0.7313797313797313
Loss 0.7566317608585601
MCC 0.6375675837083334
AUC 0.7450198527183225
==================================
MLP
problemall
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       208
           1       0.89      0.98      0.93       210
           2       0.96      0.90      0.93       281
           3       0.91      1.00      0.95        31
           4       0.93      0.83      0.88        30
           5       1.00      0.82      0.90        33
           6       0.90      1.00      0.95        26

    accuracy                           0.94       819
   macro avg       0.94      0.93      0.93       819
weighted avg       0.94      0.94      0.94       819

Accuracy train 0.9883969465648855
Accuracy predict 0.9413919413919414
Loss 0.39519128
MCC 0.9223034694870146
AUC 0.9512768604888339
==================================
problem_gries
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       208
           1       0.91      0.99      0.95       210
           2       0.95      0.93      0.94       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.88      0.94        33
           6       0.93      1.00      0.96        26

    accuracy                           0.95       819
   macro avg       0.96      0.94      0.95       819
weighted avg       0.95      0.95      0.95       819

Accuracy train 0.9902290076335878
Accuracy predict 0.9499389499389499
Loss 0.41466588
MCC 0.9332994288245945
AUC 0.9476295002269363
==================================
code_gries
              precision    recall  f1-score   support

           0       0.94      0.98      0.96       208
           1       0.90      0.98      0.93       210
           2       0.97      0.91      0.94       281
           3       0.97      0.97      0.97        31
           4       0.93      0.83      0.88        30
           5       1.00      0.73      0.84        33
           6       0.93      1.00      0.96        26

    accuracy                           0.94       819
   macro avg       0.95      0.91      0.93       819
weighted avg       0.94      0.94      0.94       819

Accuracy train 0.9716030534351145
Accuracy predict 0.938949938949939
Loss 0.3482081
MCC 0.918947058229875
AUC 0.9321242329380536
==================================
gries
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       208
           1       0.92      0.98      0.95       210
           2       0.94      0.95      0.95       281
           3       1.00      1.00      1.00        31
           4       1.00      0.77      0.87        30
           5       1.00      0.82      0.90        33
           6       0.87      1.00      0.93        26

    accuracy                           0.95       819
   macro avg       0.96      0.92      0.94       819
weighted avg       0.95      0.95      0.95       819

Accuracy train 0.9923664122137404
Accuracy predict 0.9499389499389499
Loss 0.31166023
MCC 0.9330475943397499
AUC 0.9682017128700194
==================================
problem_code
              precision    recall  f1-score   support

           0       0.98      0.95      0.96       208
           1       0.93      0.96      0.95       210
           2       0.93      0.95      0.94       281
           3       1.00      1.00      1.00        31
           4       1.00      0.87      0.93        30
           5       1.00      0.82      0.90        33
           6       0.86      0.96      0.91        26

    accuracy                           0.95       819
   macro avg       0.96      0.93      0.94       819
weighted avg       0.95      0.95      0.95       819

Accuracy train 0.9883969465648855
Accuracy predict 0.9462759462759462
Loss 0.28965023
MCC 0.9279790576740383
AUC 0.9686112102808035
==================================
code
              precision    recall  f1-score   support

           0       0.98      0.95      0.96       208
           1       0.93      0.99      0.96       210
           2       0.94      0.96      0.95       281
           3       1.00      0.94      0.97        31
           4       0.96      0.80      0.87        30
           5       1.00      0.82      0.90        33
           6       0.93      1.00      0.96        26

    accuracy                           0.95       819
   macro avg       0.96      0.92      0.94       819
weighted avg       0.95      0.95      0.95       819

Accuracy train 0.9887022900763359
Accuracy predict 0.9511599511599511
Loss 0.26743653
MCC 0.9345635694396232
AUC 0.9630276450991744
==================================
Random Forest
problemall
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       208
           1       0.92      0.98      0.95       210
           2       0.95      0.93      0.94       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.82      0.90        33
           6       0.93      1.00      0.96        26

    accuracy                           0.95       819
   macro avg       0.96      0.93      0.94       819
weighted avg       0.95      0.95      0.95       819

Accuracy train 0.9987786259541984
Accuracy predict 0.9474969474969475
Loss 0.26226375600497287
MCC 0.929845137713522
AUC 0.9662470869734572
==================================
problem_gries
              precision    recall  f1-score   support

           0       0.97      0.98      0.97       208
           1       0.93      0.99      0.96       210
           2       0.96      0.94      0.95       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.82      0.90        33
           6       0.93      1.00      0.96        26

    accuracy                           0.96       819
   macro avg       0.96      0.93      0.95       819
weighted avg       0.96      0.96      0.96       819

Accuracy train 0.9987786259541984
Accuracy predict 0.9560439560439561
Loss 0.2571632072444875
MCC 0.941324413206703
AUC 0.967884803439124
==================================
code_gries
              precision    recall  f1-score   support

           0       0.97      0.98      0.97       208
           1       0.94      0.99      0.96       210
           2       0.96      0.94      0.95       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.82      0.90        33
           6       0.93      1.00      0.96        26

    accuracy                           0.96       819
   macro avg       0.97      0.93      0.95       819
weighted avg       0.96      0.96      0.96       819

Accuracy train 0.9987786259541984
Accuracy predict 0.9584859584859585
Loss 0.26106184772120716
MCC 0.9445119841487503
AUC 0.9622738360298425
==================================
gries
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       208
           1       0.93      0.99      0.96       210
           2       0.96      0.94      0.95       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.82      0.90        33
           6       0.93      1.00      0.96        26

    accuracy                           0.95       819
   macro avg       0.96      0.93      0.94       819
weighted avg       0.95      0.95      0.95       819

Accuracy train 0.9981679389312977
Accuracy predict 0.9536019536019537
Loss 0.24197439169009322
MCC 0.9379946218609664
AUC 0.9622255329095875
==================================
problem_code
              precision    recall  f1-score   support

           0       0.92      0.96      0.94       208
           1       0.93      0.96      0.94       210
           2       0.95      0.93      0.94       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.79      0.88        33
           6       0.93      1.00      0.96        26

    accuracy                           0.94       819
   macro avg       0.96      0.92      0.93       819
weighted avg       0.94      0.94      0.94       819

Accuracy train 0.997557251908397
Accuracy predict 0.938949938949939
Loss 0.40340723863929223
MCC 0.9182492252031206
AUC 0.9495920700236022
==================================
code
              precision    recall  f1-score   support

           0       0.93      0.96      0.94       208
           1       0.94      0.97      0.95       210
           2       0.94      0.92      0.93       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.82      0.90        33
           6       0.93      1.00      0.96        26

    accuracy                           0.94       819
   macro avg       0.96      0.92      0.94       819
weighted avg       0.94      0.94      0.94       819

Accuracy train 0.9984732824427481
Accuracy predict 0.9401709401709402
Loss 0.3569684146819971
MCC 0.9199198774813024
AUC 0.9500271698980399
==================================
Voting
problemall
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       208
           1       0.86      0.99      0.92       210
           2       0.95      0.89      0.92       281
           3       1.00      0.90      0.95        31
           4       0.96      0.80      0.87        30
           5       0.92      0.70      0.79        33
           6       0.87      1.00      0.93        26

    accuracy                           0.92       819
   macro avg       0.93      0.89      0.90       819
weighted avg       0.93      0.92      0.92       819

Accuracy train 0.9883969465648855
Accuracy predict 0.9218559218559218
Loss 0.2574341948736554
MCC 0.8963999889906451
AUC 0.9610732635423435
==================================
problem_gries
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       208
           1       0.92      0.99      0.95       210
           2       0.93      0.94      0.94       281
           3       1.00      1.00      1.00        31
           4       0.96      0.80      0.87        30
           5       1.00      0.88      0.94        33
           6       0.92      0.92      0.92        26


In [32]:
import pandas as pd
df=pd.DataFrame({
    "Model":ml_names,
    "Ablation":abl_names,
    "Accuracy_train":accuracies_train,
    "Accuracy_predict":accuracies_predict,
    "Loss":loss_predict,
    "Time_train":times_train,
    "Time_predict":times_predict,
    "MCC":mccs_predict,
    "AUC":aucpr_predict
})

In [33]:
df

,Model,Ablation,Accuracy_train,Accuracy_predict,Loss,Time_train,Time_predict,MCC,AUC
0,KNN,problemall,0.998779,0.948718,0.382691,0.006111,4.536839,0.931433,0.971839
1,KNN,problem_gries,0.998779,0.951160,0.383416,0.004442,3.547064,0.934719,0.972300
2,KNN,code_gries,0.998779,0.946276,0.367746,0.004646,3.547678,0.928159,0.973429
3,KNN,gries,0.998168,0.948718,0.368277,0.003758,2.582526,0.931456,0.972407
4,KNN,problem_code,0.998779,0.923077,0.416609,0.002913,1.777971,0.897594,0.963868
5,KNN,code,0.998779,0.935287,0.360728,0.001803,0.878540,0.914078,0.965721
6,SVM,problemall,0.966412,0.902320,0.340766,64.167769,5.635096,0.869353,0.914667
7,SVM,problem_gries,0.950229,0.875458,0.397162,49.501906,4.383139,0.833077,0.904307
8,SVM,code_gries,0.962748,0.890110,0.340713,46.498002,4.053945,0.853034,0.917339
9,SVM,gries,0.943511,0.880342,0.409085,33.798800,2.847913,0.839256,0.896718
10,SVM,problem_code,0.808550,0.746032,0.736891,26.995231,2.157318,0.656881,0.747252
11,SVM,code,0.793282,0.731380,0.756632,14.558553,1.066060,0.637568,0.745020
12,MLP,problemall,0.988397,0.941392,0.395191,12.306275,0.026442,0.922303,0.951277
13,MLP,problem_gries,0.990229,0.949939,0.414666,11.394871,0.020123,0.933299,0.947630
14,MLP,code_gries,0.971603,0.938950,0.348208,9.214896,0.026048,0.918947,0.932124
15,MLP,gries,0.992366,0.949939,0.311660,3.515079,0.020890,0.933048,0.968202
16,MLP,problem_code,0.988397,0.946276,0.289650,5.667245,0.011766,0.927979,0.968611
17,MLP,code,0.988702,0.951160,0.267437,6.653990,0.006773,0.934564,0.963028
18,Random Forest,problemall,0.998779,0.947497,0.262264,8.603071,0.021754,0.929845,0.966247
19,Random Forest,problem_gries,0.998779,0.956044,0.257163,6.891726,0.019701,0.941324,0.967885
20,Random Forest,code_gries,0.998779,0.958486,0.261062,8.072260,0.020816,0.944512,0.962274
21,Random Forest,gries,0.998168,0.953602,0.241974,6.135260,0.019637,0.937995,0.962226
22,Random Forest,problem_code,0.997557,0.938950,0.403407,6.027905,0.019956,0.918249,0.949592
23,Random Forest,code,0.998473,0.940171,0.356968,5.501367,0.020121,0.919920,0.950027
24,Voting,problemall,0.988397,0.921856,0.257434,20.492767,0.051191,0.896400,0.961073
25,Voting,problem_gries,0.997863,0.948718,0.205994,20.371888,0.124305,0.931350,0.966677
26,Voting,code_gries,0.997863,0.949939,0.191690,14.307015,0.045158,0.932975,0.975905
27,Voting,gries,0.997557,0.956044,0.198779,14.352005,0.038848,0.941342,0.966314
28,Voting,problem_code,0.994809,0.945055,0.256926,12.129975,0.033592,0.926285,0.961815
29,Voting,code,0.996641,0.948718,0.252214,8.987856,0.030739,0.931304,0.958655
30,Stacking,problemall,0.998473,0.948718,0.175285,97.933313,0.051395,0.931364,0.972723
31,Stacking,problem_gries,0.998779,0.949939,0.173460,89.344226,0.042532,0.933151,0.972117
32,Stacking,code_gries,0.998779,0.956044,0.162676,85.152047,0.044816,0.941109,0.974204
33,Stacking,gries,0.998168,0.953602,0.158625,71.134316,0.040962,0.937869,0.970821
34,Stacking,problem_code,0.998473,0.958486,0.179182,72.512356,0.033799,0.944266,0.969531
35,Stacking,code,0.998779,0.953602,0.174729,50.516073,0.029932,0.937694,0.965271

In [34]:
path="/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/1. Tradicional Machine Learning/BestResult6/"

In [35]:
df.to_csv(path+"tradicionalML_ablationsResultsGraph.csv",index=False)

In [36]:
df=pd.read_csv(path+"tradicionalML_ablationsResultsGraph.csv")
df

,Model,Ablation,Accuracy_train,Accuracy_predict,Loss,Time_train,Time_predict,MCC,AUC
0,KNN,problemall,0.998779,0.948718,0.382691,0.006111,4.536839,0.931433,0.971839
1,KNN,problem_gries,0.998779,0.951160,0.383416,0.004442,3.547064,0.934719,0.972300
2,KNN,code_gries,0.998779,0.946276,0.367746,0.004646,3.547678,0.928159,0.973429
3,KNN,gries,0.998168,0.948718,0.368277,0.003758,2.582526,0.931456,0.972407
4,KNN,problem_code,0.998779,0.923077,0.416609,0.002913,1.777971,0.897594,0.963868
5,KNN,code,0.998779,0.935287,0.360728,0.001803,0.878540,0.914078,0.965721
6,SVM,problemall,0.966412,0.902320,0.340766,64.167769,5.635096,0.869353,0.914667
7,SVM,problem_gries,0.950229,0.875458,0.397162,49.501906,4.383139,0.833077,0.904307
8,SVM,code_gries,0.962748,0.890110,0.340713,46.498002,4.053945,0.853034,0.917339
9,SVM,gries,0.943511,0.880342,0.409085,33.798800,2.847913,0.839256,0.896718
10,SVM,problem_code,0.808550,0.746032,0.736891,26.995231,2.157318,0.656881,0.747252
11,SVM,code,0.793282,0.731380,0.756632,14.558553,1.066060,0.637568,0.745020
12,MLP,problemall,0.988397,0.941392,0.395191,12.306275,0.026442,0.922303,0.951277
13,MLP,problem_gries,0.990229,0.949939,0.414666,11.394871,0.020123,0.933299,0.947630
14,MLP,code_gries,0.971603,0.938950,0.348208,9.214896,0.026048,0.918947,0.932124
15,MLP,gries,0.992366,0.949939,0.311660,3.515079,0.020890,0.933048,0.968202
16,MLP,problem_code,0.988397,0.946276,0.289650,5.667245,0.011766,0.927979,0.968611
17,MLP,code,0.988702,0.951160,0.267437,6.653990,0.006773,0.934564,0.963028
18,Random Forest,problemall,0.998779,0.947497,0.262264,8.603071,0.021754,0.929845,0.966247
19,Random Forest,problem_gries,0.998779,0.956044,0.257163,6.891726,0.019701,0.941324,0.967885
20,Random Forest,code_gries,0.998779,0.958486,0.261062,8.072260,0.020816,0.944512,0.962274
21,Random Forest,gries,0.998168,0.953602,0.241974,6.135260,0.019637,0.937995,0.962226
22,Random Forest,problem_code,0.997557,0.938950,0.403407,6.027905,0.019956,0.918249,0.949592
23,Random Forest,code,0.998473,0.940171,0.356968,5.501367,0.020121,0.919920,0.950027
24,Voting,problemall,0.988397,0.921856,0.257434,20.492767,0.051191,0.896400,0.961073
25,Voting,problem_gries,0.997863,0.948718,0.205994,20.371888,0.124305,0.931350,0.966677
26,Voting,code_gries,0.997863,0.949939,0.191690,14.307015,0.045158,0.932975,0.975905
27,Voting,gries,0.997557,0.956044,0.198779,14.352005,0.038848,0.941342,0.966314
28,Voting,problem_code,0.994809,0.945055,0.256926,12.129975,0.033592,0.926285,0.961815
29,Voting,code,0.996641,0.948718,0.252214,8.987856,0.030739,0.931304,0.958655
30,Stacking,problemall,0.998473,0.948718,0.175285,97.933313,0.051395,0.931364,0.972723
31,Stacking,problem_gries,0.998779,0.949939,0.173460,89.344226,0.042532,0.933151,0.972117
32,Stacking,code_gries,0.998779,0.956044,0.162676,85.152047,0.044816,0.941109,0.974204
33,Stacking,gries,0.998168,0.953602,0.158625,71.134316,0.040962,0.937869,0.970821
34,Stacking,problem_code,0.998473,0.958486,0.179182,72.512356,0.033799,0.944266,0.969531
35,Stacking,code,0.998779,0.953602,0.174729,50.516073,0.029932,0.937694,0.965271

# Externd Data

In [37]:
extern_file = '/content/drive/MyDrive/UDENAR/ProyectosGrado/Errol/Ginna/Tuning/BestModels/Copia de ExternData.csv'
train_full = pd.read_csv(extern_file)
train_full

,Problem Description,Python Code,Source,Description Error,Error Label
0,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2
1,Sum numbers from 1 to n,def sum_to_n_buggy(n):\n total = 0\n i =...,Based on typical mistakes in Codeforces common...,i is incorrectly incremented,2
2,Prompt user for numbers until 0 is entered,def input_until_zero_buggy():\n num = int(i...,Common error from GeeksforGeeks Python while l...,number is never updated in the loop,2
3,Find first multiple of 7 greater than n,def first_multiple_7_buggy(n):\n i = n + 1\...,Typical error in CodeNet beginner loop problems,i not incremented,2
4,Calculate factorial of n,def factorial_buggy(n):\n result = 1\n w...,Inspired by classic factorial exercises,"decrement by 2, not 1",2
5,Count digits in a positive integer n,def count_digits_buggy(n):\n count = 0\n ...,Inspired by digit counting problems in Codefor...,n not updated inside the loop,2
6,Sum all even numbers up to n,def sum_evens_buggy(n):\n total = 0\n i ...,"CodeChef/Codeforces summing problems, conditio...",loop condition incorrect,1
7,Find a prime number using break,def find_prime_buggy():\n num = 2\n whil...,Inspired by break/continue loop errors from Py...,break outside the if block,2
8,Print cubes of numbers from 1 to n,def print_cubes_buggy(n):\n while i <= n:\n...,"Common initialization error, based on CodeNet ...",i not initialized,0
9,Prompt for password until correct,def prompt_password_buggy():\n password = i...,Typical validation loop error from Python begi...,password requested only once,2
10,"Print numbers from 1 to n, but condition exclu...",def print_numbers_buggy(n):\n i = 1\n wh...,Common inclusive/exclusive error in loops (Cod...,condition excludes n,1
11,Divide a number by 2 repeatedly until it's les...,def divide_repeatedly_buggy(n):\n while n >...,Inspired by CodeNet loop problems involving di...,integer division and missing update,2
12,Sum all digits of n,def sum_digits_buggy(n):\n total = 0\n w...,"Classic digit-processing error, Python/Codeforces",missing update of n,2
13,Count how many times 5 can be subtracted from n,def count_subtract_5_buggy(n):\n count = 0\...,Common mistake in decrement loops (CodeNet/Cod...,n is not updated,2
14,Calculate power using while loop,"def power_buggy(base, exp):\n result = 1\n ...",Power calculation errors in Codeforces/Python ...,missing increment of i,2
15,Check if number is perfect,def is_perfect_buggy(n):\n sum_div = 0\n ...,"Perfect number mistakes, classic math loops",sum calculation and missing increment,2
16,Convert decimal to binary,def decimal_to_binary_buggy(n):\n res = ''\...,"Typical binary conversion loop, Codeforces/Cod...",n not updated inside the loop,2
17,Print items in list until negative is found,def print_until_negative_buggy(lst):\n i = ...,Inspired by control-flow misplacement from Pyt...,break outside the if block,2
18,Count multiples of 3 up to n,def count_mult_3_buggy(n):\n i = 1\n cou...,"Loops with missed accumulation, typical in beg...",count never updated,2
19,Print odd numbers up to n,def print_odds_buggy(n):\n i = 1\n while...,"Increment logic error, Codeforces/CodeChef",i is incremented incorrectly,2
20,Sum the first n natural numbers,def sum_n_buggy(n):\n i = 1\n total = 0\...,"Classic off-by-one loop error, inspired by bas...",loop condition excludes n,1
21,Sum odd numbers up to n,def sum_odds_buggy(n):\n total = 0\n i =...,"Odd number sum, increment bug, beginner mistakes",i increment incorrect,2
22,Count primes up to n,def count_primes_buggy(n):\n count = 0\n ...,Classic loop and condition error in prime coun...,loop condition excludes n,1
23,Read and sum numbers until a negative is entered,def sum_until_negative_buggy():\n total = 0...,"Missing input update bug, shown in tutorials (...",does not read new number inside loop,2
24,Find LCM of two numbers,"def lcm_buggy(a, b):\n num = max(a, b)\n ...","LCM calculation, common loop bug (CodeNet/Code...",missing increment of candidate,2
25,Print Fibonacci sequence up to n terms,"def fibonacci_buggy(n):\n a, b = 0, 1\n ...","Sequence and assignment bug, inspired by class...",assignments out of order,2
26,Count multiples of 5 up to n,def count_mult_5_buggy(n):\n i = 1\n cou...,"Missing i update, common beginner error, CodeC...",i not updated,2
27,Find GCD of two numbers using Euclid algorithm,"def gcd_buggy(a, b):\n while a != b:\n ...","Euclid's algorithm off-by-one/condition bug, C...",condition may cause infinite loop,1
28,Prompt user for positive numbers until 5 are e...,def count_positives_buggy():\n count = 0\n ...,"Input accumulation/counting error, basic progr...",counter never incremented,2
29,Sum multiples of 4 between 1 and n,def sum_mult_4_buggy(n):\n i = 1\n while...,"Sum variable scope bug, inspired by sum/accumu...",sum variable is reset inside the loop,2
30,"Print the factorial of n, but n is not initial...",def buggy_factorial():\n while n > 0:\n ...,Initialization errors are a classic mistake (C...,n is not initialized before the while loop,0
31,Reverse a list but forget to initialize the in...,def buggy_reverse(lst):\n # missing i = len...,"Initialization and condition errors, common in...",missing initialization and undefined variable ...,3
32,"Print numbers from a to b, missing both variab...",def buggy_print_range(b):\n # missing a = 1...,Initialization and update errors frequently se...,missing initialization and wrong update in loo...,4
33,"Sum even numbers in a list, with an off-by-one...",def buggy_sum_evens(lst):\n i = 0\n sum_...,"Condition and update errors, drawn from typica...",wrong condition and no accumulation in loop body,5
34,"Count numbers divisible by 3, fails to initial...",def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6

In [38]:
train_full['Python Code']=train_full['Python Code'].apply(lambda x: x.replace("\\n","\n"))

In [39]:
train_full[["Estado incial","Transformación de estado","Estado final"]]=train_full['Python Code'].apply(DGries_states).apply(pd.Series)

OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body

In [40]:
train_full

,Problem Description,Python Code,Source,Description Error,Error Label,Estado incial,Transformación de estado,Estado final
0,Count how many even numbers are up to n,def count_evens_buggy(n):\n i = 0\n coun...,Inspired by CodeChef Learn Python (While Loop)...,missing increment leads to infinite loop,2,i = 0\n count = 0,if i % 2 == 0:\n count += 1,i <= n
1,Sum numbers from 1 to n,def sum_to_n_buggy(n):\n total = 0\n i =...,Based on typical mistakes in Codeforces common...,i is incorrectly incremented,2,total = 0\n i = 1,total += i\ni = i + 0,i <= n
2,Prompt user for numbers until 0 is entered,def input_until_zero_buggy():\n num = int(i...,Common error from GeeksforGeeks Python while l...,number is never updated in the loop,2,num = int(input('Enter number (0 to exit): ')),"print('Number:', num)",num != 0
3,Find first multiple of 7 greater than n,def first_multiple_7_buggy(n):\n i = n + 1\...,Typical error in CodeNet beginner loop problems,i not incremented,2,i = n + 1,pass,i % 7 != 0
4,Calculate factorial of n,def factorial_buggy(n):\n result = 1\n w...,Inspired by classic factorial exercises,"decrement by 2, not 1",2,result = 1,result *= n\nn -= 2,n > 1
5,Count digits in a positive integer n,def count_digits_buggy(n):\n count = 0\n ...,Inspired by digit counting problems in Codefor...,n not updated inside the loop,2,count = 0,n % 10\ncount += 1,n > 0
6,Sum all even numbers up to n,def sum_evens_buggy(n):\n total = 0\n i ...,"CodeChef/Codeforces summing problems, conditio...",loop condition incorrect,1,total = 0\n i = 2,total += i\ni += 2,i < n
7,Find a prime number using break,def find_prime_buggy():\n num = 2\n whil...,Inspired by break/continue loop errors from Py...,break outside the if block,2,num = 2,is_prime = True\ndivisor = 2\nwhile divisor < ...,True
8,Print cubes of numbers from 1 to n,def print_cubes_buggy(n):\n while i <= n:\n...,"Common initialization error, based on CodeNet ...",i not initialized,0,print(i ** 3)\ni += 1,print(i ** 3)\ni += 1,i <= n
9,Prompt for password until correct,def prompt_password_buggy():\n password = i...,Typical validation loop error from Python begi...,password requested only once,2,password = input('Enter password: '),print('Incorrect'),password != 'secret'
10,"Print numbers from 1 to n, but condition exclu...",def print_numbers_buggy(n):\n i = 1\n wh...,Common inclusive/exclusive error in loops (Cod...,condition excludes n,1,i = 1,print(i)\ni += 1,i < n
11,Divide a number by 2 repeatedly until it's les...,def divide_repeatedly_buggy(n):\n while n >...,Inspired by CodeNet loop problems involving di...,integer division and missing update,2,print(n)\nn = n // 2,print(n)\nn = n // 2,n >= 1
12,Sum all digits of n,def sum_digits_buggy(n):\n total = 0\n w...,"Classic digit-processing error, Python/Codeforces",missing update of n,2,total = 0,total += n % 10,n > 0
13,Count how many times 5 can be subtracted from n,def count_subtract_5_buggy(n):\n count = 0\...,Common mistake in decrement loops (CodeNet/Cod...,n is not updated,2,count = 0,count += 1,n >= 5
14,Calculate power using while loop,"def power_buggy(base, exp):\n result = 1\n ...",Power calculation errors in Codeforces/Python ...,missing increment of i,2,result = 1\n i = 0,result *= base,i < exp
15,Check if number is perfect,def is_perfect_buggy(n):\n sum_div = 0\n ...,"Perfect number mistakes, classic math loops",sum calculation and missing increment,2,sum_div = 0\n divisor = 1,if n % divisor == 0:\n sum_div = divisor,divisor < n
16,Convert decimal to binary,def decimal_to_binary_buggy(n):\n res = ''\...,"Typical binary conversion loop, Codeforces/Cod...",n not updated inside the loop,2,res = '',res = str(n % 2) + res,n > 0
17,Print items in list until negative is found,def print_until_negative_buggy(lst):\n i = ...,Inspired by control-flow misplacement from Pyt...,break outside the if block,2,i = 0,print(lst[i])\nbreak\nif lst[i] < 0:\n brea...,i < len(lst)
18,Count multiples of 3 up to n,def count_mult_3_buggy(n):\n i = 1\n cou...,"Loops with missed accumulation, typical in beg...",count never updated,2,i = 1\n count = 0,if i % 3 == 0:\n pass\ni += 1,i <= n
19,Print odd numbers up to n,def print_odds_buggy(n):\n i = 1\n while...,"Increment logic error, Codeforces/CodeChef",i is incremented incorrectly,2,i = 1,print(i)\ni += 2\ni += 1,i <= n
20,Sum the first n natural numbers,def sum_n_buggy(n):\n i = 1\n total = 0\...,"Classic off-by-one loop error, inspired by bas...",loop condition excludes n,1,i = 1\n total = 0,total += i\ni += 1,i < n
21,Sum odd numbers up to n,def sum_odds_buggy(n):\n total = 0\n i =...,"Odd number sum, increment bug, beginner mistakes",i increment incorrect,2,total = 0\n i = 1,if i % 2 != 0:\n total += i\ni = i + 1 - 1,i <= n
22,Count primes up to n,def count_primes_buggy(n):\n count = 0\n ...,Classic loop and condition error in prime coun...,loop condition excludes n,1,count = 0\n i = 2,if is_prime(i):\n count += 1\ni += 1,i < n
23,Read and sum numbers until a negative is entered,def sum_until_negative_buggy():\n total = 0...,"Missing input update bug, shown in tutorials (...",does not read new number inside loop,2,total = 0\n num = int(input('Enter number (...,total += num,num >= 0
24,Find LCM of two numbers,"def lcm_buggy(a, b):\n num = max(a, b)\n ...","LCM calculation, common loop bug (CodeNet/Code...",missing increment of candidate,2,"num = max(a, b)",if num % a == 0 and num % b == 0:\n return num,True
25,Print Fibonacci sequence up to n terms,"def fibonacci_buggy(n):\n a, b = 0, 1\n ...","Sequence and assignment bug, inspired by class...",assignments out of order,2,"a, b = 0, 1\n i = 0",print(a)\nb = a + b\na = b\ni += 1,i < n
26,Count multiples of 5 up to n,def count_mult_5_buggy(n):\n i = 1\n cou...,"Missing i update, common beginner error, CodeC...",i not updated,2,i = 1\n count = 0,if i % 5 == 0:\n count += 1,i <= n
27,Find GCD of two numbers using Euclid algorithm,"def gcd_buggy(a, b):\n while a != b:\n ...","Euclid's algorithm off-by-one/condition bug, C...",condition may cause infinite loop,1,if a > b:\n a -= b\nelse:\n b -= a,if a > b:\n a -= b\nelse:\n b -= a,a != b
28,Prompt user for positive numbers until 5 are e...,def count_positives_buggy():\n count = 0\n ...,"Input accumulation/counting error, basic progr...",counter never incremented,2,count = 0,num = int(input('Enter positive number: '))\ni...,count < 5
29,Sum multiples of 4 between 1 and n,def sum_mult_4_buggy(n):\n i = 1\n while...,"Sum variable scope bug, inspired by sum/accumu...",sum variable is reset inside the loop,2,i = 1,sum = 0\nif i % 4 == 0:\n sum += i\ni += 1,i <= n
30,"Print the factorial of n, but n is not initial...",def buggy_factorial():\n while n > 0:\n ...,Initialization errors are a classic mistake (C...,n is not initialized before the while loop,0,print(n)\nn -= 1,print(n)\nn -= 1,n > 0
31,Reverse a list but forget to initialize the in...,def buggy_reverse(lst):\n # missing i = len...,"Initialization and condition errors, common in...",missing initialization and undefined variable ...,3,print(lst[j])\nj -= 1,print(lst[j])\nj -= 1,j >= 0
32,"Print numbers from a to b, missing both variab...",def buggy_print_range(b):\n # missing a = 1...,Initialization and update errors frequently se...,missing initialization and wrong update in loo...,4,a = 1\nprint(a)\na += 1,a = 1\nprint(a)\na += 1,a <= b
33,"Sum even numbers in a list, with an off-by-one...",def buggy_sum_evens(lst):\n i = 0\n sum_...,"Condition and update errors, drawn from typica...",wrong condition and no accumulation in loop body,5,i = 0\n sum_evens = 0,if lst[i] % 2 == 0:\n pass\ni += 1,i <= len(lst)
34,"Count numbers divisible by 3, fails to initial...",def buggy_count_mult_3(n):\n while i < n: ...,"Simultaneous initialization, condition, and bo...","multiple errors in initialization, condition a...",6,count = 0\nif i % 3 == 0:\n pass\ni += 1,count = 0\nif i % 3 == 0:\n pass\ni += 1,i < n

In [41]:
train_full['Python Code']=train_full['Python Code'].apply(lambda x: x.replace("\\n","\n"))

In [42]:
train_full[["Estado incial","Transformación de estado","Estado final"]]=train_full['Python Code'].apply(DGries_states).apply(pd.Series)

OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body
OK condition
Ok body

In [43]:
%%time
problem=train_full['Problem Description'].apply(encoder.tokenize_and_generate_embeddings_descriptions).to_numpy()
code=train_full['Python Code'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
startstate = train_full['Estado incial'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
finalstate = train_full['Estado final'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()
transstate = train_full['Transformación de estado'].apply(encoder.tokenize_and_generate_embeddings_graphcodes).to_numpy()

CPU times: user 1.39 s, sys: 1.01 ms, total: 1.39 s
Wall time: 1.39 s

In [44]:
problem.shape,code.shape,startstate.shape,finalstate.shape,transstate.shape

((35,), (35,), (35,), (35,), (35,))

In [45]:
print(startstate.shape)
print(startstate[0].shape)

(35,)
(1, 12, 768)

In [46]:
Xp=np.array([sentence[0].mean(axis=0) for sentence in problem])
Xcode=np.array([sentence[0].mean(axis=0) for sentence in code])
Xs=np.array([sentence[0].mean(axis=0) for sentence in startstate])
Xf=np.array([sentence[0].mean(axis=0) for sentence in finalstate])
Xt=np.array([sentence[0].mean(axis=0) for sentence in transstate])
Xp.shape,Xs.shape,Xf.shape,Xt.shape

((35, 768), (35, 768), (35, 768), (35, 768))

In [47]:
y=train_full['Error Label']
y=y.to_numpy()
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6])

In [48]:
accuracies_predict=[]
loss_predict=[]
times_predict=[]
mccs_predict=[]
aucpr_predict=[]
ml_names=[]
abl_names=[]

ml_names=[]
abl_names=[]

In [49]:
from time import time


models_names=["KNN","SVM","MLP","Random Forest","Voting","Stacking"]
ablations_names=["problemall","problem_gries","code_gries","gries","problem_code","code"]

for name in models_names:
  print(name)
  for ablations_name in ablations_names:
    ml_names.append(name)
    abl_names.append(ablations_name)
    print(ablations_name)
    model=joblib.load(path+"graph_"+name+"_"+ablations_name+".joblib")
    print(model)
    if ablations_name=="problemall":
      Xe= np.concatenate((Xp,Xcode,Xs,Xt,Xf),axis=1)
    elif ablations_name=="problem_gries":
      Xe=np.concatenate((Xp,Xs,Xt,Xf),axis=1)
    elif ablations_name=="code_gries":
      Xe=np.concatenate((Xcode,Xs,Xt,Xf),axis=1)
    elif ablations_name=="gries":
      Xe=np.concatenate((Xs,Xt,Xf),axis=1)
    elif ablations_name=="problem_code":
      Xe=np.concatenate((Xp,Xcode),axis=1)
    elif ablations_name=="code":
      Xe=Xcode

    time1=time()
    y_pred=model.predict(Xe)
    time2=time()
    times_predict.append(time2-time1)

    accuracie_test=model.score(Xe,y)
    accuracies_predict.append(accuracie_test)
    #sparse_categorical_crossentropy
    y_pred_proba = model.predict_proba(Xe)
    loss=np.mean(sparse_categorical_crossentropy(y,y_pred_proba))
    loss_predict.append(loss)
    mcc = matthews_corrcoef(y, y_pred)
    mccs_predict.append(mcc)
    auc_pr = calculate_auc_pr_multiclass(y, y_pred_proba)
    aucpr_predict.append(auc_pr)
    print(classification_report(y,y_pred))
    print("Accuracy predict",accuracie_test)
    print("Loss",loss)
    print("MCC",mcc)
    print("AUC",auc_pr)
    print("==================================")

KNN
problemall
KNeighborsClassifier(n_neighbors=15, p=1, weights='distance')
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.40      0.57         5
           2       0.85      0.96      0.90        24
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.86        35
   macro avg       0.84      0.77      0.78        35
weighted avg       0.87      0.86      0.84        35

Accuracy predict 0.8571428571428571
Loss 0.2600383573087797
MCC 0.7032636776948774
AUC 0.8736767606842838
==================================
problem_gries
KNeighborsClassifier(n_neighbors=15, p=1, weights='distance')
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       1.00      0.40      0.57         5
           2       0.86      1.00      0.92        24
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.86        35
   macro avg       0.84      0.70      0.74        35
weighted avg       0.87      0.86      0.84        35

Accuracy predict 0.8571428571428571
Loss 0.3144914355956164
MCC 0.70174017534218
AUC 0.8520671769856553
==================================
code_gries
KNeighborsClassifier(n_neighbors=15, p=1, weights='distance')
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.40      0.57         5
           2       0.92      0.96      0.94        24
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.33      1.00      0.50         1

    accuracy                           0.89        35
   macro avg       0.89      0.91      0.86        35
weighted avg       0.93      0.89      0.88        35

Accuracy predict 0.8857142857142857
Loss 0.30307907201713596
MCC 0.7779444736740649
AUC 0.8783330563382502
==================================
gries
KNeighborsClassifier(n_neighbors=15, p=1, weights='distance')
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.40      0.57         5
           2       0.92      0.92      0.92        24
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.33      1.00      0.50         1

    accuracy                           0.86        35
   macro avg       0.85      0.90      0.83        35
weighted avg       0.90      0.86      0.86        35

Accuracy predict 0.8571428571428571
Loss 0.7653565536370465
MCC 0.7290474309056693
AUC 0.800935069324067
==================================
problem_code
KNeighborsClassifier(n_neighbors=15, p=1, weights='distance')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         2
           1       0.67      0.40      0.50         5
           2       0.84      0.88      0.86        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.33      1.00      0.50         1
           6       0.00      0.00      0.00         1

    accuracy                           0.74        35
   macro avg       0.33      0.47      0.36        35
weighted avg       0.71      0.74      0.71        35

Accuracy predict 0.7428571428571429
Loss 1.2026496834969556
MCC 0.48097197110408335
AUC 0.8338160842293906
==================================
code
KNeighborsClassifier(n_neighbors=15, p=1, weights='distance')
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       0.75      0.60      0.67         5
           2       0.96      0.96      0.96        24
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1

    accuracy                           0.91        35
   macro avg       0.91      0.94      0.92        35
weighted avg       0.92      0.91      0.91        35

Accuracy predict 0.9142857142857143
Loss 0.20748359524087878
MCC 0.8317195657866148
AUC 0.9799598316193813
==================================
SVM
problemall
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=69.51927961775606, gamma=3.359818286283781e-05,
                     probability=True))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         2
           1       1.00      0.40      0.57         5
           2       0.82      0.96      0.88        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.80        35
   macro avg       0.47      0.48      0.45        35
weighted avg       0.76      0.80      0.75        35

Accuracy predict 0.8
Loss 0.5351975409733363
MCC 0.5681759430741397
AUC 0.7584075799687743
==================================
problem_gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=69.51927961775606, gamma=3.359818286283781e-05,
                     probability=True))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.40      1.00      0.57         2
           1       1.00      0.40      0.57         5
           2       0.82      0.96      0.88        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.77        35
   macro avg       0.32      0.34      0.29        35
weighted avg       0.73      0.77      0.72        35

Accuracy predict 0.7714285714285715
Loss 0.6355756295573134
MCC 0.502205606865622
AUC 0.7449502317031278
==================================
code_gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=69.51927961775606, gamma=3.359818286283781e-05,
                     probability=True))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.40      0.57         5
           2       0.85      0.96      0.90        24
           3       1.00      1.00      1.00         1
           4       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1

    accuracy                           0.86        35
   macro avg       0.79      0.77      0.75        35
weighted avg       0.85      0.86      0.83        35

Accuracy predict 0.8571428571428571
Loss 0.3964154550593098
MCC 0.7043488327089981
AUC 0.9930328146262367
==================================
gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=69.51927961775606, gamma=3.359818286283781e-05,
                     probability=True))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.40      1.00      0.57         2
           1       1.00      0.40      0.57         5
           2       0.88      0.96      0.92        24
           3       1.00      1.00      1.00         1
           4       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.83        35
   macro avg       0.61      0.62      0.58        35
weighted avg       0.83      0.83      0.80        35

Accuracy predict 0.8285714285714286
Loss 0.5243827526015272
MCC 0.6532375333166035
AUC 0.8531767141441267
==================================
problem_code
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=69.51927961775606, gamma=3.359818286283781e-05,
                     probability=True))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.80      0.89         5
           2       0.83      1.00      0.91        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.86        35
   macro avg       0.40      0.40      0.40        35
weighted avg       0.77      0.86      0.81        35

Accuracy predict 0.8571428571428571
Loss 0.6210435998722373
MCC 0.6969038952728474
AUC 0.4996681413166579
==================================
code
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=69.51927961775606, gamma=3.359818286283781e-05,
                     probability=True))])
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.60      0.75         5
           2       0.92      1.00      0.96        24
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       0.50      1.00      0.67         1
           6       0.00      0.00      0.00         1

    accuracy                           0.91        35
   macro avg       0.77      0.80      0.77        35
weighted avg       0.90      0.91      0.90        35

Accuracy predict 0.9142857142857143
Loss 0.4153890747370845
MCC 0.8278141580834736
AUC 0.7482943594104309
==================================
MLP
problemall
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.40      0.57         5
           2       0.89      1.00      0.94        24
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.89        35
   macro avg       0.79      0.77      0.76        35
weighted avg       0.88      0.89      0.86        35

Accuracy predict 0.8857142857142857
Loss 0.88137764
MCC 0.7687149140270526
AUC 0.8652482117893608
==================================
problem_gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.40      0.57         5
           2       0.83      1.00      0.91        24
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.86        35
   macro avg       0.69      0.63      0.64        35
weighted avg       0.82      0.86      0.82        35

Accuracy predict 0.8571428571428571
Loss 1.9035244
MCC 0.7041911181716715
AUC 0.8329292255650952
==================================
code_gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])
              precision    recall  f1-score   support

           0       0.40      1.00      0.57         2
           1       1.00      0.40      0.57         5
           2       0.85      0.92      0.88        24
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.80        35
   macro avg       0.61      0.62      0.57        35
weighted avg       0.80      0.80      0.77        35

Accuracy predict 0.8
Loss 1.0000815
MCC 0.5912773336795273
AUC 0.8585029276891829
==================================
gries
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.20      0.33         5
           2       0.92      1.00      0.96        24
           3       0.50      1.00      0.67         1
           4       1.00      1.00      1.00         1
           5       0.50      1.00      0.67         1
           6       0.00      0.00      0.00         1

    accuracy                           0.86        35
   macro avg       0.66      0.74      0.63        35
weighted avg       0.87      0.86      0.82        35

Accuracy predict 0.8571428571428571
Loss 0.93434036
MCC 0.7175556127150616
AUC 0.9464236311153256
==================================
problem_code
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.80      0.89         5
           2       0.86      1.00      0.92        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.86        35
   macro avg       0.41      0.40      0.40        35
weighted avg       0.79      0.86      0.82        35

Accuracy predict 0.8571428571428571
Loss 1.3170248
MCC 0.6940003733742952
AUC 0.6376190476190475
==================================
code
Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 MLPClassifier(hidden_layer_sizes=(100, 100, 100),
                               learning_rate='adaptive'))])
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.80      0.89         5
           2       0.96      1.00      0.98        24
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1

    accuracy                           0.97        35
   macro avg       0.99      0.97      0.98        35
weighted avg       0.97      0.97      0.97        35

Accuracy predict 0.9714285714285714
Loss 0.17550893
MCC 0.9434843870463827
AUC 0.9947619047619047
==================================
Random Forest
problemall
RandomForestClassifier(max_depth=15, n_estimators=80)
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.40      0.57         5
           2       0.77      1.00      0.87        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.80        35
   macro avg       0.40      0.34      0.35        35
weighted avg       0.73      0.80      0.74        35

Accuracy predict 0.8
Loss 0.48698443137299663
MCC 0.5590396812926076
AUC 1.0
==================================
problem_gries
RandomForestClassifier(max_depth=15, n_estimators=80)
              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       1.00      0.40      0.57         5
           2       0.77      1.00      0.87        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.77        35
   macro avg       0.32      0.27      0.28        35
weighted avg       0.70      0.77      0.71        35

Accuracy predict 0.7714285714285715
Loss 0.5220066511929958
MCC 0.4709027946023316
AUC 0.9804372165532881
==================================
code_gries
RandomForestClassifier(max_depth=15, n_estimators=80)

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       1.00      0.60      0.75         5
           2       0.83      1.00      0.91        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.83        35
   macro avg       0.48      0.44      0.45        35
weighted avg       0.77      0.83      0.79        35

Accuracy predict 0.8285714285714286
Loss 0.5770867415528702
MCC 0.6262964791113548
AUC 0.8407874459885942
==================================
gries
RandomForestClassifier(max_depth=15, n_estimators=80)
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         2
           1       0.75      0.60      0.67         5
           2       0.88      0.96      0.92        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.83        35
   macro avg       0.45      0.51      0.46        35
weighted avg       0.77      0.83      0.79        35

Accuracy predict 0.8285714285714286
Loss 0.5583057724649848
MCC 0.6420862409078028
AUC 0.858408118080669
==================================
problem_code
RandomForestClassifier(max_depth=15, n_estimators=80)
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.20      0.33         5
           2       0.75      1.00      0.86        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.77        35
   macro avg       0.39      0.31      0.31        35
weighted avg       0.71      0.77      0.69        35

Accuracy predict 0.7714285714285715
Loss 0.6038807761024114
MCC 0.4834937784152282
AUC 0.8656599995070492
==================================
code
RandomForestClassifier(max_depth=15, n_estimators=80)
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.80      0.89         5
           2       0.86      1.00      0.92        24
           3       1.00      1.00      1.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.89        35
   macro avg       0.55      0.54      0.54        35
weighted avg       0.82      0.89      0.85        35

Accuracy predict 0.8857142857142857
Loss 0.5550106764761491
MCC 0.7628106086946927
AUC 0.9945188492063493
==================================
Voting
problemall

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=80))],
                 voting='soft')
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.60      0.75         5
           2       0.89      1.00      0.94        24
           3       0.00      0.00      0.00         1
           4       0.50      1.00      0.67         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.89        35
   macro avg       0.63      0.66      0.62        35
weighted avg       0.85      0.89      0.86        35

Accuracy predict 0.8857142857142857
Loss 0.3965710545395029
MCC 0.7647928028552862
AUC 0.880952380952381
==================================
problem_gries
VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=80))],
                 voting='soft')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.40      0.57         5
           2       0.80      1.00      0.89        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.80        35
   macro avg       0.35      0.34      0.32        35
weighted avg       0.73      0.80      0.74        35

Accuracy predict 0.8
Loss 0.5581113892410432
MCC 0.5565730498088816
AUC 0.8747569444444444
==================================
code_gries
VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=80))],
                 voting='soft')
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.40      0.57         5
           2       0.88      0.96      0.92        24
           3       0.00      0.00      0.00         1
           4       0.50      1.00      0.67         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.83        35
   macro avg       0.58      0.62      0.57        35
weighted avg       0.83      0.83      0.81        35

Accuracy predict 0.8285714285714286
Loss 0.4650488277517786
MCC 0.6493003227250923
AUC 0.7757512536012795
==================================
gries
VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=80))],
                 voting='soft')
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.40      0.57         5
           2       0.86      1.00      0.92        24
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.86        35
   macro avg       0.65      0.63      0.61        35
weighted avg       0.83      0.86      0.82        35

Accuracy predict 0.8571428571428571
Loss 0.49169177828381755
MCC 0.70276050320023
AUC 0.8354332144552661
==================================
problem_code
VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=80))],
                 voting='soft')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       0.60      0.60      0.60         5
           2       0.88      0.96      0.92        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.83        35
   macro avg       0.45      0.51      0.47        35
weighted avg       0.76      0.83      0.79        35

Accuracy predict 0.8285714285714286
Loss 0.46241217065798507
MCC 0.6380027240305742
AUC 0.8460776062561777
==================================
code
VotingClassifier(estimators=[('mlp',
                              Pipeline(steps=[('scaler', StandardScaler()),
                                              ('classifier',
                                               MLPClassifier(hidden_layer_sizes=(100,
                                                                                 100,
                                                                                 100),
                                                             learning_rate='adaptive'))])),
                             ('rf',
                              RandomForestClassifier(max_depth=15,
                                                     n_estimators=80))],
                 voting='soft')
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         5
           2       0.96      1.00      0.98        24
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.97        35
   macro avg       0.85      0.86      0.85        35
weighted avg       0.94      0.97      0.96        35

Accuracy predict 0.9714285714285714
Loss 0.3014092763692683
MCC 0.9433430952489882
AUC 0.9997569444444444
==================================
Stacking
problemall

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=80))],
                   final_estimator=LogisticRegression())
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.40      0.57         5
           2       0.83      1.00      0.91        24
           3       1.00      1.00      1.00         1
           4       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.86        35
   macro avg       0.69      0.63      0.64        35
weighted avg       0.82      0.86      0.82        35

Accuracy predict 0.8571428571428571
Loss 0.40330840536410384
MCC 0.7041911181716715
AUC 0.8659134070294784
==================================
problem_gries
StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=80))],
                   final_estimator=LogisticRegression())

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.40      0.57         5
           2       0.80      1.00      0.89        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.83        35
   macro avg       0.54      0.49      0.49        35
weighted avg       0.78      0.83      0.78        35

Accuracy predict 0.8285714285714286
Loss 0.6310691176314871
MCC 0.6346351669793114
AUC 0.8387736911552904
==================================
code_gries
StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=80))],
                   final_estimator=LogisticRegression())
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       0.75      0.60      0.67         5
           2       0.89      1.00      0.94        24
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.89        35
   macro avg       0.66      0.66      0.66        35
weighted avg       0.83      0.89      0.85        35

Accuracy predict 0.8857142857142857
Loss 0.5134769464668597
MCC 0.7606104624063137
AUC 0.8326647058945195
==================================
gries
StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=80))],
                   final_estimator=LogisticRegression())
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.40      0.57         5
           2       0.89      1.00      0.94        24
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.89        35
   macro avg       0.79      0.77      0.76        35
weighted avg       0.88      0.89      0.86        35

Accuracy predict 0.8857142857142857
Loss 0.45884884380992463
MCC 0.7687149140270526
AUC 0.8347863493476847
==================================
problem_code
StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=80))],
                   final_estimator=LogisticRegression())

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.60      0.75         5
           2       0.80      1.00      0.89        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.83        35
   macro avg       0.40      0.37      0.38        35
weighted avg       0.75      0.83      0.77        35

Accuracy predict 0.8285714285714286
Loss 0.6479507033495802
MCC 0.6295662366690628
AUC 0.8739554011259676
==================================
code
StackingClassifier(estimators=[('mlp',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 MLPClassifier(hidden_layer_sizes=(100,
                                                                                   100,
                                                                                   100),
                                                               learning_rate='adaptive'))])),
                               ('rf',
                                RandomForestClassifier(max_depth=15,
                                                       n_estimators=80))],
                   final_estimator=LogisticRegression())
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       1.00      0.60      0.75         5
           2       0.80      1.00      0.89        24
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         1
           6       0.00      0.00      0.00         1

    accuracy                           0.83        35
   macro avg       0.54      0.44      0.47        35
weighted avg       0.78      0.83      0.78        35

Accuracy predict 0.8285714285714286
Loss 0.5419813466659165
MCC 0.6298318068252363
AUC 0.8267048423453703
==================================

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [50]:
import pandas as pd
dfe=pd.DataFrame({
    "Model":ml_names,
    "Ablation":abl_names,
    "Accuracy_predict":accuracies_predict,
    "Loss":loss_predict,
    "Time_predict":times_predict,
    "MCC":mccs_predict,
    "AUC":aucpr_predict
})

In [51]:
dfe

,Model,Ablation,Accuracy_predict,Loss,Time_predict,MCC,AUC
0,KNN,problemall,0.857143,0.260038,0.186745,0.703264,0.873677
1,KNN,problem_gries,0.857143,0.314491,0.148788,0.701740,0.852067
2,KNN,code_gries,0.885714,0.303079,0.149793,0.777944,0.878333
3,KNN,gries,0.857143,0.765357,0.111068,0.729047,0.800935
4,KNN,problem_code,0.742857,1.202650,0.075899,0.480972,0.833816
5,KNN,code,0.914286,0.207484,0.039625,0.831720,0.979960
6,SVM,problemall,0.800000,0.535198,0.235237,0.568176,0.758408
7,SVM,problem_gries,0.771429,0.635576,0.202938,0.502206,0.744950
8,SVM,code_gries,0.857143,0.396415,0.191295,0.704349,0.993033
9,SVM,gries,0.828571,0.524383,0.131582,0.653238,0.853177
10,SVM,problem_code,0.857143,0.621044,0.184317,0.696904,0.499668
11,SVM,code,0.914286,0.415389,0.051158,0.827814,0.748294
12,MLP,problemall,0.885714,0.881378,0.003468,0.768715,0.865248
13,MLP,problem_gries,0.857143,1.903524,0.002189,0.704191,0.832929
14,MLP,code_gries,0.800000,1.000082,0.002342,0.591277,0.858503
15,MLP,gries,0.857143,0.934340,0.002145,0.717556,0.946424
16,MLP,problem_code,0.857143,1.317025,0.001708,0.694000,0.637619
17,MLP,code,0.971429,0.175509,0.001432,0.943484,0.994762
18,Random Forest,problemall,0.800000,0.486984,0.008644,0.559040,1.000000
19,Random Forest,problem_gries,0.771429,0.522007,0.006054,0.470903,0.980437
20,Random Forest,code_gries,0.828571,0.577087,0.008390,0.626296,0.840787
21,Random Forest,gries,0.828571,0.558306,0.006234,0.642086,0.858408
22,Random Forest,problem_code,0.771429,0.603881,0.005205,0.483494,0.865660
23,Random Forest,code,0.885714,0.555011,0.006516,0.762811,0.994519
24,Voting,problemall,0.885714,0.396571,0.011130,0.764793,0.880952
25,Voting,problem_gries,0.800000,0.558111,0.010850,0.556573,0.874757
26,Voting,code_gries,0.828571,0.465049,0.010983,0.649300,0.775751
27,Voting,gries,0.857143,0.491692,0.011283,0.702761,0.835433
28,Voting,problem_code,0.828571,0.462412,0.010272,0.638003,0.846078
29,Voting,code,0.971429,0.301409,0.010190,0.943343,0.999757
30,Stacking,problemall,0.857143,0.403308,0.011885,0.704191,0.865913
31,Stacking,problem_gries,0.828571,0.631069,0.016638,0.634635,0.838774
32,Stacking,code_gries,0.885714,0.513477,0.011720,0.760610,0.832665
33,Stacking,gries,0.885714,0.458849,0.011473,0.768715,0.834786
34,Stacking,problem_code,0.828571,0.647951,0.010041,0.629566,0.873955
35,Stacking,code,0.828571,0.541981,0.010145,0.629832,0.826705

In [52]:
dfe.to_csv(path+"graph_externData_ablationsResults.csv",index=False)

In [53]:
dfe=pd.read_csv(path+"graph_externData_ablationsResults.csv")
dfe

,Model,Ablation,Accuracy_predict,Loss,Time_predict,MCC,AUC
0,KNN,problemall,0.857143,0.260038,0.186745,0.703264,0.873677
1,KNN,problem_gries,0.857143,0.314491,0.148788,0.701740,0.852067
2,KNN,code_gries,0.885714,0.303079,0.149793,0.777944,0.878333
3,KNN,gries,0.857143,0.765357,0.111068,0.729047,0.800935
4,KNN,problem_code,0.742857,1.202650,0.075899,0.480972,0.833816
5,KNN,code,0.914286,0.207484,0.039625,0.831720,0.979960
6,SVM,problemall,0.800000,0.535198,0.235237,0.568176,0.758408
7,SVM,problem_gries,0.771429,0.635576,0.202938,0.502206,0.744950
8,SVM,code_gries,0.857143,0.396415,0.191295,0.704349,0.993033
9,SVM,gries,0.828571,0.524383,0.131582,0.653238,0.853177
10,SVM,problem_code,0.857143,0.621044,0.184317,0.696904,0.499668
11,SVM,code,0.914286,0.415389,0.051158,0.827814,0.748294
12,MLP,problemall,0.885714,0.881378,0.003468,0.768715,0.865248
13,MLP,problem_gries,0.857143,1.903524,0.002189,0.704191,0.832929
14,MLP,code_gries,0.800000,1.000082,0.002342,0.591277,0.858503
15,MLP,gries,0.857143,0.934340,0.002145,0.717556,0.946424
16,MLP,problem_code,0.857143,1.317025,0.001708,0.694000,0.637619
17,MLP,code,0.971429,0.175509,0.001432,0.943484,0.994762
18,Random Forest,problemall,0.800000,0.486984,0.008644,0.559040,1.000000
19,Random Forest,problem_gries,0.771429,0.522007,0.006054,0.470903,0.980437
20,Random Forest,code_gries,0.828571,0.577087,0.008390,0.626296,0.840787
21,Random Forest,gries,0.828571,0.558306,0.006234,0.642086,0.858408
22,Random Forest,problem_code,0.771429,0.603881,0.005205,0.483494,0.865660
23,Random Forest,code,0.885714,0.555011,0.006516,0.762811,0.994519
24,Voting,problemall,0.885714,0.396571,0.011130,0.764793,0.880952
25,Voting,problem_gries,0.800000,0.558111,0.010850,0.556573,0.874757
26,Voting,code_gries,0.828571,0.465049,0.010983,0.649300,0.775751
27,Voting,gries,0.857143,0.491692,0.011283,0.702761,0.835433
28,Voting,problem_code,0.828571,0.462412,0.010272,0.638003,0.846078
29,Voting,code,0.971429,0.301409,0.010190,0.943343,0.999757
30,Stacking,problemall,0.857143,0.403308,0.011885,0.704191,0.865913
31,Stacking,problem_gries,0.828571,0.631069,0.016638,0.634635,0.838774
32,Stacking,code_gries,0.885714,0.513477,0.011720,0.760610,0.832665
33,Stacking,gries,0.885714,0.458849,0.011473,0.768715,0.834786
34,Stacking,problem_code,0.828571,0.647951,0.010041,0.629566,0.873955
35,Stacking,code,0.828571,0.541981,0.010145,0.629832,0.826705